'use client';
import {AdministrationRecords,AdministrationSection} from '@/components/ui/administration-records';
import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {apiRequest} from '@/lib/apiClient';
import {ApiClientError,getErrorMessage} from '@/lib/errors';
import {FrozenCommand,CommandOwner} from '@/lib/frozen-command';
import {Button,Card,ErrorBanner,Input,SuccessBanner} from '@/components/ui';
import {AccountOffboarding} from '@/components/ui/account-offboarding';
import {AdministrationDialog} from '@/components/ui/administration-dialog';
import {HomeOrganization} from '@/components/ui/home-organization';
import {ContextHelp} from '@/components/ui/context-help';
import type {Page} from '@/shared/types';
import type {OffboardingResult} from '@/lib/contracts/account-offboarding';
type Account={userId:string;name:string;email:string;companyName:string;disabledAt:string|null};
type Review={id:string;projectName:string;subjectUserId:string;subjectName:string;subjectEmail:string;reason:string;status:string};
type Resolution={reviewId:string;disposition:string;reason:string;tenantEventId:string|null;snapshot:string;confirmed:true};
function ReviewEditor({review,onResolved,onLockChange,owner,onClose}:{owner:CommandOwner;review:Review;onResolved:()=>void;onLockChange:(value:boolean)=>void;onClose:()=>void}){
 const token=`review:${review.id}`;useSyncExternalStore(owner.subscribe,owner.snapshot,owner.snapshot);const blocked=owner.blocked(token);
 const [evidence,setEvidence]=useState<{review:Record<string,unknown>;snapshot:string}>(),[reason,setReason]=useState(''),[consent,setConsent]=useState(false),[tenant,setTenant]=useState<OffboardingResult>(),[openTenant,setOpenTenant]=useState(false),[error,setError]=useState<string>(),[done,setDone]=useState(false),[revision,setRevision]=useState(0);
 const [tenantLocked,setTenantLocked]=useState(false);const tenantLock=useRef(false);
 const gate=useRef(new FrozenCommand<Resolution>());
 const url=`/api/accounts/offboarding-reviews/${review.id}`;
 async function load(){setError(undefined);setEvidence(undefined);setConsent(false);try{setEvidence(await apiRequest(url));}catch(cause){setError(getErrorMessage(cause,'Unable to load review evidence.'));}}
 useEffect(()=>{void load();},[review.id]);
 async function resolve(disposition:string){if(!evidence||tenantLock.current||!owner.claim(token))return;const frozen=gate.current.begin({reviewId:review.id,disposition,reason:reason.trim(),tenantEventId:disposition==='TENANT_ACCOUNT_DISABLED'?tenant?.eventId??null:null,snapshot:evidence.snapshot,confirmed:true},crypto.randomUUID());if(!frozen){if(!gate.current.locked)owner.release(token);return;}onLockChange(true);setRevision(n=>n+1);setError(undefined);
 try{await apiRequest(url,{method:'POST',body:frozen.body,headers:{'Idempotency-Key':frozen.key}});gate.current.success();setDone(true);onResolved();}
 catch(cause){gate.current.fail(cause instanceof ApiClientError?cause.status:undefined);setError(getErrorMessage(cause,'Outcome uncertain. Retry the same resolution.'));}finally{if(!gate.current.locked)owner.release(token);onLockChange(gate.current.locked);setRevision(n=>n+1);}}
 void revision;
 return <AdministrationDialog title={`Review ${review.subjectName} · ${review.projectName}`} closeDisabled={blocked||tenantLocked||gate.current.pending||!!gate.current.command&&!gate.current.stale} onClose={()=>{if(!blocked&&!tenantLocked&&gate.current.reload()){owner.release(token);onClose();}}}><p>Project removal reason: {review.reason}</p>{error&&<ErrorBanner message={error}/>}{done?<SuccessBanner message="Review resolved. No account action was inferred."/>:evidence&&<>
 <p>Original local lifecycle evidence: {String(evidence.review.local_event_id)}. Tenant disable requires its own preview and confirmation.</p>
 <Button variant="secondary" disabled={blocked||gate.current.locked||tenantLocked} onClick={()=>setOpenTenant(true)}>Open separate tenant account decision</Button>
 {openTenant&&<AccountOffboarding commandOwner={owner} subjectUserId={review.subjectUserId} subjectName={review.subjectName} scope={{kind:'TENANT_ACCOUNT'}} onCancel={()=>setOpenTenant(false)} onResult={setTenant} onLockChange={value=>{tenantLock.current=value;setTenantLocked(value);onLockChange(value||gate.current.locked);}}/>}
 <label className="field"><span className="field-label">Review resolution reason (10–1000 characters)</span><Input value={reason} maxLength={1000} disabled={blocked||gate.current.locked||tenantLocked} onChange={e=>setReason(e.target.value)}/></label><label className="checkbox-row"><input type="checkbox" checked={consent} disabled={blocked||gate.current.locked||tenantLocked} onChange={e=>setConsent(e.target.checked)}/><span>I confirm this review resolution.</span></label>
 <div className="row"><Button disabled={blocked||tenantLocked||!consent||reason.trim().length<10||gate.current.pending||gate.current.stale||!!gate.current.command&&gate.current.command.body.disposition!=='NO_FURTHER_ACTION'} onClick={()=>void resolve('NO_FURTHER_ACTION')}>No further action</Button><Button disabled={blocked||tenantLocked||!tenant?.eventId||!consent||reason.trim().length<10||gate.current.pending||gate.current.stale||!!gate.current.command&&gate.current.command.body.disposition!=='TENANT_ACCOUNT_DISABLED'} onClick={()=>void resolve('TENANT_ACCOUNT_DISABLED')}>Link separately confirmed tenant disable</Button></div>{gate.current.command&&!gate.current.pending&&!gate.current.stale&&<p role="status">Retry the same resolution. Its body and key are retained.</p>}{gate.current.stale&&<p role="alert">Review changed. Reload before resolving.</p>}
 </>}<Button variant="secondary" disabled={blocked||tenantLocked||gate.current.pending||!!gate.current.command&&!gate.current.stale} onClick={()=>{if(!owner.blocked(token)&&gate.current.reload()){owner.release(token);onLockChange(false);void load();}}}>Reload review</Button></AdministrationDialog>;
}
export default function AccountsPage(){
 const owner=useRef(new CommandOwner()).current;const locked=useSyncExternalStore(owner.subscribe,owner.snapshot,owner.snapshot)!==null;const setLocked=()=>{};
 const [accountSelection,setAccountSelection]=useState<string[]>([]),[accountQueue,setAccountQueue]=useState<Account[]>([]);
 const [accounts,setAccounts]=useState<Page<Account>>(),[reviews,setReviews]=useState<Page<Review>>(),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[reviewOffset,setReviewOffset]=useState(0),[status,setStatus]=useState('PENDING'),[selected,setSelected]=useState<Account>(),[review,setReview]=useState<Review>(),[error,setError]=useState<string>(),[revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;setError(undefined);Promise.all([apiRequest<{accounts:Page<Account>}>(`/api/accounts?search=${encodeURIComponent(search)}&offset=${offset}&limit=25`),apiRequest<{reviews:Page<Review>}>(`/api/accounts/offboarding-reviews?status=${status}&offset=${reviewOffset}&limit=25`)]).then(([a,r])=>{if(active){setAccounts(a.accounts);setAccountSelection([]);setReviews(r.reviews);}}).catch(cause=>{if(active)setError(getErrorMessage(cause,'Current Central IT authority is required to read tenant accounts and reviews.'));});return()=>{active=false;};},[search,offset,status,reviewOffset,revision]);
 return <div className="stack"><div className="heading-with-help"><h1>Tenant Accounts and Central IT Reviews</h1><ContextHelp label="Tenant accounts and Central IT reviews">Project access removal and tenant account disable are separate decisions. Inspect current evidence and confirm each action independently. Account records and review filters apply to the loaded pages.</ContextHelp></div>{error&&<ErrorBanner message={error}/>}
 <Card title="Tenant Home Organization" help="Axiom provisions this account-bound company. Contact Axiom customer support for changes."><HomeOrganization owner={owner} disabled={!!selected||!!review}/></Card>
 <Card title="Tenant Accounts"><div className="stack"><label className="field"><span className="field-label">Find a person</span><Input disabled={locked} value={search} maxLength={100} onChange={e=>{setSearch(e.target.value);setOffset(0);setSelected(undefined);}}/></label>{selected&&<AccountOffboarding commandOwner={owner} key={selected.userId} subjectUserId={selected.userId} subjectName={selected.name} scope={{kind:'TENANT_ACCOUNT'}} onLockChange={setLocked} onResult={()=>setRevision(n=>n+1)} onCancel={()=>{setSelected(undefined);setAccountQueue([]);setAccountSelection([]);}} onNext={accountQueue.length>1?()=>{const remaining=accountQueue.slice(1);setAccountQueue(remaining);setSelected(remaining[0]);}:undefined}/>}{accountQueue.length>1&&<div className="row"><span>{accountQueue.length} accounts remaining in this review queue.</span><Button variant="secondary" disabled={locked} onClick={()=>{const remaining=accountQueue.slice(1);setAccountQueue(remaining);setSelected(remaining[0]);}}>Review next account</Button></div>}
 <AdministrationSection title="Account Records" open locked={locked}><AdministrationRecords label="tenant accounts on this page" rows={accounts?.data??[]} id={a=>a.userId} columns={[{key:'name',label:'Name',text:a=>a.name},{key:'email',label:'Email',text:a=>a.email},{key:'company',label:'Company',text:a=>a.companyName},{key:'access',label:'Account',text:a=>a.disabledAt?'Disabled':'Active'}]} selected={accountSelection} onSelection={setAccountSelection} disabled={locked} selectionActions={<Button variant="secondary" disabled={locked||!accountSelection.length} onClick={()=>{const queue=accounts!.data.filter(a=>accountSelection.includes(a.userId));setAccountQueue(queue);setSelected(queue[0]);}}>Review selected tenant disables</Button>} actions={a=><Button variant="secondary" disabled={locked} onClick={()=>{setAccountQueue([]);setSelected(a);}}>Preview tenant disable</Button>}/></AdministrationSection>{accounts&&!accounts.total&&<p>No matching accounts.</p>}<div className="row"><Button variant="secondary" disabled={locked||!offset} onClick={()=>setOffset(n=>Math.max(0,n-25))}>Previous accounts</Button><Button variant="secondary" disabled={locked||!accounts||offset+25>=accounts.total} onClick={()=>setOffset(n=>n+25)}>Next accounts</Button></div></div></Card>
 <Card title="Central IT Review Queue" description="This durable queue remains available independently of notification delivery."><div className="stack"><label className="field"><span className="field-label">Review status</span><select disabled={locked} className="select" value={status} onChange={e=>{setStatus(e.target.value);setReviewOffset(0);setReview(undefined);}}><option value="PENDING">Pending</option><option value="RESOLVED">Resolved</option></select></label><AdministrationSection title="Review Records" open locked={locked}><AdministrationRecords label="Central IT reviews on this page" rows={reviews?.data??[]} id={r=>r.id} columns={[{key:'name',label:'Person',text:r=>r.subjectName},{key:'email',label:'Email',text:r=>r.subjectEmail},{key:'project',label:'Project',text:r=>r.projectName},{key:'status',label:'Status',text:r=>r.status},{key:'reason',label:'Reason',text:r=>r.reason}]} disabled={locked} actions={r=>r.status==='PENDING'?<Button variant="secondary" disabled={locked} onClick={()=>setReview(r)}>Open review</Button>:null}/></AdministrationSection>{reviews&&!reviews.total&&<p>No {status.toLowerCase()} reviews.</p>}<div className="row"><Button variant="secondary" disabled={locked||!reviewOffset} onClick={()=>setReviewOffset(n=>Math.max(0,n-25))}>Previous reviews</Button><Button variant="secondary" disabled={locked||!reviews||reviewOffset+25>=reviews.total} onClick={()=>setReviewOffset(n=>n+25)}>Next reviews</Button></div>{review&&<ReviewEditor owner={owner} key={review.id} review={review} onLockChange={setLocked} onResolved={()=>setRevision(n=>n+1)} onClose={()=>setReview(undefined)}/>}</div></Card>
 </div>;
}
