import assert from 'node:assert/strict';
import test from 'node:test';
import {initialProtectedEditor,reduceProtectedEditor,canConfirmProtectedResolution,coveragePreview,protectedResolutionFailure} from '../../src/lib/protected-obligations-view';
import type {ProtectedReadResult,ReviewerCandidate,ReviewerObligation} from '../../src/modules/tenancy/application/protected-obligations.types';
import {ApiClientError} from '../../src/lib/errors';
import type {UUID} from '../../src/shared/types';
const id=(n:number)=>`99000000-0000-4000-8000-${String(n).padStart(12,'0')}` as UUID;
const obligation:ReviewerObligation={grantId:id(30),responsibility:'SURVEY_REVIEWER',areaId:id(21),areaName:'Area1',canResolve:true,unsupportedReason:null,addedCoverageIntent:null,addedIndividualAssignment:null};
const candidate:ReviewerCandidate={userId:id(12),name:'Jason',email:'jason@example.test',replacementGrantId:null,replacementAssignmentId:null,canReuse:false,missingReviewGrant:true,missingIndividualAssignment:true};
const detail:Extract<ProtectedReadResult,{mode:'obligations'}>={mode:'obligations',project:{status:'ACTIVE',crewBuild:'FULL'},person:{userId:id(11),name:'John',email:'john@example.test',role:'SURVEY_SUPERINTENDENT',active:true,responsibilityCount:1,actingCount:0},obligations:{data:[obligation],total:1,limit:10,offset:0},actingCount:0,departmentMembershipCount:0,snapshotToken:'a'.repeat(32)};
function ready(){let s=initialProtectedEditor();s=reduceProtectedEditor(s,{type:'person',userId:id(11)});s=reduceProtectedEditor(s,{type:'load',generation:1});s=reduceProtectedEditor(s,{type:'obligations',generation:1,data:detail});s=reduceProtectedEditor(s,{type:'grant',grant:obligation});s=reduceProtectedEditor(s,{type:'load',generation:2});s=reduceProtectedEditor(s,{type:'candidates',generation:2,data:{mode:'candidates',candidates:{data:[candidate],total:1,limit:10,offset:0},snapshotToken:detail.snapshotToken}});s=reduceProtectedEditor(s,{type:'candidate',candidate});s=reduceProtectedEditor(s,{type:'intent',intent:'TEMPORARY'});s=reduceProtectedEditor(s,{type:'additional',confirmed:true});return reduceProtectedEditor(s,{type:'confirm',confirmed:true});}
test('additional_requires_explicit_confirmation_intent',()=>{const s=ready();assert.equal(canConfirmProtectedResolution(s),true);assert.equal(canConfirmProtectedResolution(reduceProtectedEditor(s,{type:'intent',intent:null})),false);assert.equal(canConfirmProtectedResolution(reduceProtectedEditor(s,{type:'additional',confirmed:false})),false);assert.equal(canConfirmProtectedResolution(reduceProtectedEditor(s,{type:'confirm',confirmed:false})),false);});
test('candidate_token_mismatch_blocks; cancel_reopen_keeps_stale',()=>{let s=ready();s=reduceProtectedEditor(s,{type:'load',generation:3});s=reduceProtectedEditor(s,{type:'candidates',generation:3,data:{mode:'candidates',candidates:{data:[candidate],total:1,limit:10,offset:0},snapshotToken:'b'.repeat(32)}});assert.equal(s.originalToken,detail.snapshotToken);assert.equal(s.stale,true);assert.equal(canConfirmProtectedResolution(s),false);s=reduceProtectedEditor(s,{type:'cancel'});s=reduceProtectedEditor(s,{type:'grant',grant:obligation});assert.equal(s.stale,true);assert.equal(reduceProtectedEditor(s,{type:'reload'}).stale,false);});
test('late_previous_person_response_ignored',()=>{let s=ready();s=reduceProtectedEditor(s,{type:'person',userId:id(13)});s=reduceProtectedEditor(s,{type:'load',generation:4});assert.deepEqual(reduceProtectedEditor(s,{type:'obligations',generation:2,data:detail}),s);});
test('uncertain_retry_freezes_person_mode_intent_key',()=>{let s=ready();s=reduceProtectedEditor(s,{type:'begin',key:'stable-key'});const attempt=s.attempt;assert.ok(attempt);assert.equal(attempt.input.expectedSnapshot,detail.snapshotToken);s=reduceProtectedEditor(s,{type:'uncertain',message:'Response lost'});for(const event of [{type:'person',userId:id(13)},{type:'intent',intent:'PERMANENT'},{type:'mode',mode:'reuse'},{type:'additional',confirmed:false},{type:'cancel'},{type:'reload'},{type:'grant',grant:obligation}] as const)assert.deepEqual(reduceProtectedEditor(s,event),s);const retry=reduceProtectedEditor(s,{type:'retry'});assert.deepEqual(retry.attempt,attempt);assert.equal(retry.pending,true);assert.equal(canConfirmProtectedResolution(s),false);});
test('pending_blocks_duplicate_begin_and_selection; definitive_failure_unlocks',()=>{let s=reduceProtectedEditor(ready(),{type:'begin',key:'first'});assert.deepEqual(reduceProtectedEditor(s,{type:'begin',key:'second'}),s);s=reduceProtectedEditor(s,{type:'failure',message:'Denied'});assert.equal(s.attempt,null);assert.equal(s.pending,false);assert.notDeepEqual(reduceProtectedEditor(s,{type:'intent',intent:'PERMANENT'}),s);});
test('grant_only_preview_truthful',()=>{assert.deepEqual(coveragePreview({...candidate,missingReviewGrant:false,replacementGrantId:id(50)}),{review:'Reuse existing review grant',individual:'Add individual Area assignment'});assert.deepEqual(coveragePreview({...candidate,missingIndividualAssignment:false,replacementAssignmentId:id(51)}),{review:'Add review grant',individual:'Reuse existing individual Area assignment'});});
test('later_obligation_page_cannot_overwrite_displayed_token; reload_invalidates_inflight',()=>{let s=ready();s=reduceProtectedEditor(s,{type:'load',generation:3});s=reduceProtectedEditor(s,{type:'obligations',generation:3,data:{...detail,snapshotToken:'b'.repeat(32)}});assert.equal(s.originalToken,detail.snapshotToken);assert.equal(s.stale,true);s=reduceProtectedEditor(s,{type:'reload'});assert.deepEqual(reduceProtectedEditor(s,{type:'obligations',generation:3,data:detail}),s);});
test('archived_evidence_never_confirms; reuse_needs_both_witnesses',()=>{let s=ready();s={...s,detail:{...detail,project:{...detail.project,status:'ARCHIVED'}}};assert.equal(canConfirmProtectedResolution(s),false);s=reduceProtectedEditor(ready(),{type:'mode',mode:'reuse'});s=reduceProtectedEditor(s,{type:'confirm',confirmed:true});assert.equal(canConfirmProtectedResolution(s),false);});

test('every_definitive_409_latches_until_deliberate_reload',()=>{let s=reduceProtectedEditor(ready(),{type:'begin',key:'conflict'});const event=protectedResolutionFailure(new ApiClientError('CONFLICT','Coverage changed',409,'CONFLICT'));assert.equal(event.type,'stale');s=reduceProtectedEditor(s,event);assert.equal(s.stale,true);assert.match(s.error!,/Coverage changed/);s=reduceProtectedEditor(s,{type:'cancel'});s=reduceProtectedEditor(s,{type:'grant',grant:obligation});assert.equal(s.stale,true);assert.equal(canConfirmProtectedResolution(s),false);assert.equal(reduceProtectedEditor(s,{type:'reload'}).stale,false);assert.equal(protectedResolutionFailure(new ApiClientError('INTERNAL_ERROR','Failed',500)).type,'uncertain');assert.equal(protectedResolutionFailure(new Error('Network failed')).type,'uncertain');assert.equal(protectedResolutionFailure(new ApiClientError('FORBIDDEN','Denied',403)).type,'failure');});
