import test from 'node:test';
import assert from 'node:assert/strict';
import {ApiClientError} from '../../src/lib/errors';
import type {UUID} from '../../src/shared/types';
import type {SuperintendentAreaReadResult,SuperintendentAreaAssignment,SuperintendentAreaReplacement} from '../../src/modules/tenancy/application/superintendent-area.types';
const id=(n:number)=>`99010000-0000-4000-8000-${String(n).padStart(12,'0')}` as UUID;
const assignment:SuperintendentAreaAssignment={assignmentId:id(40),areaId:id(21),areaName:'Area1',createdAt:'2026-10-01',retired:false,depth:0,parentId:null,duplicateIndividualCount:1,overlappingIndividualCount:1,responsibilityCount:0,actingCount:0,reportingCount:0,canUnlink:true,refusalReason:null};
const replacement:SuperintendentAreaReplacement={userId:id(12),name:'Jason',email:'jason@example.test',replacementGrantId:id(50),replacementAssignmentId:id(51)};
const common={project:{status:'ACTIVE' as const,crewBuild:'FULL' as const},person:{userId:id(11),name:'John',email:'john@example.test',role:'SURVEY_SUPERINTENDENT' as const,active:true},snapshotToken:'a'.repeat(32)};
const detail:SuperintendentAreaReadResult={...common,mode:'superintendent-areas',assignments:{data:[assignment],total:1,limit:10,offset:0},departmentMembershipCount:1,sharedDepartmentAssignmentCount:1};
const candidates:SuperintendentAreaReadResult={...common,mode:'superintendent-area-replacements',replacements:{data:[replacement],total:1,limit:10,offset:0}};
async function view(){return import('../../src/lib/superintendent-area-view');}
async function ready(){const v=await view(),r=v.reduceSuperintendentAreaEditor;let s=r(v.initialSuperintendentAreaEditor(),{type:'person',superintendentId:id(11)});s=r(s,{type:'load',generation:2});s=r(s,{type:'read',generation:2,data:detail});s=r(s,{type:'assignment',assignment});s=r(s,{type:'load',generation:s.generation+1});s=r(s,{type:'read',generation:s.generation,data:candidates});s=r(s,{type:'replacement',replacement});s=r(s,{type:'confirm',confirmed:true});return {v,r,s};}
test('original_token_survives_all_modes_and_cancel; duplicate preview is exact',async()=>{let {v,r,s}=await ready();assert.equal(v.canConfirmSuperintendentAreaUnlink(s),true);assert.equal(s.assignment?.duplicateIndividualCount,1);const first=s.originalToken;s=r(s,{type:'load',generation:s.generation+1});s=r(s,{type:'read',generation:s.generation,data:{...common,mode:'superintendent-area-reporting',reporting:{data:[],total:0,limit:10,offset:10}}});assert.equal(s.originalToken,first);assert.equal(r(s,{type:'cancel'}).originalToken,first);});
test('stale_latches_until_deliberate_reload including every409',async()=>{let {v,r,s}=await ready();s=r(s,{type:'load',generation:s.generation+1});s=r(s,{type:'read',generation:s.generation,data:{...candidates,snapshotToken:'b'.repeat(32)}});assert.equal(s.originalToken,'a'.repeat(32));assert.equal(s.stale,true);assert.equal(v.canConfirmSuperintendentAreaUnlink(s),false);s=r(s,{type:'cancel'});assert.equal(s.stale,true);assert.equal(r(s,{type:'reload'}).stale,false);s=r((await ready()).s,v.superintendentAreaFailure(new ApiClientError('CONFLICT','Dependency changed',409)));assert.equal(s.stale,true);});
test('late_other_person_link_page_ignored',async()=>{let {r,s}=await ready();s=r(s,{type:'load',generation:s.generation+1});assert.deepEqual(r(s,{type:'read',generation:s.generation-1,data:detail}),s);assert.deepEqual(r(s,{type:'read',generation:s.generation,data:{...candidates,person:{...common.person,userId:id(13)}}}),s);s=r(s,{type:'assignment',assignment:{...assignment,assignmentId:id(41)}});assert.deepEqual(r(s,{type:'read',generation:s.generation-1,data:candidates}),s);});
test('frozen_exact_retry_preserves_witnesses_and_key',async()=>{let {r,s}=await ready();s=r(s,{type:'begin',key:'original-key'});const attempt=s.attempt;assert.ok(attempt);s=r(s,{type:'uncertain',message:'Response lost'});for(const e of [{type:'person',superintendentId:id(13)},{type:'replacement',replacement:{...replacement,replacementAssignmentId:id(53)}},{type:'assignment',assignment},{type:'confirm',confirmed:false},{type:'cancel'},{type:'reload'},{type:'load',generation:99}] as const)assert.deepEqual(r(s,e),s);s=r(s,{type:'retry'});assert.deepEqual(s.attempt,attempt);assert.equal(s.attempt?.input.replacementAssignmentId,id(51));assert.equal(s.pending,true);assert.deepEqual(r(s,{type:'begin',key:'second'}),s);});
test('missing eligibility reporting witnesses archived and unsupported never confirm',async()=>{const {v,s}=await ready();for(const state of [{...s,assignment:{...assignment,canUnlink:false,reportingCount:1}},{...s,replacements:null},{...s,replacement:{...replacement,replacementGrantId:id(55)}},{...s,detail:{...detail,project:{status:'ARCHIVED' as const,crewBuild:'FULL' as const}}},{...s,confirmed:false},{...s,loading:true}])assert.equal(v.canConfirmSuperintendentAreaUnlink(state),false);});
test('inactive_retired_chief_guidance is retained as evidence',async()=>{let {r,s}=await ready();const data:SuperintendentAreaReadResult={...common,mode:'superintendent-area-reporting',reporting:{data:[{linkId:id(80),partyChiefId:id(13),name:'Former Chief',email:'former@example.test',role:'VIEWER',active:false,areaId:id(22),areaName:'Retired descendant',retired:true,canUseStaffing:false,refusalReason:'Requires a separate approved cleanup contract'}],total:1,limit:10,offset:0}};s=r(s,{type:'read',generation:s.generation,data});assert.deepEqual(s.reporting,data);});
test('uncertain network/server failure freezes; definitive refusal unlocks',async()=>{const {v,r,s}=await ready();for(const e of [new Error('network'),new ApiClientError('INTERNAL','Failed',500)])assert.equal(v.superintendentAreaFailure(e).type,'uncertain');const failed=r(r(s,{type:'begin',key:'k'}),v.superintendentAreaFailure(new ApiClientError('FORBIDDEN','Denied',403)));assert.equal(failed.pending,false);assert.equal(failed.uncertain,false);assert.equal(failed.attempt,null);});

test('read409_is_generation_safe_and_latches_until_reload',async()=>{const v=await view();assert.equal(typeof v.superintendentAreaReadFailure,'function','Generation-safe read conflict handling is missing');let {r,s}=await ready();const e=v.superintendentAreaReadFailure(new ApiClientError('CONFLICT','Unsupported Area',409),s.generation);assert.equal(e.type,'stale');assert.deepEqual(r(s,{...e,generation:s.generation-1}),s);s=r(s,e);assert.equal(s.stale,true);assert.equal(r(s,{type:'cancel'}).stale,true);assert.equal(r(s,{type:'reload'}).stale,false);assert.equal(v.superintendentAreaReadFailure(new Error('read transport failed'),1).type,'readFailure');});
