// Opt-in loopback acceptance in a newly owned, fully migrated schema.
import assert from 'node:assert/strict';
import {randomUUID, createHash} from 'node:crypto';
import {readFile, readdir} from 'node:fs/promises';
import {Pool, type PoolClient} from 'pg';
import bcrypt from 'bcrypt';
import {NextRequest} from 'next/server';
import {getPool} from '../../src/lib/db';
import {signToken} from '../../src/lib/auth';
import {LoginRateLimitRepository} from '../../src/modules/identity/infrastructure/login-rate-limit.repository';
import {DEFAULT_LOGIN_RATE_LIMIT_POLICY} from '../../src/modules/identity/application/login-rate-limit';
import {pruneExpiredAuthSecurityRecords} from '../../src/modules/identity/infrastructure/password-reset-email-outbox';
import {handlePostLogin} from '../../src/app/api/auth/login/handler';
import {GET as appearance, PUT as saveAppearance} from '../../src/app/api/account/appearance/route';
import {GET as preview, POST as recommission} from '../../src/app/api/projects/[projectId]/recommission/route';
import {POST as activate} from '../../src/app/api/projects/[projectId]/activate/route';
import {POST as createTicket} from '../../src/app/api/tickets/route';
import {handlePostProject} from '../../src/app/api/projects/post-handler';
import type {UUID} from '../../src/shared/types';

async function main() {
  const url = new URL(process.env.DATABASE_URL ?? '');
  assert.equal(process.env.SWR_TEAM_POSTGRES, '1');
  assert.equal(url.hostname, '127.0.0.1'); assert.equal(url.port, '15489');
  assert.equal(url.pathname, '/swr_team_isolated');
  const schema = 'alpha1_' + randomUUID().replaceAll('-', '');
  assert.match(schema, /^alpha1_[a-f0-9]{32}$/);
  const setup = new Pool({connectionString:url.href}), db = await setup.connect();
  const app = getPool(), oldQuery = app.query, oldConnect = app.connect, oldSecret = process.env.JWT_SECRET;
  let scoped:Pool|undefined, created=false, failAudit=false, checks=0;
  process.env.JWT_SECRET = 'alpha1-disposable-acceptance-only-long-secret';
  const tenant=randomUUID() as UUID, otherTenant=randomUUID() as UUID;
  const company=randomUUID(), otherCompany=randomUUID(), project=randomUUID(), foreignProject=randomUUID();
  const central=randomUUID() as UUID, replacement=randomUUID() as UUID, ordinary=randomUUID() as UUID, outsider=randomUUID() as UUID;
  const email=central+'@example.invalid', password='Synthetic acceptance password only';
  const check = (name:string) => {checks++;console.log('PASS '+name);};
  const fingerprint = async(client:PoolClient) => (await client.query("SELECT count(*)::text AS n,md5(string_agg(id::text||':'||status||':'||row_version::text,',' ORDER BY id)) AS hash FROM public.tickets")).rows[0];
  const publicBefore=await fingerprint(db);
  try {
    await db.query('BEGIN'); await db.query(`CREATE SCHEMA "${schema}"`);
    await db.query(`SET LOCAL search_path TO "${schema}",public`);
    for(const file of (await readdir('db/migrations')).filter(f=>f.endsWith('.sql')).sort()) await db.query(await readFile('db/migrations/'+file,'utf8'));
    await db.query('COMMIT'); created=true;
    scoped=new Pool({connectionString:url.href,options:'-c search_path='+schema+',public',max:6});
    app.query=scoped.query.bind(scoped) as typeof app.query;
    const pg=scoped;
    app.connect=(async()=>{
      const client=await pg.connect(), query=client.query.bind(client);
      return {query:async(sql:string, values?:unknown[])=>{
        if(failAudit && sql.includes('INSERT INTO administrative_events')) throw new Error('Synthetic audit failure');
        return query(sql,values);
      },release:()=>client.release()};
    }) as typeof app.connect;
    await pg.query("INSERT INTO tenants(id,name) VALUES($1,'Alpha1'),($2,'Foreign')",[tenant,otherTenant]);
    await pg.query("INSERT INTO companies(id,tenant_id,name,type) VALUES($1,$2,'GC','GC'),($3,$4,'Foreign GC','GC')",[company,tenant,otherCompany,otherTenant]);
    await pg.query("INSERT INTO projects(id,tenant_id,name,status,crew_build,archived_at) VALUES($1,$2,'Archived fixture','ARCHIVED','SLIM',NOW()),($3,$4,'Foreign fixture','ARCHIVED','SLIM',NOW())",[project,tenant,foreignProject,otherTenant]);
    for(const [u,t,c] of [[central,tenant,company],[replacement,tenant,company],[ordinary,tenant,company],[outsider,otherTenant,otherCompany]]) await pg.query("INSERT INTO users(id,tenant_id,company_id,name,email,password_hash) VALUES($1,$2,$3,'Synthetic user',$4,$5)",[u,t,c,u+'@example.invalid',await bcrypt.hash(password,12)]);
    await pg.query("INSERT INTO tenant_memberships(tenant_id,user_id,role) VALUES($1,$2,'TENANT_ADMIN'),($3,$4,'TENANT_ADMIN')",[tenant,central,otherTenant,outsider]);
    await pg.query("INSERT INTO project_memberships(project_id,user_id,role) VALUES($1,$2,'SURVEY_MANAGER'),($1,$3,'REQUESTER'),($1,$4,'REQUESTER')",[project,central,replacement,ordinary]);
    await pg.query('INSERT INTO project_companies(tenant_id,project_id,company_id,associated_by) VALUES($1,$2,$3,$4)',[tenant,project,company,central]);
    const ticket=randomUUID(), event=randomUUID();
    await pg.query("INSERT INTO tickets(id,tenant_id,project_id,company_id,requester_id,workflow_variant,status,craft,description) VALUES($1,$2,$3,$4,$5,'STANDARD_APPROVAL','DRAFT','Survey','Retained history')",[ticket,tenant,project,company,ordinary]);
    await pg.query("INSERT INTO ticket_events(id,ticket_id,tenant_id,actor_id,event_type,payload) VALUES($1,$2,$3,$4,'ticket.created','{}')",[event,ticket,tenant,ordinary]);
    const history=async()=>createHash('sha256').update(JSON.stringify((await pg.query('SELECT to_jsonb(t) AS row FROM tickets t ORDER BY id')).rows.concat((await pg.query('SELECT to_jsonb(e) AS row FROM ticket_events e ORDER BY id')).rows))).digest('hex');
    const historyBefore=await history();
    const repo=new LoginRateLimitRepository();
    for(let n=0;n<40;n++) for(const t of [tenant,randomUUID() as UUID]) await repo.recordFailure(pg,{tenantId:t,email:randomUUID()+'@example.invalid'},DEFAULT_LOGIN_RATE_LIMIT_POLICY);
    assert.equal((await pg.query('SELECT count(*)::int AS n FROM auth_login_rate_limits')).rows[0].n,0);check('unknown_accounts_cannot_grow_durable_login_keys');
    await repo.recordFailure(pg,{tenantId:tenant.toUpperCase() as UUID,email},DEFAULT_LOGIN_RATE_LIMIT_POLICY);
    assert.equal((await pg.query('SELECT tenant_id FROM auth_login_rate_limits')).rows[0].tenant_id,tenant);
    await repo.clearFailures(pg,{tenantId:tenant,email});check('uuid_case_aliases_use_one_canonical_account_bucket');
    const login=(t:UUID,e:string,p:string)=>handlePostLogin(new NextRequest('http://localhost/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tenantId:t,email:e,password:p})}));
    assert.equal((await login(tenant,'unknown@example.invalid','wrong')).status,401);
    assert.equal((await login(randomUUID() as UUID,email,'wrong')).status,401);check('unknown_login_generic_credential_failure');
    for(let n=0;n<5;n++) assert.equal((await login(tenant,email,'wrong')).status,n===4?429:401);
    assert.equal((await login(tenant,email,password)).status,429);check('known_account_five_failures_preserve_lockout');
    await pg.query("UPDATE auth_login_rate_limits SET updated_at=NOW()-interval '2 days' WHERE tenant_id=$1",[tenant]);
    await pruneExpiredAuthSecurityRecords(pg);assert.equal((await pg.query('SELECT count(*)::int AS n FROM auth_login_rate_limits')).rows[0].n,1);
    await pg.query("UPDATE auth_login_rate_limits SET blocked_until=NOW()-interval '1 second'");
    await pruneExpiredAuthSecurityRecords(pg);assert.equal((await pg.query('SELECT count(*)::int AS n FROM auth_login_rate_limits')).rows[0].n,0);check('pruning_preserves_active_blocks_and_expires_stale_buckets');
    const req=(path:string,body?:unknown,user:UUID=central,t:UUID=tenant,key=randomUUID(),sv=1,method=body===undefined?'GET':'POST')=>new NextRequest('http://localhost'+path,{method,headers:{cookie:'swr_session='+signToken(user,t,sv),'content-type':'application/json','idempotency-key':key},...(body===undefined?{}:{body:JSON.stringify(body)})});
    const expect=async(response:Response,status=200)=>{assert.equal(response.status,status,await response.clone().text());return response.json();};
    const appearancePath='/api/account/appearance';
    const creation={name:'Alpha1 exact creation',crewBuild:'SLIM'}, creationKey=randomUUID();
    const [createdA,createdB]=await Promise.all([handlePostProject(req('/api/projects',creation,central,tenant,creationKey)),handlePostProject(req('/api/projects',creation,central,tenant,creationKey))]);
    const createdResponse=await expect(createdA,201);assert.deepEqual(await expect(createdB,201),createdResponse);
    assert.equal((await pg.query("SELECT count(*)::int AS n FROM projects WHERE name=$1",[creation.name])).rows[0].n,1);
    assert.equal((await pg.query("SELECT count(*)::int AS n FROM administrative_events WHERE event_type='project.created'")).rows[0].n,1);
    await expect(await handlePostProject(req('/api/projects',{...creation,name:'Changed'},central,tenant,creationKey)),409);
    await expect(await handlePostProject(req('/api/projects',creation,ordinary,tenant,creationKey)),403);check('project_creation_concurrent_exact_replay_and_payload_conflict');
    failAudit=true;await expect(await handlePostProject(req('/api/projects',{...creation,name:'Must roll back'})),500);failAudit=false;
    assert.equal((await pg.query("SELECT count(*)::int AS n FROM projects WHERE name='Must roll back'")).rows[0].n,0);check('project_creation_audit_failure_rolls_back');
    await pg.query('DELETE FROM tenant_memberships WHERE tenant_id=$1 AND user_id=$2',[tenant,central]);
    await expect(await handlePostProject(req('/api/projects',creation,central,tenant,creationKey)),403);
    await pg.query("INSERT INTO tenant_memberships(tenant_id,user_id,role) VALUES($1,$2,'TENANT_ADMIN')",[tenant,central]);check('project_creation_current_authority_precedes_replay');
    const personal={scope:'PERSONAL',mode:'DARK'}, personalKey=randomUUID();
    await expect(await saveAppearance(req(appearancePath,personal,ordinary,tenant,personalKey,1,'PUT')));
    await expect(await saveAppearance(req(appearancePath,personal,ordinary,tenant,personalKey,1,'PUT')));
    assert.equal((await pg.query("SELECT count(*)::int AS n FROM administrative_events WHERE event_type='account.appearance_changed'")).rows[0].n,1);check('personal_appearance_exact_replay_one_event');
    await expect(await saveAppearance(req(appearancePath,{...personal,mode:'LIGHT'},ordinary,tenant,personalKey,1,'PUT')),409);
    const colors={scope:'TENANT',primary:'#123456',accent:'#ff9900',version:0}, colorKey=randomUUID();
    await expect(await saveAppearance(req(appearancePath,colors,ordinary,tenant,randomUUID(),1,'PUT')),403);
    await expect(await saveAppearance(req(appearancePath,colors,central,tenant,colorKey,1,'PUT')));
    await expect(await saveAppearance(req(appearancePath,colors,central,tenant,colorKey,1,'PUT')));
    await expect(await saveAppearance(req(appearancePath,colors,central,tenant,randomUUID(),1,'PUT')),409);
    const foreign=await expect(await appearance(req(appearancePath,undefined,outsider,otherTenant)));assert.equal(foreign.branding.version,0);check('branding_authority_tenant_isolation_stale_version_and_replay');
    await pg.query('DELETE FROM tenant_memberships WHERE tenant_id=$1 AND user_id=$2',[tenant,central]);
    await expect(await saveAppearance(req(appearancePath,colors,central,tenant,colorKey,1,'PUT')),403);
    await pg.query("INSERT INTO tenant_memberships(tenant_id,user_id,role) VALUES($1,$2,'TENANT_ADMIN')",[tenant,central]);check('branding_current_authority_precedes_saved_replay');
    const beforeAppearance=(await pg.query('SELECT mode FROM user_appearance WHERE user_id=$1',[ordinary])).rows;
    failAudit=true;await expect(await saveAppearance(req(appearancePath,{scope:'PERSONAL',mode:'LIGHT'},ordinary,tenant,randomUUID(),1,'PUT')),500);failAudit=false;
    assert.deepEqual((await pg.query('SELECT mode FROM user_appearance WHERE user_id=$1',[ordinary])).rows,beforeAppearance);check('appearance_audit_failure_rolls_back');
    const path='/api/projects/'+project+'/recommission', context={params:Promise.resolve({projectId:project})};
    await expect(await preview(req(path,undefined,ordinary),context),403);
    await expect(await preview(req(path,undefined,outsider,otherTenant),context),404);
    const p=(await expect(await preview(req(path),context))).preview;
    const begin={action:'BEGIN',snapshot:p.snapshot,replacementAdminId:replacement,reason:'Confirmed disposable operating period',confirmed:true};
    failAudit=true;await expect(await recommission(req(path,begin),context),500);failAudit=false;
    assert.equal((await pg.query('SELECT status FROM projects WHERE id=$1',[project])).rows[0].status,'ARCHIVED');
    assert.equal((await pg.query('SELECT count(*)::int AS n FROM project_recommissioning')).rows[0].n,0);check('recommission_preparation_audit_failure_rolls_back');
    const beginKey=randomUUID();const [first,second]=await Promise.all([recommission(req(path,begin,central,tenant,beginKey),context),recommission(req(path,begin,central,tenant,beginKey),context)]);
    const a=await expect(first),b=await expect(second);assert.equal(a.periodId,b.periodId);
    assert.equal((await pg.query('SELECT count(*)::int AS n FROM project_recommissioning')).rows[0].n,1);check('separate_connections_same_key_one_preparation');
    assert.equal((await pg.query('SELECT session_version FROM users WHERE id=$1',[replacement])).rows[0].session_version,2);
    await expect(await appearance(req(appearancePath,undefined,replacement)),401);check('new_admin_grant_invalidates_prior_session');
    await expect(await activate(req('/api/projects/'+project+'/activate',{}),context),409);
    await expect(await createTicket(req('/api/tickets',{projectId:project,aorNodeId:randomUUID(),ticketType:'TOPO',fieldContact:'Synthetic',description:'Should stay blocked',requestedDate:'2026-10-10'})),409);check('ordinary_activation_and_workflow_blocked_during_preparation');
    let ready=(await expect(await preview(req(path),context))).preview;
    const open=()=>({action:'OPEN',snapshot:ready.snapshot,reason:'Readiness verified',confirmed:true,retainedMembers:ready.members.map((r:{id:string})=>r.id),retainedCompanies:ready.companies.map((r:{id:string})=>r.id),continuedWork:ready.work.map((r:{id:string})=>r.id)});
    await expect(await recommission(req(path,open()),context),409);check('missing_area_readiness_blocks_opening');
    const level=randomUUID(),area=randomUUID();await pg.query("INSERT INTO aor_levels(id,tenant_id,project_id,depth,label) VALUES($1,$2,$3,0,'Area')",[level,tenant,project]);
    await pg.query("INSERT INTO aor_nodes(id,tenant_id,project_id,level_id,name,code) VALUES($1,$2,$3,$4,'Synthetic Area','A')",[area,tenant,project,level]);
    await expect(await recommission(req(path,open()),context),409);check('stale_recommission_snapshot_requires_reload');
    ready=(await expect(await preview(req(path),context))).preview;assert.deepEqual(ready.blockers,[]);
    await expect(await recommission(req(path,{...open(),continuedWork:[]}),context),409);check('exact_retained_work_review_required');
    const openKey=randomUUID(),opening=open();await expect(await recommission(req(path,opening,central,tenant,openKey),context));
    await expect(await recommission(req(path,opening,central,tenant,openKey),context));
    assert.equal((await pg.query('SELECT status FROM projects WHERE id=$1',[project])).rows[0].status,'ACTIVE');
    assert.equal((await pg.query("SELECT count(*)::int AS n FROM administrative_events WHERE event_type='project.recommissioned'")).rows[0].n,1);
    assert.equal(await history(),historyBefore);check('opening_replay_retains_all_ticket_and_event_bytes');
    await pg.query('DELETE FROM tenant_memberships WHERE tenant_id=$1 AND user_id=$2',[tenant,central]);
    await expect(await recommission(req(path,opening,central,tenant,openKey),context),403);check('recommission_current_authority_precedes_replay');
    const invalid=async(sql:string,values:unknown[],code:string)=>{const client=await pg.connect();try{await client.query('BEGIN');await assert.rejects(()=>client.query(sql,values),(e:unknown)=>{assert.equal((e as {code:string}).code,code);return true;});}finally{await client.query('ROLLBACK');client.release();}};
    for(const sql of ['UPDATE ticket_events SET payload=\'{}\' WHERE id=$1','DELETE FROM ticket_events WHERE id=$1'])await invalid(sql,[event],'55000');
    await invalid('TRUNCATE ticket_events',[],'55000');
    await invalid("INSERT INTO ticket_events(ticket_id,tenant_id,actor_id,event_type) VALUES($1,$2,$3,'ticket.created')",[ticket,otherTenant,outsider],'23503');
    const legacy=await pg.connect();
    try {
      await legacy.query('BEGIN');
      await legacy.query('ALTER TABLE ticket_events DROP CONSTRAINT ticket_events_tenant_ticket_fk');
      await legacy.query("INSERT INTO ticket_events(ticket_id,tenant_id,actor_id,event_type) VALUES($1,$2,$3,'ticket.created')",[ticket,otherTenant,outsider]);
      const migration=await readFile('db/migrations/034_ticket_event_integrity.sql','utf8');
      await assert.rejects(()=>legacy.query(migration),(error:unknown)=>{assert.equal((error as {code:string}).code,'P0001');return true;});
    } finally {await legacy.query('ROLLBACK');legacy.release();}
    assert.equal(await history(),historyBefore);check('migration_preflight_refuses_inconsistent_legacy_history_without_repair');
    await pg.query(await readFile('db/migrations/034_ticket_event_integrity.sql','utf8'));
    assert.equal(await history(),historyBefore);check('event_history_immutable_tenant_bound_and_migration_repeatable');
    await invalid('DELETE FROM project_recommissioning',[],'P0001');
    await invalid("UPDATE project_recommissioning SET reason='rewrite'",[],'P0001');check('recommission_period_evidence_immutable');
    assert.deepEqual(await fingerprint(db),publicBefore);check('retained_public_ticket_witness_unchanged');
    console.log(`Alpha1 PostgreSQL acceptance passed: ${checks}`);
  } finally {
    failAudit=false;app.query=oldQuery;app.connect=oldConnect;
    if(oldSecret===undefined)delete process.env.JWT_SECRET;else process.env.JWT_SECRET=oldSecret;
    if(scoped)await scoped.end();
    await db.query('ROLLBACK');
    if(created)await db.query(`DROP SCHEMA "${schema}" CASCADE`);
    db.release();await setup.end();
  }
}
main().catch(error=>{console.error(error);process.exitCode=1;});
