import {Pool} from 'pg';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,readdir,writeFile} from 'node:fs/promises';
import {NextRequest} from 'next/server';
import {getPool} from '../../src/lib/db';
import {signToken} from '../../src/lib/auth';
import {handlePostSurveyTeam as TEAM} from '../../src/app/api/projects/[projectId]/survey/teams/handler';
import type {UUID} from '../../src/shared/types';
async function main(){
 const dir='.local/alpha-closure267',url=new URL(process.env.DATABASE_URL??'');assert.equal(process.env.SWR_FINALIZATION_TEST,'267');assert.equal(process.env.SWR_TEAM_POSTGRES,'1');assert.equal(url.hostname,'127.0.0.1');assert.equal(url.port,'15500');assert.equal(url.pathname,'/swr_team_isolated');assert.equal(await readFile(dir+'/fixture.json').then(()=>true,e=>{if(e.code==='ENOENT')return false;throw e;}),false);const own=JSON.parse(await readFile('.local/alpha-acceptance197/ownership.json','utf8'));assert.equal(own.owner,'Alpha acceptance197');
 const schema='alpha_administration267_'+randomUUID().replaceAll('-',''),bootstrap=new Pool({connectionString:url.href}),db=await bootstrap.connect();try{await db.query('CREATE SCHEMA "'+schema+'"');await db.query('SET search_path TO "'+schema+'",public');for(const name of(await readdir('db/migrations')).filter(x=>x.endsWith('.sql')).sort()){await db.query(await readFile('db/migrations/'+name,'utf8'));assert.equal((await db.query('SELECT current_schema() name')).rows[0].name,schema);}}finally{db.release();await bootstrap.end();}url.searchParams.set('options','-c search_path='+schema+',public');process.env.DATABASE_URL=url.href;const pool=getPool(),checks:string[]=[];
 const tenant=randomUUID(),foreignTenant=randomUUID(),project=randomUUID(),otherProject=randomUUID(),foreignProject=randomUUID(),company=randomUUID(),scCompany=randomUUID(),foreignCompany=randomUUID(),level=randomUUID(),area=randomUUID(),area2=randomUUID(),area3=randomUUID();
 const ownerRepCompany=randomUUID();const people:Record<string,string>={},tokens:Record<string,string>={},roles:Record<string,string>={ownerRepManager:'SURVEY_MANAGER',ownerRepCoverage:'SURVEY_SUPERINTENDENT',subIncoming:'SURVEY_SUPERINTENDENT',projectAdmin:'VIEWER',offboard:'REQUESTER',offboard2:'REQUESTER',handoverIncoming:'SURVEY_SUPERINTENDENT',handoverCoverage:'SURVEY_SUPERINTENDENT',handoverChief:'PARTY_CHIEF',subRequest:'REQUESTER',subRequest2:'REQUESTER',adminGrant1:'VIEWER',adminGrant2:'VIEWER',secondChief:'PARTY_CHIEF',freeInstrument:'INSTRUMENT_MAN',manager:'SURVEY_MANAGER',admin:'VIEWER',superintendent:'SURVEY_SUPERINTENDENT',destinationLead:'SURVEY_SUPERINTENDENT',chief:'PARTY_CHIEF',instrument:'INSTRUMENT_MAN',instrument2:'INSTRUMENT_MAN',destinationChief:'PARTY_CHIEF',requester:'REQUESTER',viewer:'VIEWER',subcontractor:'SURVEY_MANAGER',foreignManager:'SURVEY_MANAGER'};
 for(const who of Object.keys(roles))people[who]=randomUUID();
 await pool.query("INSERT INTO tenants(id,name) VALUES($1,'Owned membership267'),($2,'Owned foreign membership267')",[tenant,foreignTenant]);
 await pool.query("INSERT INTO companies(id,tenant_id,name,type) VALUES($1,$2,'Owned GC','GC'),($3,$2,'Owned subcontractor','SUBCONTRACTOR'),($4,$5,'Owned foreign GC','GC')",[company,tenant,scCompany,foreignCompany,foreignTenant]);
 for(const [id,t] of [[project,tenant],[otherProject,tenant],[foreignProject,foreignTenant]])await pool.query("INSERT INTO projects(id,tenant_id,name,status,crew_build) VALUES($1,$2,'Owned protected creation controls','ACTIVE','FULL')",[id,t]);
 await pool.query("INSERT INTO companies(id,tenant_id,name,type) VALUES($1,$2,'Owned Owner Representative','OWNER_REP')",[ownerRepCompany,tenant]);
 for(const [who,id] of Object.entries(people)){const foreign=who==='foreignManager',t=foreign?foreignTenant:tenant,p=foreign?foreignProject:project;await pool.query("INSERT INTO users(id,tenant_id,company_id,email,name,password_hash) VALUES($1,$2,$3,$4,$5,'no-login-fixture')",[id,t,foreign?foreignCompany:['subcontractor','subRequest','subRequest2','subIncoming'].includes(who)?scCompany:who.startsWith('ownerRep')?ownerRepCompany:company,id+'@membership267.invalid','Membership '+who]);await pool.query('INSERT INTO project_memberships(project_id,user_id,role) VALUES($1,$2,$3)',[p,id,roles[who]]);tokens[who]=signToken(id as UUID,t as UUID);}
 await pool.query("INSERT INTO tenant_memberships(tenant_id,user_id,role) VALUES($1,$2,'TENANT_ADMIN')",[tenant,people.admin!]);await pool.query("INSERT INTO project_admin_grants(tenant_id,project_id,user_id,origin,granted_by) VALUES($1,$2,$3,'EXPLICIT',$4)",[tenant,project,people.admin!,people.manager!]);
 await pool.query("INSERT INTO aor_levels(id,tenant_id,project_id,depth,label) VALUES($1,$2,$3,0,'Area')",[level,tenant,project]);for(const [id,name]of[[area,'Source Area'],[area2,'Transfer Area'],[area3,'Retained Coverage']])await pool.query('INSERT INTO aor_nodes(id,tenant_id,project_id,level_id,name,code) VALUES($1,$2,$3,$4,$5,$6)',[id,tenant,project,level,name,id]);
 for(const [who,areas]of[['superintendent',[area,area2]],['destinationLead',[area,area2]],['secondChief',[area]],['chief',[area]],['destinationChief',[area2]]] as const)for(const a of areas)await pool.query('INSERT INTO aor_assignments(tenant_id,project_id,user_id,aor_node_id) VALUES($1,$2,$3,$4)',[tenant,project,people[who],a]);
 await pool.query('INSERT INTO survey_reporting_links(tenant_id,project_id,superintendent_id,party_chief_id,aor_node_id,assigned_by) VALUES($1,$2,$3,$4,$5,$6)',[tenant,project,people.superintendent!,people.chief!,area,people.manager!]);for(const who of ['instrument','instrument2'])await pool.query('INSERT INTO crew_rosters(tenant_id,project_id,party_chief_id,instrument_man_id) VALUES($1,$2,$3,$4)',[tenant,project,people.chief!,people[who]]);
 await pool.query("INSERT INTO project_admin_grants(tenant_id,project_id,user_id,origin,granted_by) VALUES($1,$2,$3,'EXPLICIT',$4),($1,$2,$5,'EXPLICIT',$4),($1,$2,$6,'EXPLICIT',$4)",[tenant,project,people.projectAdmin!,people.admin!,people.adminGrant1!,people.adminGrant2!]);
 for(const c of [company,scCompany,ownerRepCompany])await pool.query('INSERT INTO project_companies(tenant_id,project_id,company_id,associated_by) VALUES($1,$2,$3,$4)',[tenant,project,c,people.admin!]);
 await pool.query("INSERT INTO project_memberships(project_id,user_id,role) VALUES($1,$2,'REQUESTER')",[otherProject,people.offboard!]);
 await pool.query('INSERT INTO aor_assignments(tenant_id,project_id,user_id,aor_node_id) VALUES($1,$2,$3,$4)',[tenant,project,people.handoverIncoming!,area]);
 await pool.query('INSERT INTO aor_assignments(tenant_id,project_id,user_id,aor_node_id) VALUES($1,$2,$3,$4)',[tenant,project,people.handoverChief!,area]);
 await pool.query('INSERT INTO survey_reporting_links(tenant_id,project_id,superintendent_id,party_chief_id,aor_node_id,assigned_by) VALUES($1,$2,$3,$4,$5,$6)',[tenant,project,people.handoverIncoming!,people.handoverChief!,area,people.manager!]);
 const context=(id=project)=>({params:Promise.resolve({projectId:id})});
 async function result(response:Promise<Response>,status:number,label:string){const r=await response;assert.equal(r.status,status,label);checks.push(label);return r.json();}
 async function team(name:string,lead:string,ids:string[],areas:string[],primary:string){const body={teamId:null,expectedVersion:null,name,areaId:primary,areaIds:areas,leadUserId:lead,memberIds:ids};const req=new NextRequest('http://localhost/api/projects/'+project+'/survey/teams',{method:'POST',headers:{cookie:'swr_session='+tokens.manager,'content-type':'application/json','Idempotency-Key':randomUUID()},body:JSON.stringify(body)});return(await result(TEAM(req,context()),201,'Current Manager creates '+name)).teamId as string;}
 const source=await team('Source multi-Area team',people.superintendent!,[people.superintendent!,people.chief!,people.instrument!,people.instrument2!,people.secondChief!,people.freeInstrument! ],[area,area2],area),destination=await team('Destination complete coverage',people.destinationLead!,[people.destinationLead!,people.destinationChief!],[area2,area3],area3);
 await pool.query('INSERT INTO survey_reporting_links(tenant_id,project_id,superintendent_id,party_chief_id,aor_node_id,assigned_by) VALUES($1,$2,$3,$4,$5,$6)',[tenant,project,people.superintendent!,people.secondChief!,area,people.manager!]);
 await writeFile(dir+'/fixture.json',JSON.stringify({schema,origin:"http://127.0.0.1:3307",tenant,foreignTenant,project,otherProject,foreignProject,company,scCompany,people,tokens,area,area2,area3,source,destination}));
 const runtime=new URL(url.href);runtime.hostname='host.docker.internal';await writeFile(dir+'/host-runtime.env','DATABASE_URL='+url.href+'\nJWT_SECRET='+process.env.JWT_SECRET+'\n');await writeFile(dir+'/runtime.env','DATABASE_URL='+runtime.href+'\nJWT_SECRET='+process.env.JWT_SECRET+'\nSWR_ATTACHMENT_ROOT=/tmp/admin267-files\n');await writeFile(dir+'/environment.json',JSON.stringify({DATABASE_URL:url.href,JWT_SECRET:process.env.JWT_SECRET}));
 console.log(JSON.stringify({checks:checks.length,cases:checks}));await pool.end();
}
main().catch(error=>{console.error(error);process.exitCode=1;});
