import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,writeFile} from 'node:fs/promises';
import {NextRequest} from 'next/server';
import {getPool} from '../../src/lib/db';
import {signToken} from '../../src/lib/auth';
import {handlePostSurveyTeam} from '../../src/app/api/projects/[projectId]/survey/teams/handler';
import type {UUID} from '../../src/shared/types';
async function main(){
 const evidenceDir='.local/alpha-closure281';assert.equal(process.env.SWR_ALPHA_EVIDENCE,'281');assert.match(process.env.SWR_ALPHA_SCHEMA??'',/^alpha_roles281_[a-f0-9]{32}$/);await readFile(evidenceDir+'/host-runtime.env','utf8');assert.equal(await readFile(evidenceDir+'/role-fixture.json').then(()=>true,e=>{if(e.code==='ENOENT')return false;throw e;}),false,'Use a new owned schema; never overwrite completed role evidence.');
 const url=new URL(process.env.DATABASE_URL??'');assert.equal(process.env.SWR_ALPHA_ACCEPTANCE,'281');assert.equal(url.hostname,'127.0.0.1');assert.equal(url.port,'15500');assert.equal(url.pathname,'/swr_team_isolated');
 const owned=JSON.parse(await readFile('.local/alpha-acceptance197/ownership.json','utf8'));assert.equal(owned.owner,'Alpha acceptance197');assert.equal(owned.hostPort,15500);assert.match(owned.container,/^swr-alpha-acceptance197-db-[a-f0-9]{8}$/);
 const pool=getPool(),tenant=randomUUID(),foreignTenant=randomUUID(),project=randomUUID(),setupProject=randomUUID(),archivedProject=randomUUID(),foreignProject=randomUUID(),company=randomUUID(),scCompany=randomUUID(),foreignCompany=randomUUID(),level=randomUUID(),area=randomUUID(),area2=randomUUID(),area3=randomUUID(),department=randomUUID(),otherDepartment=randomUUID();
 const roles:Record<string,string>={manager:'SURVEY_MANAGER',admin:'VIEWER',superintendent:'SURVEY_SUPERINTENDENT',chief:'PARTY_CHIEF',instrument:'INSTRUMENT_MAN',requester:'REQUESTER',viewer:'VIEWER',otherChief:'PARTY_CHIEF',otherInstrument:'INSTRUMENT_MAN',otherRequester:'REQUESTER',subRequester:'REQUESTER',subRequester2:'REQUESTER',cadTech:'CAD_TECHNICIAN',cadLead:'CAD_LEAD',departmentManager:'DEPARTMENT_MANAGER',departmentLead:'DEPARTMENT_LEAD',areaViewer:'AREA_VIEWER',coordinator:'SUBCONTRACTS_COORDINATOR',legacyAdmin:'PROJECT_ADMIN',customRequester:'REQUESTER',customViewer:'VIEWER',managerAdmin:'SURVEY_MANAGER',requesterAdmin:'REQUESTER',ssAdmin:'SURVEY_SUPERINTENDENT',chiefAdmin:'PARTY_CHIEF',instrumentAdmin:'INSTRUMENT_MAN',tenantOnly:'VIEWER',projectOnly:'VIEWER',foreignManager:'SURVEY_MANAGER'};
 const people:Record<string,string>={},tokens:Record<string,string>={};for(const who of Object.keys(roles))people[who]=randomUUID();
 await pool.query("INSERT INTO tenants(id,name) VALUES($1,'Owned Alpha acceptance197'),($2,'Owned foreign Alpha acceptance197')",[tenant,foreignTenant]);
 await pool.query("INSERT INTO companies(id,tenant_id,name,type) VALUES($1,$2,'Owned GC','GC'),($3,$2,'Owned SC','SUBCONTRACTOR'),($4,$5,'Owned foreign GC','GC')",[company,tenant,scCompany,foreignCompany,foreignTenant]);
 for(const [p,t,status] of [[project,tenant,'ACTIVE'],[setupProject,tenant,'SETUP'],[archivedProject,tenant,'ARCHIVED'],[foreignProject,foreignTenant,'ACTIVE']])await pool.query("INSERT INTO projects(id,tenant_id,name,status,crew_build) VALUES($1,$2,$3,$4,'FULL')",[p,t,'Owned Alpha '+status,status]);
 for(const [who,id]of Object.entries(people)){
  const foreign=who==='foreignManager',t=foreign?foreignTenant:tenant,c=foreign?foreignCompany:who.startsWith('subRequester')?scCompany:company;
  await pool.query("INSERT INTO users(id,tenant_id,company_id,email,name,password_hash) VALUES($1,$2,$3,$4,$5,'no-login-fixture')",[id,t,c,id+'@alpha197.invalid','Acceptance '+who]);tokens[who]=signToken(id as UUID,t as UUID);
  if(who==='tenantOnly')continue;
  for(const p of foreign?[foreignProject]:[project,setupProject,archivedProject])await pool.query('INSERT INTO project_memberships(project_id,user_id,role) VALUES($1,$2,$3)',[p,id,roles[who]]);
 }
 for(const who of ['admin','tenantOnly'])await pool.query("INSERT INTO tenant_memberships(tenant_id,user_id,role) VALUES($1,$2,'TENANT_ADMIN')",[tenant,people[who]]);
 for(const who of ['admin','projectOnly','legacyAdmin','managerAdmin','requesterAdmin','ssAdmin','chiefAdmin','instrumentAdmin'])for(const p of [project,setupProject,archivedProject])await pool.query("INSERT INTO project_admin_grants(tenant_id,project_id,user_id,origin,granted_by) VALUES($1,$2,$3,'EXPLICIT',$4)",[tenant,p,people[who],people.admin]);
 for(const c of [company,scCompany])await pool.query('INSERT INTO project_companies(tenant_id,project_id,company_id,associated_by) VALUES($1,$2,$3,$4)',[tenant,project,c,people.admin]);
 await pool.query("INSERT INTO aor_levels(id,tenant_id,project_id,depth,label) VALUES($1,$2,$3,0,'Area')",[level,tenant,project]);for(const [a,name] of [[area,'Area A'],[area2,'Area B'],[area3,'Area C']])await pool.query('INSERT INTO aor_nodes(id,tenant_id,project_id,level_id,name,code) VALUES($1,$2,$3,$4,$5,$6)',[a,tenant,project,level,name,a]);
 for(const [who,areas] of [['superintendent',[area,area2]],['chief',[area]],['otherChief',[area2]],['areaViewer',[area]],['departmentLead',[area]],['ssAdmin',[area]]] as const)for(const a of areas)await pool.query('INSERT INTO aor_assignments(tenant_id,project_id,user_id,aor_node_id) VALUES($1,$2,$3,$4)',[tenant,project,people[who],a]);
 await pool.query('INSERT INTO survey_reporting_links(tenant_id,project_id,superintendent_id,party_chief_id,aor_node_id,assigned_by) VALUES($1,$2,$3,$4,$5,$6)',[tenant,project,people.superintendent,people.chief,area,people.manager]);await pool.query('INSERT INTO crew_rosters(tenant_id,project_id,party_chief_id,instrument_man_id) VALUES($1,$2,$3,$4),($1,$2,$5,$6)',[tenant,project,people.chief,people.instrument,people.otherChief,people.otherInstrument]);
 for(const [d,name] of [[department,'Department A'],[otherDepartment,'Department B']])await pool.query('INSERT INTO departments(id,tenant_id,project_id,name,manager_title,created_by) VALUES($1,$2,$3,$4,$5,$6)',[d,tenant,project,name,'Manager',people.admin]);
 for(const who of ['departmentManager','departmentLead'])await pool.query('INSERT INTO department_memberships(tenant_id,project_id,user_id,department_id,assigned_by) VALUES($1,$2,$3,$4,$5)',[tenant,project,people[who],department,people.admin]);
 for(const [who,base] of [['customRequester','REQUESTER'],['customViewer','VIEWER']] as const){const id=randomUUID();await pool.query('INSERT INTO tenant_custom_roles(id,tenant_id,name,base_role,created_by) VALUES($1,$2,$3,$4,$5)',[id,tenant,'Owned '+who,base,people.admin]);await pool.query('UPDATE project_memberships SET custom_role_id=$3 WHERE project_id=ANY($1::uuid[]) AND user_id=$2',[[project,setupProject,archivedProject],people[who],id]);}
 const response=await handlePostSurveyTeam(new NextRequest('http://localhost/api/projects/'+project+'/survey/teams',{method:'POST',headers:{cookie:'swr_session='+tokens.manager,'content-type':'application/json','Idempotency-Key':randomUUID()},body:JSON.stringify({teamId:null,expectedVersion:null,name:'Owned two-Area team',areaId:area,areaIds:[area,area2],leadUserId:people.superintendent,memberIds:[people.superintendent,people.chief,people.instrument]})}),{params:Promise.resolve({projectId:project})});assert.equal(response.status,201);const team=(await response.json()).teamId;
 const population:Array<Record<string,unknown>>=[],statuses=['SUBMITTED','APPROVED','ASSIGNED','IN_PROGRESS','DELAYED','RETURNED_FOR_CORRECTION','COMPLETED','SURVEY_CANCELED'],today=new Date().toISOString().slice(0,10);
 for(let i=0;i<24;i++){
  const id=randomUUID(),status=statuses[i%8]!,a=[area,area2,area3][i%3]!,d=i%2?department:otherDepartment,c=i%4===0?scCompany:company,r=i%4===0?people.subRequester!:i%5===0?people.customRequester!:people.requester!,pc=i%3===0?people.chief!:i%3===1?people.otherChief!:null,im=pc===people.chief?people.instrument!:pc===people.otherChief?people.otherInstrument!:null,date=new Date(today+'T00:00:00Z');date.setUTCDate(date.getUTCDate()+i%6-2);const needBy=date.toISOString().slice(0,10),first=new Date(Date.now()-5*86400000).toISOString(),completed=status==='COMPLETED'?new Date(Date.now()-86400000).toISOString():null;
  await pool.query("INSERT INTO tickets(id,tenant_id,project_id,company_id,requester_id,workflow_variant,status,craft,description,aor_node_id,department_id,ticket_type,requested_date,ticket_number,assigned_party_chief_id,assigned_instrument_man_id,field_contact,submitted_at,first_submitted_at,completed_at) VALUES($1,$2,$3,$4,$5,'STANDARD_APPROVAL',$6,'Survey',$7,$8,$9,'LAYOUT',$10,$11,$12,$13,'Owned contact',$14,$14,$15)",[id,tenant,project,c,r,status,'Owned population '+i,a,d,needBy,'ALPHA197-'+i,pc,im,first,completed]);population.push({id,area:a,department:d,company:c,requester:r,status,chief:pc,instrument:im,needBy,completedAt:completed,firstSubmittedAt:first});
 }
 const partial=randomUUID();await pool.query("INSERT INTO tickets(id,tenant_id,project_id,company_id,requester_id,workflow_variant,status,craft,description) VALUES($1,$2,$3,$4,$5,'STANDARD_APPROVAL','DRAFT','','Owned partial draft')",[partial,tenant,project,company,people.requester]);
 await writeFile(evidenceDir+'/role-fixture.json',JSON.stringify({schema:process.env.SWR_ALPHA_SCHEMA,origin:'http://127.0.0.1:3314',tenant,foreignTenant,project,setupProject,archivedProject,foreignProject,company,scCompany,people,tokens,roles,area,area2,area3,department,otherDepartment,team,population,partial,today}));console.log('Fresh owned Alpha role/state/population fixture created; no retained database used');await pool.end();
}
main().catch(error=>{console.error(error);process.exitCode=1;});
