import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {runLifecycleSchemaAcceptance} from './account-offboarding-postgres';
import {saveCustomRole,deleteCustomRole,readCustomRoles,resolveCustomRoleSelection} from '../../src/modules/tenancy/application/custom-roles';
import {assignTemplateRole} from '../../src/modules/tenancy/application/assign-template-role';
import {createProjectEmployee} from '../../src/modules/tenancy/application/create-project-employee';
import {executeIdempotentHttpMutation} from '../../src/lib/idempotency';
import type {UUID} from '../../src/shared/types';
runLifecycleSchemaAcceptance(async(db,f)=>{
 await db.query(await readFile('db/migrations/032_administrative_events.sql','utf8'));
 const auth={tenantId:f.tenant as UUID,userId:f.actor as UUID,sessionVersion:1},project=f.project as UUID;
 await db.query("INSERT INTO tenant_memberships(tenant_id,user_id,role) VALUES($1,$2,'TENANT_ADMIN')",[f.tenant,f.actor]);
 const company=(await db.query('SELECT company_id FROM users WHERE id=$1',[f.actor])).rows[0].company_id;
 await db.query('INSERT INTO project_companies(tenant_id,project_id,company_id,associated_by) VALUES($1,$2,$3,$4)',[f.tenant,project,company,f.actor]);
 let checks=0;async function refuses(fn:()=>Promise<unknown>,type:string){await db.query('SAVEPOINT negative_role');try{await assert.rejects(fn,{type});}finally{await db.query('ROLLBACK TO SAVEPOINT negative_role');}checks++;}
 const payload={name:'Construction Manager',baseRole:'REQUESTER'};
 const ledger={tenantId:auth.tenantId,actorId:auth.userId,endpoint:'POST /api/roles',idempotencyKey:randomUUID()};
 const create=()=>executeIdempotentHttpMutation(db,ledger,payload,async()=>({status:201,body:{role:await saveCustomRole(db,auth,payload)}}));
 const first=await create(),replay=await create();assert.deepEqual(first.body,replay.body);assert.equal(replay.replayed,true);checks++;
 const role=first.body.role;
 await refuses(()=>saveCustomRole(db,auth,{...payload,name:'construction-manager'}),'ConflictError');
 await refuses(()=>saveCustomRole(db,{...auth,userId:f.subject as UUID},payload),'ForbiddenError');
 await refuses(()=>readCustomRoles(db,{...auth,userId:f.subject as UUID},project),'ForbiddenError');
 await refuses(()=>resolveCustomRoleSelection(db,auth.tenantId,{role:'VIEWER',customRoleId:role.id,customRoleVersion:1}),'ConflictError');
 await refuses(()=>resolveCustomRoleSelection(db,randomUUID() as UUID,{role:'REQUESTER',customRoleId:role.id,customRoleVersion:1}),'NotFoundError');
 const employee=await createProjectEmployee(db,auth,project,{companyId:company,name:'Custom member',email:randomUUID()+'@example.test',password:'Synthetic-Role-2026!',role:'REQUESTER',customRoleId:role.id,customRoleVersion:1,projectAdmin:false,confirmed:true});
 assert.equal((await db.query('SELECT custom_role_id FROM project_memberships WHERE user_id=$1',[employee.id])).rows[0].custom_role_id,role.id);checks++;
 const second=randomUUID();await db.query("INSERT INTO projects(id,tenant_id,name,status,crew_build) VALUES($1,$2,'Future project','ACTIVE','FULL')",[second,f.tenant]);
 await db.query("INSERT INTO project_memberships(project_id,user_id,role,custom_role_id) VALUES($1,$2,'REQUESTER',$3)",[second,employee.id,role.id]);
 assert.equal((await readCustomRoles(db,auth,second as UUID))[0].id,role.id);checks++;
 await refuses(()=>deleteCustomRole(db,auth,role.id,1),'ConflictError');
 const beforeVersion=(await db.query('SELECT session_version FROM users WHERE id=$1',[employee.id])).rows[0].session_version;
 const edited=await saveCustomRole(db,auth,{name:'Project Coordinator',baseRole:'VIEWER'},role.id,1);
 const memberships=(await db.query('SELECT role,custom_role_id FROM project_memberships WHERE user_id=$1',[employee.id])).rows;
 assert.equal(memberships.length,2);assert(memberships.every(m=>m.role==='VIEWER'&&m.custom_role_id===role.id));
 assert.equal((await db.query('SELECT session_version FROM users WHERE id=$1',[employee.id])).rows[0].session_version,beforeVersion+1);checks++;
 await refuses(()=>saveCustomRole(db,auth,payload,role.id,1),'ConflictError');
 await refuses(()=>assignTemplateRole(db,auth,project,employee.id,{role:'REQUESTER',sessionVersion:beforeVersion}),'ConflictError');
 await assignTemplateRole(db,auth,project,employee.id,{role:'REQUESTER',sessionVersion:beforeVersion+1});
 assert.equal((await db.query('SELECT custom_role_id FROM project_memberships WHERE project_id=$1 AND user_id=$2',[project,employee.id])).rows[0].custom_role_id,null);checks++;
 await refuses(()=>assignTemplateRole(db,auth,project,f.subject as UUID,{role:'VIEWER',sessionVersion:1}),'ValidationError');
 await refuses(()=>assignTemplateRole(db,{...auth,userId:f.subject as UUID},project,employee.id,{role:'VIEWER',sessionVersion:beforeVersion+2}),'ForbiddenError');
 await refuses(()=>assignTemplateRole(db,auth,f.foreignProject as UUID,employee.id,{role:'VIEWER',sessionVersion:beforeVersion+2}),'NotFoundError');
 await refuses(()=>deleteCustomRole(db,auth,role.id,edited.version),'ConflictError');
 await db.query('UPDATE project_memberships SET custom_role_id=NULL WHERE custom_role_id=$1',[role.id]);
 await deleteCustomRole(db,auth,role.id,edited.version);assert.equal((await readCustomRoles(db,auth)).length,0);checks++;
 const failed={name:'Fault Role',baseRole:'REQUESTER'};await db.query('SAVEPOINT role_fault');
 await db.query(`CREATE FUNCTION fail_role_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.event_type='tenant.custom_role_created' THEN RAISE EXCEPTION 'synthetic role audit failure'; END IF; RETURN NEW; END $$`);
 await db.query('CREATE TRIGGER role_audit_fault BEFORE INSERT ON administrative_events FOR EACH ROW EXECUTE FUNCTION fail_role_audit()');
 await assert.rejects(saveCustomRole(db,auth,failed),/synthetic role audit failure/);await db.query('ROLLBACK TO SAVEPOINT role_fault');
 assert.equal((await db.query('SELECT count(*)::int n FROM tenant_custom_roles WHERE name=$1',[failed.name])).rows[0].n,0);checks++;
 console.log('Custom role PostgreSQL checks passed: '+checks);
}).catch(error=>{console.error(error);process.exitCode=1;});
