import {inUnitRequestScope} from '../setup/unit-request-scope';
import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {readFile,writeFile} from 'node:fs/promises';
import {NextRequest} from 'next/server';
import {getPool} from '../../src/lib/db';
import {signToken} from '../../src/lib/auth';
import {acquireTenantLifecycleLock} from '../../src/lib/tenant-lifecycle-lock';
import {GET as GETHandler,POST as POSTHandler} from '../../src/app/api/projects/[projectId]/survey/reorganization/route';
import {handlePostSurveyTeam as TEAM} from '../../src/app/api/projects/[projectId]/survey/teams/handler';
import type {UUID} from '../../src/shared/types';
const GET=inUnitRequestScope(GETHandler);
const POST=inUnitRequestScope(POSTHandler);
async function main(){
 const url=new URL(process.env.DATABASE_URL??'');assert.equal(process.env.SWR_RECONCILIATION_TEST,'1');assert.equal(url.hostname,'127.0.0.1');assert.equal(url.port,'15489');assert.equal(url.pathname,'/swr_team_isolated');assert.match(url.searchParams.get('options')??'',/^-c search_path=d4_current_[a-f0-9]{32},public$/);
 const owned=JSON.parse(await readFile('.local/alpha-acceptance197/ownership.json','utf8'));assert.equal(owned.owner,'Alpha acceptance197');assert.equal(owned.hostPort,15500);const pool=getPool(),checks:string[]=[];
 const tenant=randomUUID(),foreignTenant=randomUUID(),project=randomUUID(),otherProject=randomUUID(),foreignProject=randomUUID(),company=randomUUID(),scCompany=randomUUID(),foreignCompany=randomUUID(),level=randomUUID(),area=randomUUID(),area2=randomUUID(),area3=randomUUID();
 const people:Record<string,string>={},tokens:Record<string,string>={},roles:Record<string,string>={manager:'SURVEY_MANAGER',admin:'VIEWER',superintendent:'SURVEY_SUPERINTENDENT',destinationLead:'SURVEY_SUPERINTENDENT',chief:'PARTY_CHIEF',instrument:'INSTRUMENT_MAN',instrument2:'INSTRUMENT_MAN',destinationChief:'PARTY_CHIEF',requester:'REQUESTER',viewer:'VIEWER',subcontractor:'SURVEY_MANAGER',foreignManager:'SURVEY_MANAGER'};
 for(const who of Object.keys(roles))people[who]=randomUUID();
 await pool.query("INSERT INTO tenants(id,name) VALUES($1,'Owned crew190'),($2,'Owned foreign crew190')",[tenant,foreignTenant]);
 await pool.query("INSERT INTO companies(id,tenant_id,name,type) VALUES($1,$2,'Owned GC','GC'),($3,$2,'Owned subcontractor','SUBCONTRACTOR'),($4,$5,'Owned foreign GC','GC')",[company,tenant,scCompany,foreignCompany,foreignTenant]);
 for(const [id,t] of [[project,tenant],[otherProject,tenant],[foreignProject,foreignTenant]])await pool.query("INSERT INTO projects(id,tenant_id,name,status,crew_build) VALUES($1,$2,'Owned intact crew transfer','ACTIVE','FULL')",[id,t]);
 for(const [who,id] of Object.entries(people)){const foreign=who==='foreignManager',t=foreign?foreignTenant:tenant,p=foreign?foreignProject:project;await pool.query("INSERT INTO users(id,tenant_id,company_id,email,name,password_hash) VALUES($1,$2,$3,$4,$5,'no-login-fixture')",[id,t,foreign?foreignCompany:who==='subcontractor'?scCompany:company,id+'@crew190.invalid','Crew '+who]);await pool.query('INSERT INTO project_memberships(project_id,user_id,role) VALUES($1,$2,$3)',[p,id,roles[who]]);tokens[who]=signToken(id as UUID,t as UUID);}
 await pool.query("INSERT INTO tenant_memberships(tenant_id,user_id,role) VALUES($1,$2,'TENANT_ADMIN')",[tenant,people.admin!]);await pool.query("INSERT INTO project_admin_grants(tenant_id,project_id,user_id,origin,granted_by) VALUES($1,$2,$3,'EXPLICIT',$4)",[tenant,project,people.admin!,people.manager!]);
 await pool.query("INSERT INTO aor_levels(id,tenant_id,project_id,depth,label) VALUES($1,$2,$3,0,'Area')",[level,tenant,project]);for(const [id,name]of[[area,'Source Area'],[area2,'Transfer Area'],[area3,'Retained Coverage']])await pool.query('INSERT INTO aor_nodes(id,tenant_id,project_id,level_id,name,code) VALUES($1,$2,$3,$4,$5,$6)',[id,tenant,project,level,name,id]);
 for(const [who,areas]of[['superintendent',[area,area2]],['destinationLead',[area,area2]],['chief',[area]],['destinationChief',[area2]]] as const)for(const a of areas)await pool.query('INSERT INTO aor_assignments(tenant_id,project_id,user_id,aor_node_id) VALUES($1,$2,$3,$4)',[tenant,project,people[who],a]);
 await pool.query('INSERT INTO survey_reporting_links(tenant_id,project_id,superintendent_id,party_chief_id,aor_node_id,assigned_by) VALUES($1,$2,$3,$4,$5,$6)',[tenant,project,people.superintendent!,people.chief!,area,people.manager!]);for(const who of ['instrument','instrument2'])await pool.query('INSERT INTO crew_rosters(tenant_id,project_id,party_chief_id,instrument_man_id) VALUES($1,$2,$3,$4)',[tenant,project,people.chief!,people[who]]);
 const context=(id=project)=>({params:Promise.resolve({projectId:id})}),endpoint=(id=project)=>'http://localhost/api/projects/'+id+'/survey/reorganization';
 function request(method:string,who:string,body?:unknown,key:string=randomUUID(),p=project){return new NextRequest(endpoint(p),{method,headers:{cookie:'swr_session='+tokens[who],...(body?{'content-type':'application/json','Idempotency-Key':key}:{})},...(body?{body:JSON.stringify(body)}:{})});}
 async function result(response:Promise<Response>,status:number,label:string){const r=await response;assert.equal(r.status,status,label);checks.push(label);return r.json();}
 async function team(name:string,lead:string,ids:string[],areas:string[],primary:string){const body={teamId:null,expectedVersion:null,name,areaId:primary,areaIds:areas,leadUserId:lead,memberIds:ids};const req=new NextRequest('http://localhost/api/projects/'+project+'/survey/teams',{method:'POST',headers:{cookie:'swr_session='+tokens.manager,'content-type':'application/json','Idempotency-Key':randomUUID()},body:JSON.stringify(body)});return(await result(TEAM(req,context()),201,'Current Manager creates '+name)).teamId as string;}
 const source=await team('Source multi-Area team',people.superintendent!,[people.superintendent!,people.chief!,people.instrument!,people.instrument2!],[area,area2],area),destination=await team('Destination complete coverage',people.destinationLead!,[people.destinationLead!,people.destinationChief!],[area2,area3],area3);
 const selection={kind:'CREW',partyChiefId:people.chief!,areaId:area2,superintendentId:people.destinationLead!,destinationTeamId:destination};
 async function preview(input:Record<string,unknown>=selection,who='manager',p=project,status=200){const query=new URLSearchParams(Object.entries(input).map(([k,v])=>[k,String(v)]));const req=new NextRequest(endpoint(p)+'?'+query,{headers:{cookie:'swr_session='+tokens[who]}});const r=await GET(req,context(p));assert.equal(r.status,status);return (await r.json()).preview;}
 async function command(display:Awaited<ReturnType<typeof preview>>,who='manager',key:string=randomUUID(),patch:Record<string,unknown>={}){return POST(request('POST',who,{...display.selection,snapshot:display.snapshot,reason:'Move the complete reviewed crew to its explicit destination.',confirmed:true,...patch},key),context());}
 async function witness(){const rows=[];for(const t of ['survey_teams','survey_team_members','survey_team_areas','crew_rosters','survey_reporting_links','aor_assignments','survey_staffing_events','tickets','ticket_events','ticket_assignment_history','survey_work_delegations','api_idempotency'])rows.push((await pool.query(`SELECT row_to_json(t) r FROM ${t} t WHERE tenant_id=$1 ORDER BY row_to_json(t)::text`,[tenant])).rows);return createHash('sha256').update(JSON.stringify(rows)).digest('hex');}
 async function blocked(label:string,fragment:string,input:Record<string,unknown>=selection){const p=await preview(input);assert(p.blockers.some((s:string)=>s.includes(fragment)),label);const before=await witness();await result(command(p),409,label);assert.equal(await witness(),before,label+' no effects');}
 async function activeTicket(chief=people.chief!,instrument=people.instrument!){const id=randomUUID();await pool.query("INSERT INTO tickets(id,tenant_id,project_id,company_id,requester_id,workflow_variant,status,craft,field_contact,description,aor_node_id,ticket_type,requested_date,ticket_number,first_submitted_at,assigned_party_chief_id,assigned_instrument_man_id) VALUES($1,$2,$3,$4,$5,'STANDARD_APPROVAL','ASSIGNED','Survey','Owned contact','Owned transfer work',$6,'LAYOUT',CURRENT_DATE+7,$7,now(),$8,$9)",[id,tenant,project,company,people.requester!,area,'CREW190-'+id,chief,instrument]);return id;}
 try{
  const missingDestination={kind:'INSTRUMENT_MAN',instrumentManId:people.instrument!,partyChiefId:people.destinationChief!};
  const omitted=new NextRequest(endpoint()+'?'+new URLSearchParams(missingDestination),{headers:{cookie:'swr_session='+tokens.manager}});await result(GET(omitted,context()),400,'Instrument Man destination omission fails before guessing');
  await preview({...missingDestination,destinationTeamId:randomUUID()},'manager',project,404);checks.push('Nonexistent explicit destination is not inferred');
  await blocked('Chosen Chief must belong to chosen team','explicitly selected named team',{...missingDestination,destinationTeamId:source});
  let p=await preview();assert.equal(p.blockers.length,0);assert(p.summary.some((s:string)=>s.includes(people.instrument2!)));checks.push('Preview explicitly names complete current cohort and complete destination coverage');assert(p.summary.some((s:string)=>s.includes('Chief current individual Area: Source Area')&&s.includes('New individual Area: Transfer Area')));assert(p.summary.some((s:string)=>s.includes('Current reporting: Crew superintendent')&&s.includes('New reporting: Crew destinationLead')));checks.push('Current/new individual Area and reporting facts pair names with exact UUIDs');
  for(const who of ['admin','superintendent','chief','instrument','requester','viewer','subcontractor','foreignManager']){await preview(selection,who,project,403);checks.push(who+' has no Manager transfer authority');}
  await preview(selection,'manager',otherProject,403);checks.push('Wrong project grant cannot follow selected UUID');await preview(selection,'manager',foreignProject,403);checks.push('Foreign project remains undisclosed');await preview({...selection,destinationTeamId:randomUUID()},'manager',project,404);checks.push('Unknown destination cannot be inferred');const foreignDestination=randomUUID(),foreignLevel=randomUUID(),foreignArea=randomUUID();await pool.query("INSERT INTO aor_levels(id,tenant_id,project_id,depth,label) VALUES($1,$2,$3,0,'Area')",[foreignLevel,foreignTenant,foreignProject]);await pool.query("INSERT INTO aor_nodes(id,tenant_id,project_id,level_id,name,code) VALUES($1,$2,$3,$4,'Owned foreign Area','F')",[foreignArea,foreignTenant,foreignProject,foreignLevel]);await pool.query('BEGIN');await pool.query("INSERT INTO survey_teams(id,tenant_id,project_id,name,aor_node_id,lead_user_id,created_by) VALUES($1,$2,$3,'Owned foreign team',$4,$5,$5)",[foreignDestination,foreignTenant,foreignProject,foreignArea,people.foreignManager!]);await pool.query('INSERT INTO survey_team_members(tenant_id,project_id,team_id,user_id) VALUES($1,$2,$3,$4)',[foreignTenant,foreignProject,foreignDestination,people.foreignManager!]);await pool.query('COMMIT');await preview({...selection,destinationTeamId:foreignDestination},'manager',project,404);checks.push('Actual foreign-tenant named team remains undisclosed');await preview({...selection,partyChiefId:people.foreignManager!},'manager',project,404);checks.push('Foreign person UUID cannot create a crew authority');
  await result(command(p,'manager',randomUUID(),{confirmed:false}),400,'Explicit transfer consent required');await result(command(p,'manager',randomUUID(),{transferTickets:true}),400,'No request ownership transfer field accepted');
  await blocked('Broader Area change requires explicit named destination','explicit destination',{kind:'CREW',partyChiefId:people.chief!,areaId:area2,superintendentId:people.destinationLead!});await blocked('Destination must already cover selected Area','already cover',{...selection,areaId:area});
  await pool.query('UPDATE survey_teams SET lead_user_id=$3 WHERE tenant_id=$1 AND id=$2',[tenant,source,people.chief!]);await blocked('Moving source lead requires separate resolution','lead vacancy');await pool.query('UPDATE survey_teams SET lead_user_id=$3 WHERE tenant_id=$1 AND id=$2',[tenant,source,people.superintendent!]);
  await pool.query("UPDATE project_memberships SET access_disabled_at=now(),access_disabled_by=$3 WHERE project_id=$1 AND user_id=$2",[project,people.destinationLead!,people.manager!]);await blocked('Disabled destination lead cannot accept crew','lead vacancy',{...selection,superintendentId:people.superintendent!});await pool.query('UPDATE project_memberships SET access_disabled_at=NULL,access_disabled_by=NULL WHERE project_id=$1 AND user_id=$2',[project,people.destinationLead!]);
  await pool.query('UPDATE aor_nodes SET retired_at=now() WHERE tenant_id=$1 AND id=$2',[tenant,area3]);await blocked('Retired secondary destination coverage blocks transfer','retired named-team');await pool.query('UPDATE aor_nodes SET retired_at=NULL WHERE tenant_id=$1 AND id=$2',[tenant,area3]);
  await pool.query('UPDATE survey_team_members SET deactivated_at=now() WHERE tenant_id=$1 AND team_id=$2 AND user_id=$3',[tenant,source,people.instrument2!]);await blocked('Partial source membership cannot silently merge crew','whole current crew');await pool.query('UPDATE survey_team_members SET deactivated_at=NULL WHERE tenant_id=$1 AND team_id=$2 AND user_id=$3',[tenant,source,people.instrument2!]);
  await pool.query('UPDATE survey_team_members SET deactivated_at=now() WHERE tenant_id=$1 AND team_id=$2 AND user_id=$3',[tenant,source,people.superintendent!]);await blocked('Missing current source lead membership blocks transfer','current named-team lead vacancy');await pool.query('UPDATE survey_team_members SET deactivated_at=NULL WHERE tenant_id=$1 AND team_id=$2 AND user_id=$3',[tenant,source,people.superintendent!]);
  const work=await activeTicket();await blocked('Chief assigned work blocks explicit transfer','open crew requests');await pool.query("UPDATE tickets SET assigned_party_chief_id=$3 WHERE tenant_id=$1 AND id=$2",[tenant,work,people.destinationChief!]);await blocked('Included Instrument Man work under another Chief blocks transfer','open crew requests');
  await pool.query('UPDATE tickets SET assigned_instrument_man_id=NULL,field_validation_reviewer_id=$3 WHERE tenant_id=$1 AND id=$2',[tenant,work,people.chief!]);await blocked('Captured field reviewer duty blocks transfer','open crew requests');await pool.query("UPDATE tickets SET status='COMPLETED',field_validation_reviewer_id=NULL WHERE tenant_id=$1 AND id=$2",[tenant,work]);
  const pending=await activeTicket();await pool.query("UPDATE tickets SET status='APPROVED',assigned_instrument_man_id=NULL WHERE tenant_id=$1 AND id=$2",[tenant,pending]);await pool.query("INSERT INTO survey_work_delegations(tenant_id,project_id,ticket_id,team_id,lead_user_id,delegated_by) VALUES($1,$2,$3,$4,$5,$6)",[tenant,project,pending,source,people.superintendent!,people.manager!]);await blocked('Source team work awaiting crew cannot be stranded','source-team delegated');await pool.query("UPDATE survey_work_delegations SET ended_at=now(),end_reason='owned fixture resolution' WHERE tenant_id=$1 AND ticket_id=$2",[tenant,pending]);await pool.query("UPDATE tickets SET status='COMPLETED' WHERE tenant_id=$1 AND id=$2",[tenant,pending]);
  const legacy={kind:'CREW',partyChiefId:people.chief!,areaId:area,superintendentId:people.destinationLead!},legacyWork=await activeTicket(),teamBefore=JSON.stringify((await pool.query('SELECT t.*, (SELECT jsonb_agg(a ORDER BY a.area_id) FROM survey_team_areas a WHERE a.team_id=t.id) coverage FROM survey_teams t WHERE tenant_id=$1 ORDER BY id',[tenant])).rows);
  const lp=await preview(legacy);assert.equal(lp.blockers.length,0);await result(command(lp),200,'Existing same-Area reporting-only action remains valid with current work');assert.equal(JSON.stringify((await pool.query('SELECT t.*, (SELECT jsonb_agg(a ORDER BY a.area_id) FROM survey_team_areas a WHERE a.team_id=t.id) coverage FROM survey_teams t WHERE tenant_id=$1 ORDER BY id',[tenant])).rows),teamBefore);checks.push('Legacy reporting-only retains all team coverage, primary Areas and versions');await pool.query("UPDATE tickets SET status='COMPLETED' WHERE tenant_id=$1 AND id=$2",[tenant,legacyWork]);
  p=await preview();await pool.query('UPDATE survey_teams SET row_version=row_version+1 WHERE tenant_id=$1 AND id=$2',[tenant,destination]);await result(command(p),409,'Reviewed destination version change requires renewed preview');p=await preview();
  const fn='owned_crew_'+randomUUID().replaceAll('-',''),before=await witness();await pool.query('CREATE FUNCTION '+fn+"() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.tenant_id='"+tenant+"'::uuid AND NEW.event_type='survey.staffing_saved' THEN RAISE EXCEPTION 'owned crew audit failure'; END IF; RETURN NEW; END $$");await pool.query('CREATE TRIGGER '+fn+' BEFORE INSERT ON survey_staffing_events FOR EACH ROW EXECUTE FUNCTION '+fn+'()');try{await result(command(p),500,'Actual final staffing audit failure refuses whole transfer');assert.equal(await witness(),before);checks.push('Reporting/individual Area/source exit/destination membership/team audits and ledger roll back atomically');}finally{await pool.query('DROP TRIGGER '+fn+' ON survey_staffing_events');await pool.query('DROP FUNCTION '+fn+'()');}
  await pool.query("INSERT INTO ticket_assignment_history(tenant_id,ticket_id,party_chief_id,instrument_man_id,assigned_by,ended_at,end_reason) VALUES($1,$2,$3,$4,$5,now(),'owned completed fixture')",[tenant,work,people.chief!,people.instrument!,people.manager!]);await pool.query("INSERT INTO ticket_events(tenant_id,ticket_id,actor_id,event_type,payload) VALUES($1,$2,$3,'ticket.assigned',$4::jsonb)",[tenant,work,people.manager!,JSON.stringify({partyChiefId:people.chief,instrumentManId:people.instrument,fixture:true})]);
  const immutableBefore=JSON.stringify((await pool.query('SELECT row_to_json(t) r FROM ticket_assignment_history t WHERE tenant_id=$1 ORDER BY id',[tenant])).rows)+JSON.stringify((await pool.query('SELECT row_to_json(t) r FROM ticket_events t WHERE tenant_id=$1 ORDER BY id',[tenant])).rows);
  const history=JSON.stringify((await pool.query('SELECT row_to_json(t) r FROM tickets t WHERE tenant_id=$1 ORDER BY id',[tenant])).rows),roster=JSON.stringify((await pool.query('SELECT * FROM crew_rosters WHERE tenant_id=$1 ORDER BY id',[tenant])).rows),key=randomUUID();await result(command(p,'manager',key),200,'Manager transfers intact crew to explicitly reviewed destination');await result(command(p,'manager',key),200,'Exact original retry survives ended source membership');await result(command(p,'manager',key,{reason:'Different intent cannot replace recorded transfer.'}),409,'Same retry key cannot replace reviewed intent');
  assert.equal(JSON.stringify((await pool.query('SELECT row_to_json(t) r FROM tickets t WHERE tenant_id=$1 ORDER BY id',[tenant])).rows),history);assert.equal(JSON.stringify((await pool.query('SELECT * FROM crew_rosters WHERE tenant_id=$1 ORDER BY id',[tenant])).rows),roster);const memberships=(await pool.query('SELECT user_id,team_id FROM survey_team_members WHERE tenant_id=$1 AND user_id=ANY($2::uuid[]) AND deactivated_at IS NULL ORDER BY user_id',[tenant,[people.chief!,people.instrument!,people.instrument2!]])).rows;assert.equal(memberships.length,3);assert(memberships.every(r=>r.team_id===destination));checks.push('Whole crew changes named team together while exact roster and existing request rows remain unchanged');assert.equal(JSON.stringify((await pool.query('SELECT row_to_json(t) r FROM ticket_assignment_history t WHERE tenant_id=$1 ORDER BY id',[tenant])).rows)+JSON.stringify((await pool.query('SELECT row_to_json(t) r FROM ticket_events t WHERE tenant_id=$1 ORDER BY id',[tenant])).rows),immutableBefore);checks.push('Nonempty closed assignment and append-only ticket event evidence remain byte-identical');assert.equal((await pool.query("SELECT count(*)::int n FROM survey_staffing_events WHERE tenant_id=$1 AND event_type='survey.team_updated'",[tenant])).rows[0].n,2);checks.push('Exact retry records one source update and one destination update');
  const ts=(await pool.query('SELECT t.id,t.aor_node_id,ARRAY(SELECT area_id FROM survey_team_areas WHERE team_id=t.id AND deactivated_at IS NULL ORDER BY area_id) coverage FROM survey_teams t WHERE tenant_id=$1 ORDER BY id',[tenant])).rows;assert.deepEqual(ts.find(t=>t.id===source).coverage,[area,area2].sort());assert.deepEqual(ts.find(t=>t.id===destination).coverage,[area2,area3].sort());assert.equal(ts.find(t=>t.id===destination).aor_node_id,area3);checks.push('Source and destination retain complete coverage and independent primary Areas');assert.equal((await pool.query('SELECT aor_node_id FROM aor_assignments WHERE tenant_id=$1 AND user_id=$2 AND deactivated_at IS NULL',[tenant,people.chief!])).rows[0].aor_node_id,area2);checks.push('Only Chief individual Area changes; reporting link is explicit');
  await pool.query("UPDATE projects SET status='ARCHIVED' WHERE tenant_id=$1 AND id=$2",[tenant,project]);await result(command(p,'manager',key),409,'Archived project refuses historical transfer replay');await pool.query("UPDATE projects SET status='ACTIVE' WHERE tenant_id=$1 AND id=$2",[tenant,project]);await pool.query("UPDATE project_memberships SET role='VIEWER' WHERE project_id=$1 AND user_id=$2",[project,people.manager!]);await result(command(p,'manager',key),403,'Revoked current Manager role refuses historical replay');await pool.query("UPDATE project_memberships SET role='SURVEY_MANAGER' WHERE project_id=$1 AND user_id=$2",[project,people.manager!]);
  const imWork=await activeTicket(),imBefore=JSON.stringify((await pool.query('SELECT * FROM tickets WHERE tenant_id=$1 AND id=$2',[tenant,imWork])).rows),coverageBefore=JSON.stringify((await pool.query('SELECT * FROM survey_team_areas WHERE tenant_id=$1 ORDER BY team_id,area_id',[tenant])).rows);await result(command(await preview({kind:'INSTRUMENT_MAN',instrumentManId:people.instrument!,partyChiefId:people.destinationChief!,destinationTeamId:destination})),200,'Existing active Instrument Man transfer remains authorized');assert.equal(JSON.stringify((await pool.query('SELECT * FROM tickets WHERE tenant_id=$1 AND id=$2',[tenant,imWork])).rows),imBefore);assert.equal(JSON.stringify((await pool.query('SELECT * FROM survey_team_areas WHERE tenant_id=$1 ORDER BY team_id,area_id',[tenant])).rows),coverageBefore);checks.push('Active Instrument Man move preserves recorded Chief/work and every team Area');await pool.query("UPDATE tickets SET status='COMPLETED' WHERE tenant_id=$1 AND id=$2",[tenant,imWork]);
  // Two real concurrent commands reviewed against identical current same-team structure.
  const same={...selection,areaId:area2},current=await preview(same),race=await Promise.all([command(current),command(current)]);assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);checks.push('Concurrent reviewed crew commands serialize, one transition and one stale conflict');
  const fresh=await preview({...same,superintendentId:people.superintendent!}),holder=await pool.connect();try{await holder.query('BEGIN');await acquireTenantLifecycleLock(holder,tenant as UUID,'EXCLUSIVE');const holderPid=(await holder.query('SELECT pg_backend_pid() AS pid')).rows[0].pid,waiting=command(fresh);let observed=false;for(let attempt=0;attempt<40;attempt++){if((await pool.query("SELECT count(*)::int n FROM pg_stat_activity WHERE datname=current_database() AND wait_event_type='Lock' AND $1=ANY(pg_blocking_pids(pid))",[holderPid])).rows[0].n>0){observed=true;break;}await new Promise(r=>setTimeout(r,50));}assert(observed,'Observed actual lifecycle wait before revoking session');await holder.query('UPDATE users SET session_version=session_version+1 WHERE tenant_id=$1 AND id=$2',[tenant,people.manager!]);await holder.query('COMMIT');await result(waiting,401,'Current session revoked during observed lifecycle wait refuses command');tokens.manager=signToken(people.manager! as UUID,tenant as UUID,2);}finally{await holder.query('ROLLBACK');holder.release();}
  await writeFile('.local/d1-d8/d4/intact-crew-fixture.json',JSON.stringify({tenant,foreignTenant,project,otherProject,foreignProject,company,scCompany,area,area2,area3,source,destination,people,tokens}));console.log(JSON.stringify({checks:checks.length,cases:checks}));
 }finally{await pool.end();}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
