import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import bcrypt from 'bcrypt';
import {readFile} from 'node:fs/promises';
import {runLifecycleSchemaAcceptance} from './account-offboarding-postgres';
import {createProjectEmployee,type EmployeeInput} from '../../src/modules/tenancy/application/create-project-employee';
import {executeIdempotentHttpMutation} from '../../src/lib/idempotency';
import type {UUID} from '../../src/shared/types';

runLifecycleSchemaAcceptance(async(db,f)=>{
 await db.query(await readFile('db/migrations/032_administrative_events.sql','utf8'));
 const auth={tenantId:f.tenant as UUID,userId:f.actor as UUID,sessionVersion:1};
 const project=f.project as UUID;
 const company=(await db.query('SELECT company_id FROM users WHERE id=$1',[f.actor])).rows[0].company_id;
 await db.query('INSERT INTO project_companies(tenant_id,project_id,company_id,associated_by) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[f.tenant,f.project,company,f.actor]);
 const input=(overrides:Partial<EmployeeInput>={}):EmployeeInput=>({companyId:company,name:'Employee fixture',email:randomUUID()+'@example.test',password:'Synthetic-Employee-2026!',role:'REQUESTER',projectAdmin:false,confirmed:true,...overrides});
 const history=JSON.stringify((await db.query('SELECT row_to_json(t) FROM tickets t ORDER BY id')).rows);
 const payload=input({projectAdmin:true});
 const ledger={tenantId:auth.tenantId,actorId:auth.userId,endpoint:`POST /api/projects/${project}/employees`,idempotencyKey:randomUUID()};
 const create=()=>executeIdempotentHttpMutation(db,ledger,payload,async()=>({status:201,body:{employee:await createProjectEmployee(db,auth,project,payload)}}));
 const first=await create(),replay=await create();assert.deepEqual(first.body,replay.body);assert.equal(replay.replayed,true);
 const id=first.body.employee.id;
 const row=(await db.query('SELECT password_hash,session_version FROM users WHERE id=$1',[id])).rows[0];assert(await bcrypt.compare(payload.password,row.password_hash));
 assert.equal((await db.query('SELECT role FROM project_memberships WHERE project_id=$1 AND user_id=$2',[project,id])).rows[0].role,'REQUESTER');
 assert.equal((await db.query('SELECT count(*)::int n FROM project_admin_grants WHERE project_id=$1 AND user_id=$2 AND revoked_at IS NULL',[project,id])).rows[0].n,1);
 const events=(await db.query('SELECT event_type,changes FROM administrative_events WHERE subject_user_id=$1 ORDER BY event_type',[id])).rows;
 assert.deepEqual(events.map(e=>e.event_type),['project.admin_granted','user.provisioned']);assert(!JSON.stringify(events).includes(payload.password));assert(!JSON.stringify(first.body).includes(payload.password));
 let checks=8;
 async function refuses(fn:()=>Promise<unknown>,type:string){await db.query('SAVEPOINT negative_employee');try{await assert.rejects(fn,{type});}finally{await db.query('ROLLBACK TO SAVEPOINT negative_employee');}checks++;}
 await refuses(()=>createProjectEmployee(db,auth,project,payload),'ConflictError');
 await refuses(()=>createProjectEmployee(db,{...auth,userId:f.subject as UUID},project,input()),'ForbiddenError');
 await refuses(()=>createProjectEmployee(db,auth,f.foreignProject as UUID,input()),'NotFoundError');
 await refuses(()=>createProjectEmployee(db,auth,project,input({companyId:randomUUID() as UUID})),'NotFoundError');
 await refuses(()=>executeIdempotentHttpMutation(db,ledger,{...payload,name:'Changed'},async()=>({status:201,body:first.body})),'ConflictError');
 await db.query('SAVEPOINT archived_employee');await db.query("UPDATE projects SET status='ARCHIVED' WHERE id=$1",[project]);
 await assert.rejects(createProjectEmployee(db,auth,project,input()),{type:'ConflictError'});await db.query('ROLLBACK TO SAVEPOINT archived_employee');checks++;
 const sub=randomUUID();await db.query("INSERT INTO companies(id,tenant_id,name,type) VALUES($1,$2,'Sub','SUBCONTRACTOR')",[sub,f.tenant]);await db.query('INSERT INTO project_companies(tenant_id,project_id,company_id,associated_by) VALUES($1,$2,$3,$4)',[f.tenant,project,sub,f.actor]);
 await refuses(()=>createProjectEmployee(db,auth,project,input({companyId:sub as UUID,projectAdmin:true})),'ValidationError');
 await refuses(()=>createProjectEmployee(db,auth,project,input({companyId:sub as UUID,role:'VIEWER'})),'ValidationError');
 const subEmployee=await createProjectEmployee(db,auth,project,input({companyId:sub as UUID}));assert.equal(subEmployee.role,'REQUESTER');checks++;
 const central=await createProjectEmployee(db,auth,project,input());await db.query("INSERT INTO tenant_memberships(tenant_id,user_id,role) VALUES($1,$2,'TENANT_ADMIN')",[f.tenant,central.id]);
 await db.query('DELETE FROM project_memberships WHERE user_id=$1',[central.id]);
 const centralVersion=(await db.query('SELECT session_version FROM users WHERE id=$1',[central.id])).rows[0].session_version;
 await createProjectEmployee(db,{...auth,userId:central.id,sessionVersion:centralVersion},project,input());checks++;
 const failed=input();await db.query('SAVEPOINT employee_fault');await db.query(`CREATE FUNCTION fail_employee_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.event_type='user.provisioned' THEN RAISE EXCEPTION 'synthetic audit failure'; END IF; RETURN NEW; END $$`);
 await db.query('CREATE TRIGGER employee_audit_fault BEFORE INSERT ON administrative_events FOR EACH ROW EXECUTE FUNCTION fail_employee_audit()');
 await assert.rejects(createProjectEmployee(db,auth,project,failed),/synthetic audit failure/);await db.query('ROLLBACK TO SAVEPOINT employee_fault');assert.equal((await db.query('SELECT count(*)::int n FROM users WHERE email=$1',[failed.email])).rows[0].n,0);checks++;
 assert.equal(JSON.stringify((await db.query('SELECT row_to_json(t) FROM tickets t ORDER BY id')).rows),history);checks++;
 console.log('Project employee PostgreSQL checks passed: '+checks);
}).catch(error=>{console.error(error);process.exitCode=1;});
