import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {NextRequest} from 'next/server';
import {runLifecycleSchemaAcceptance} from './account-offboarding-postgres';
import {getPool} from '../../src/lib/db';
import {signToken} from '../../src/lib/auth';
import {resolveDepartmentMembershipActorRole,handlePostDepartmentMembers} from '../../src/app/api/projects/[projectId]/departments/[departmentId]/members/handler';
import {POST as members} from '../../src/app/api/projects/[projectId]/members/route';
import {POST as companies,GET as readCompanies,DELETE as removeCompanies} from '../../src/app/api/projects/[projectId]/companies/route';
import {POST as administrators} from '../../src/app/api/projects/[projectId]/administrators/route';
import {PATCH as template} from '../../src/app/api/projects/[projectId]/template/route';
import {GET as diagnostics} from '../../src/app/api/projects/[projectId]/diagnostics/route';
import {GET as discovery} from '../../src/app/api/projects/administration/route';
import {POST as whitelist} from '../../src/app/api/projects/[projectId]/whitelist/route';
import {handlePostProjectArchive} from '../../src/app/api/projects/[projectId]/archive/handler';
import {POST as tenantRole} from '../../src/app/api/tenant-memberships/route';
import {POST as tenantCompany} from '../../src/app/api/companies/route';
import {handlePostProject} from '../../src/app/api/projects/post-handler';
import {handlePostProjectTemplates} from '../../src/app/api/project-templates/handler';
import type {UUID} from '../../src/shared/types';
runLifecycleSchemaAcceptance(async(db,f)=>{
 await db.query(await readFile('db/migrations/032_administrative_events.sql','utf8'));
 await db.query('UPDATE users SET deactivated_at=NULL,deactivated_by=NULL,session_version=1 WHERE tenant_id=$1',[f.tenant]);
 await db.query("UPDATE project_memberships SET access_disabled_at=NULL,access_disabled_by=NULL,role=CASE WHEN user_id=$2 THEN 'SURVEY_MANAGER' ELSE 'REQUESTER' END WHERE project_id=$1",[f.project,f.actor]);
 const app=getPool(),oldQuery=app.query,oldConnect=app.connect,oldSecret=process.env.JWT_SECRET;
 process.env.JWT_SECRET='project-admin-acceptance-secret';let checks=0,failAudit=false;
 app.query=db.query.bind(db) as typeof app.query;
 app.connect=(async()=>({query:async(sql:string,params?:unknown[])=>{
  if(sql==='BEGIN')return db.query('SAVEPOINT local_admin_route');if(sql==='COMMIT')return db.query('RELEASE SAVEPOINT local_admin_route');if(sql==='ROLLBACK')return db.query('ROLLBACK TO SAVEPOINT local_admin_route');
  if(failAudit&&sql.includes('INSERT INTO administrative_events'))throw Error('Synthetic evidence failure');return db.query(sql,params);
 },release:()=>{}})) as typeof app.connect;
 const req=(body?:unknown,key=randomUUID(),method='POST')=>new NextRequest('http://localhost/api/admin',{method,headers:{cookie:'swr_session='+signToken(f.actor as UUID,f.tenant as UUID,1),'content-type':'application/json','idempotency-key':key},body:body===undefined?undefined:JSON.stringify(body)});
 const ctx=(projectId=f.project)=>({params:Promise.resolve({projectId})});
 const expect=async(response:Response,status=200)=>{assert.equal(response.status,status,JSON.stringify(await response.clone().json()));checks++;return response.json();};
 const count=async(table:string)=>(await db.query('SELECT count(*)::int AS n FROM '+table)).rows[0].n;
 try{
  const registered=await expect(await companies(req({name:'Local company',type:'GC',confirmed:true}),ctx()));
  const company=registered.company.id;assert.equal(await count('project_companies'),1);checks++;
  const duplicateCompanies=await count('companies'),duplicateEvents=await count('administrative_events');
  for(const name of ['Local company','  LOCAL   COMPANY  ','Local\tcompany'])await expect(await companies(req({name,type:'SUBCONTRACTOR',confirmed:true}),ctx()),409);
  assert.equal(await count('companies'),duplicateCompanies);assert.equal(await count('administrative_events'),duplicateEvents);checks+=2;
  // Selected company removal is atomic, versioned, scoped and preserves tenant records.
  const removable=[];
  for(const name of ['Removal one','Removal two'])removable.push((await expect(await companies(req({name,type:'GC',confirmed:true}),ctx()))).company.id);
  const review=async(ids:string[])=>{const records=await expect(await readCompanies(req(undefined,randomUUID(),'GET'),ctx()));return {companies:records.companies.filter((c:{id:string})=>ids.includes(c.id)).map((c:{id:string;associatedAt:string})=>({id:c.id,associatedAt:c.associatedAt})),confirmed:true};};
  const removal=await review(removable),removalKey=randomUUID();
  await expect(await removeCompanies(req({...removal,confirmed:false},randomUUID(),'DELETE'),ctx()),400);
  await expect(await removeCompanies(req({companies:[],confirmed:true},randomUUID(),'DELETE'),ctx()),400);
  await expect(await removeCompanies(req({companies:[removal.companies[0],removal.companies[0]],confirmed:true},randomUUID(),'DELETE'),ctx()),400);
  await expect(await removeCompanies(req({...removal,companies:removal.companies.map((c:{id:string;associatedAt:string})=>({...c,associatedAt:'stale'}))},randomUUID(),'DELETE'),ctx()),409);
  const associationCount=await count('project_companies'),auditCount=await count('administrative_events');
  failAudit=true;await expect(await removeCompanies(req(removal,randomUUID(),'DELETE'),ctx()),500);failAudit=false;
  assert.equal(await count('project_companies'),associationCount);assert.equal(await count('administrative_events'),auditCount);checks+=2;
  assert.equal((await expect(await removeCompanies(req(removal,removalKey,'DELETE'),ctx()))).removed,2);checks++;
  assert.equal((await db.query('SELECT count(*)::int n FROM companies WHERE id=ANY($1::uuid[])',[removable])).rows[0].n,2);checks++;
  const removalEvents=await count('administrative_events');await expect(await removeCompanies(req(removal,removalKey,'DELETE'),ctx()));assert.equal(await count('administrative_events'),removalEvents);checks++;
  await expect(await removeCompanies(req({...removal,companies:removal.companies.slice(0,1)},removalKey,'DELETE'),ctx()),409);
  await expect(await removeCompanies(req(removal,randomUUID(),'DELETE'),ctx()),409);
  await expect(await companies(req({companyId:removable[0],confirmed:true}),ctx()));
  // This route harness shares one outer transaction; advance NOW()'s otherwise fixed timestamp to model a later association.
  await db.query("UPDATE project_companies SET associated_at=associated_at+interval '1 microsecond' WHERE company_id=$1",[removable[0]]);
  await expect(await removeCompanies(req({companies:[removal.companies[0]],confirmed:true},randomUUID(),'DELETE'),ctx()),409);
  const blockedUser=randomUUID();await db.query("INSERT INTO users(id,tenant_id,company_id,email,name,password_hash) VALUES($1,$2,$3,$4,'Removal dependent','fixture')",[blockedUser,f.tenant,removable[0],blockedUser+'@example.test']);
  await db.query("INSERT INTO project_memberships(project_id,user_id,role) VALUES($1,$2,'REQUESTER')",[f.project,blockedUser]);
  let currentRemoval=await review([removable[0]]);await expect(await removeCompanies(req(currentRemoval,randomUUID(),'DELETE'),ctx()),409);
  await db.query('UPDATE users SET deactivated_at=NOW(),deactivated_by=$2 WHERE id=$1',[blockedUser,f.actor]);await expect(await removeCompanies(req(currentRemoval,randomUUID(),'DELETE'),ctx()),409);
  await db.query('UPDATE project_memberships SET access_disabled_at=NOW(),access_disabled_by=$2 WHERE user_id=$1',[blockedUser,f.actor]);
  const invite=randomUUID();await db.query("INSERT INTO invites(id,tenant_id,project_id,company_id,email,role,invited_by,expires_at) VALUES($1,$2,$3,$4,$5,'REQUESTER',$6,NOW()+interval '1 day')",[invite,f.tenant,f.project,removable[0],invite+'@example.test',f.actor]);
  await expect(await removeCompanies(req(currentRemoval,randomUUID(),'DELETE'),ctx()),409);await db.query('UPDATE invites SET canceled_at=NOW() WHERE id=$1',[invite]);
  const grant=randomUUID();await db.query("INSERT INTO project_responsibility_grants(id,tenant_id,project_id,user_id,responsibility,granted_by) VALUES($1,$2,$3,$4,'SURVEY_REVIEWER',$5)",[grant,f.tenant,f.project,blockedUser,f.actor]);
  await expect(await removeCompanies(req(currentRemoval,randomUUID(),'DELETE'),ctx()),409);await db.query('UPDATE project_responsibility_grants SET revoked_at=NOW(),revoked_by=$2 WHERE id=$1',[grant,f.actor]);
  currentRemoval=await review([removable[0]]);await expect(await removeCompanies(req(currentRemoval,randomUUID(),'DELETE'),ctx()));
  assert.equal((await db.query('SELECT count(*)::int n FROM project_memberships WHERE user_id=$1',[blockedUser])).rows[0].n,1);assert.equal((await db.query('SELECT count(*)::int n FROM invites WHERE id=$1',[invite])).rows[0].n,1);assert.equal((await db.query('SELECT count(*)::int n FROM project_responsibility_grants WHERE id=$1',[grant])).rows[0].n,1);checks+=3;
  // Fresh independent authority precedes even a successful recorded removal replay.
  await db.query('UPDATE project_admin_grants SET revoked_at=NOW(),revoked_by=$2 WHERE user_id=$1',[f.actor,blockedUser]);await expect(await removeCompanies(req(removal,removalKey,'DELETE'),ctx()),403);await db.query('UPDATE project_admin_grants SET revoked_at=NULL,revoked_by=NULL WHERE user_id=$1',[f.actor]);
  await expect(await removeCompanies(req(removal,randomUUID(),'DELETE'),ctx(f.foreignProject)),404);
  const person=randomUUID();await db.query("INSERT INTO users(id,tenant_id,company_id,email,name,password_hash) VALUES($1,$2,$3,$4,'Candidate','fixture')",[person,f.tenant,company,person+'@example.test']);
  const choices=await expect(await readCompanies(req(undefined,randomUUID(),'GET'),ctx()));assert.equal(choices.candidates.some((u:{userId:string})=>u.userId===person),true);checks++;
  const memberBody={userId:person,role:'REQUESTER'},memberKey=randomUUID();await expect(await members(req(memberBody,memberKey),ctx()),201);
  const events=await count('administrative_events');await expect(await members(req(memberBody,memberKey),ctx()),201);assert.equal(await count('administrative_events'),events);checks++;
  await expect(await members(req({userId:person,role:'SURVEY_MANAGER'}),ctx()),409);
  const grantBody={userId:person,enabled:true,confirmed:true},grantKey=randomUUID();await expect(await administrators(req(grantBody,grantKey),ctx()),403);
  await db.query("INSERT INTO tenant_memberships(tenant_id,user_id,role) VALUES($1,$2,'TENANT_ADMIN')",[f.tenant,f.actor]);await expect(await administrators(req(grantBody,grantKey),ctx()));
  await expect(await tenantCompany(req({name:' LOCAL   company ',type:'GC'})),409);
  assert.equal((await db.query('SELECT role FROM project_memberships WHERE user_id=$1',[person])).rows[0].role,'REQUESTER');checks++;
  assert.equal((await db.query('SELECT session_version FROM users WHERE id=$1',[person])).rows[0].session_version,3);checks++;
  await expect(await administrators(req(grantBody,grantKey),ctx()));assert.equal((await db.query('SELECT session_version FROM users WHERE id=$1',[person])).rows[0].session_version,3);checks++;
  await expect(await administrators(req({userId:person,enabled:false,confirmed:true}),ctx()));assert.equal((await db.query('SELECT role FROM project_memberships WHERE user_id=$1',[person])).rows[0].role,'REQUESTER');checks++;
  // A40/P05: independent administration does not change actual Manager role.
  await db.query("UPDATE project_memberships SET role='SURVEY_MANAGER' WHERE user_id=$1",[person]);
  await expect(await administrators(req({userId:person,enabled:true,confirmed:true}),ctx()));
  assert.equal((await db.query('SELECT role FROM project_memberships WHERE user_id=$1',[person])).rows[0].role,'SURVEY_MANAGER');checks++;
  await expect(await administrators(req({userId:person,enabled:false,confirmed:true}),ctx()));
  assert.equal((await db.query('SELECT role FROM project_memberships WHERE user_id=$1',[person])).rows[0].role,'SURVEY_MANAGER');checks++;
  await db.query('DELETE FROM tenant_memberships WHERE user_id=$1',[f.actor]);
  await db.query("UPDATE projects SET status='SETUP' WHERE id=$1",[f.project]);
  const department=randomUUID();await db.query("INSERT INTO departments(id,tenant_id,project_id,name,manager_title,created_by) VALUES($1,$2,$3,'Admin parity department','Manager',$4)",[department,f.tenant,f.project,f.actor]);
  await expect(await handlePostDepartmentMembers(req({userId:person}),{params:Promise.resolve({projectId:f.project,departmentId:department})}),201);
  // Stacked delegated authority chooses the correct branch for each title layer.
  await db.query("UPDATE project_memberships SET role='DEPARTMENT_MANAGER' WHERE user_id=$1",[f.actor]);
  await db.query("INSERT INTO department_titles(id,tenant_id,department_id,title,default_priority,assignment_layer) VALUES($1,$2,$3,'Delegate','NORMAL','SUPERINTENDENT'),($4,$2,$3,'Manager','NORMAL','MANAGER')",[randomUUID(),f.tenant,department,randomUUID()]);
  assert.equal(await resolveDepartmentMembershipActorRole(db,f.tenant as UUID,f.project as UUID,f.actor as UUID,1,{departmentId:department as UUID,title:'Delegate'}),'DEPARTMENT_MANAGER');checks++;
  assert.equal(await resolveDepartmentMembershipActorRole(db,f.tenant as UUID,f.project as UUID,f.actor as UUID,1,{departmentId:department as UUID,title:'Manager'}),'PROJECT_ADMIN');checks++;
  const centralOnly=randomUUID();await db.query("INSERT INTO users(id,tenant_id,company_id,email,name,password_hash) VALUES($1,$2,$3,$4,'Central without membership','fixture')",[centralOnly,f.tenant,company,centralOnly+'@example.test']);await db.query("INSERT INTO tenant_memberships(tenant_id,user_id,role) VALUES($1,$2,'TENANT_ADMIN')",[f.tenant,centralOnly]);
  assert.equal(await resolveDepartmentMembershipActorRole(db,f.tenant as UUID,f.project as UUID,centralOnly as UUID,1,{departmentId:department as UUID,title:'Manager'}),'TENANT_ADMIN');checks++;
  await db.query("INSERT INTO project_memberships(project_id,user_id,role,access_disabled_at,access_disabled_by) VALUES($1,$2,'REQUESTER',NOW(),$3)",[f.project,centralOnly,f.actor]);
  assert.equal(await resolveDepartmentMembershipActorRole(db,f.tenant as UUID,f.project as UUID,centralOnly as UUID,1,{departmentId:department as UUID,title:'Manager'}),'TENANT_ADMIN');checks++;

  await db.query("UPDATE project_memberships SET role='SURVEY_MANAGER' WHERE user_id=$1",[f.actor]);
  await db.query("UPDATE projects SET status='ACTIVE' WHERE id=$1",[f.project]);
  // P05: changing actual operational role leaves independent administration intact.
  await db.query("UPDATE project_memberships SET role='VIEWER' WHERE user_id=$1",[f.actor]);
  await expect(await diagnostics(req(undefined,randomUUID(),'GET'),ctx()));
  assert.equal((await db.query('SELECT count(*)::int AS n FROM project_admin_grants WHERE user_id=$1 AND revoked_at IS NULL',[f.actor])).rows[0].n,1);checks++;
  await db.query("UPDATE project_memberships SET role='SURVEY_MANAGER' WHERE user_id=$1",[f.actor]);
  const localProject=randomUUID();await db.query("INSERT INTO projects(id,tenant_id,name,status,crew_build) VALUES($1,$2,'Other local','SETUP','FULL')",[localProject,f.tenant]);
  await expect(await companies(req({companyId:company,confirmed:true}),ctx(localProject)),403);
  assert.equal((await db.query('SELECT count(*)::int AS n FROM project_memberships WHERE project_id=$1',[localProject])).rows[0].n,0);checks++;
  const d=await expect(await discovery(req(undefined,randomUUID(),'GET')));assert.equal(d.canCreateProject,false);assert.deepEqual(d.projects.map((p:{id:string})=>p.id),[f.project]);checks+=2;
  await expect(await diagnostics(req(undefined,randomUUID(),'GET'),ctx()));await expect(await diagnostics(req(undefined,randomUUID(),'GET'),ctx(f.foreignProject)),404);
  const foreign=(await db.query('SELECT company_id FROM users WHERE tenant_id<>$1 LIMIT 1',[f.tenant])).rows[0].company_id;
  await expect(await companies(req({companyId:foreign,confirmed:true}),ctx()),404);
  await expect(await tenantRole(req({userId:person,role:'TENANT_ADMIN'})),403);
  await expect(await tenantCompany(req({name:'Forbidden shared company',type:'GC'})),403);
  await expect(await handlePostProject(req({name:'Forbidden project',crewBuild:'FULL'})),403);
  await expect(await handlePostProjectTemplates(req({name:'Forbidden template',crewBuild:'FULL',aorDepth:1,aorLevelLabels:['Area'],disciplineGroups:[]})),403);
  const whitelistBody={email:'priority@example.test'},whitelistKey=randomUUID();await expect(await whitelist(req(whitelistBody,whitelistKey),ctx()),201);const wlEvents=await count('administrative_events');await expect(await whitelist(req(whitelistBody,whitelistKey),ctx()),201);assert.equal(await count('administrative_events'),wlEvents);checks++;
  const sub=await expect(await companies(req({name:'Subcontractor',type:'SUBCONTRACTOR',confirmed:true}),ctx()));
  const subUser=randomUUID();await db.query("INSERT INTO users(id,tenant_id,company_id,email,name,password_hash) VALUES($1,$2,$3,$4,'Sub person','fixture')",[subUser,f.tenant,sub.company.id,subUser+'@example.test']);
  await expect(await members(req({userId:subUser,role:'SURVEY_MANAGER'}),ctx()),403);await expect(await members(req({userId:subUser,role:'REQUESTER'}),ctx()),201);await expect(await administrators(req({userId:subUser,enabled:true,confirmed:true}),ctx()),403);
  const beforeCompanies=await count('companies'),beforeEvents=await count('administrative_events');failAudit=true;await expect(await companies(req({name:'Rollback company',type:'GC',confirmed:true}),ctx()),500);failAudit=false;assert.equal(await count('companies'),beforeCompanies);assert.equal(await count('administrative_events'),beforeEvents);checks+=2;
  await db.query("UPDATE projects SET status='SETUP' WHERE id=$1",[f.project]);const selected=randomUUID();await db.query("INSERT INTO project_templates(id,tenant_id,name,crew_build,aor_depth,aor_level_labels,discipline_groups) VALUES($1,$2,'Eligible','SLIM',1,'[\"Area\"]','[]')",[selected,f.tenant]);
  await expect(await template(req({templateId:selected,confirmed:true},randomUUID(),'PATCH'),ctx()));assert.equal((await db.query('SELECT crew_build FROM projects WHERE id=$1',[f.project])).rows[0].crew_build,'SLIM');checks++;
  await db.query("UPDATE projects SET status='ACTIVE' WHERE id=$1",[f.project]);await expect(await template(req({templateId:selected,confirmed:true},randomUUID(),'PATCH'),ctx()),409);
  await db.query('UPDATE project_admin_grants SET revoked_at=NOW(),revoked_by=$2 WHERE user_id=$1',[f.actor,person]);await expect(await administrators(req(grantBody,grantKey),ctx()),403);
  await db.query('UPDATE project_admin_grants SET revoked_at=NULL,revoked_by=NULL WHERE user_id=$1',[f.actor]);
  const archiveKey=randomUUID();await expect(await handlePostProjectArchive(req({},archiveKey),ctx()));await expect(await handlePostProjectArchive(req({},archiveKey),ctx()));assert.equal((await db.query('SELECT status FROM projects WHERE id=$1',[localProject])).rows[0].status,'SETUP');checks++;
  await expect(await companies(req({name:'Archived mutation',type:'GC',confirmed:true}),ctx()),409);
  await expect(await removeCompanies(req(removal,removalKey,'DELETE'),ctx()),409);
  console.log('Project administration PostgreSQL checks passed: '+checks);
 }finally{app.query=oldQuery;app.connect=oldConnect;if(oldSecret===undefined)delete process.env.JWT_SECRET;else process.env.JWT_SECRET=oldSecret;}
}).catch(error=>{console.error(error);process.exitCode=1;});
