import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { SuperintendentAreasPgRepository } from '../../src/modules/tenancy/infrastructure/superintendent-areas.repository';
import { TicketRepository } from '../../src/modules/ticket/infrastructure/ticket.repository';
import { SqlMyAccountReader } from '../../src/modules/tenancy/infrastructure/my-account.reader';
import { runLifecycleSchemaAcceptance } from './account-offboarding-postgres';
import { resolveProjectCapabilities, assertProjectAdministrator } from '../../src/lib/project-capabilities';
import { lockDraftActor } from '../../src/modules/ticket/application/draft-access';
import { requireSurveyReviewAuthority } from '../../src/lib/survey-review-authority';
import { NextRequest } from 'next/server';
import { handleGetProjects } from '../../src/app/api/projects/get-handler';
import { assertActiveSession } from '../../src/lib/auth';
import { ProtectedObligationsPgRepository } from '../../src/modules/tenancy/infrastructure/protected-obligations.repository';
import { SurveyWorkforcePgRepository } from '../../src/modules/tenancy/infrastructure/survey-workforce.repository';
import { NotificationRepository } from '../../src/modules/notification/infrastructure';
import { getProjectRole } from '../../src/lib/get-project-role';
import { SurveyStaffingPgRepository } from '../../src/modules/tenancy/infrastructure/survey-staffing.repository';
import { SurveyTeamsPgRepository } from '../../src/modules/tenancy/infrastructure/survey-teams.repository';
import { TenancyRepository } from '../../src/modules/tenancy/infrastructure/tenancy.repository';
import type { UUID } from '../../src/shared/types';

runLifecycleSchemaAcceptance(async(db,f)=>{
  const auth={tenantId:f.tenant as UUID,userId:f.subject as UUID,sessionVersion:1};
  const project=f.project as UUID;
  let checks=0;
  let caps=await resolveProjectCapabilities(db,auth,project);
  assert.deepEqual(caps,{operationalRole:'SURVEY_MANAGER',canAdminister:false,centralIT:false,accessDisabled:false}); checks++;
  await assert.rejects(assertProjectAdministrator(db,auth,project),{type:'ForbiddenError'}); checks++;
  await db.query("INSERT INTO project_admin_grants(tenant_id,project_id,user_id,granted_by,origin) VALUES($1,$2,$3,$4,'EXPLICIT')",[f.tenant,f.project,f.subject,f.actor]);
  caps=await resolveProjectCapabilities(db,auth,project);
  assert.equal(caps.operationalRole,'SURVEY_MANAGER'); assert.equal(caps.canAdminister,true); checks++;
  await lockDraftActor(db,{tenantId:auth.tenantId,projectId:project,actorId:auth.userId,sessionVersion:1},'PROJECT_ADMIN'); checks++;
  const protectedRepo=new ProtectedObligationsPgRepository();
  assert.equal((await protectedRepo.readAuthority(db,auth,project)).branch,'PROJECT_IT','independent grant carries protected-duty IT authority'); checks++;
  const workforce=new SurveyWorkforcePgRepository();
  const workforceActor={tenantId:auth.tenantId,projectId:project,actorId:auth.userId,actorRole:'SURVEY_MANAGER' as const,sessionVersion:1};
  assert.ok(await workforce.context(db,workforceActor)); checks++;
  const staffing=new SurveyStaffingPgRepository();
  const area=randomUUID(),level=randomUUID();
  await db.query("INSERT INTO aor_levels(id,tenant_id,project_id,depth,label) VALUES($1,$2,$3,0,'Area')",[level,f.tenant,f.project]);
  await db.query("INSERT INTO aor_nodes(id,tenant_id,project_id,level_id,name,code) VALUES($1,$2,$3,$4,'Synthetic Area','SYN')",[area,f.tenant,f.project,level]);
  await db.query("INSERT INTO aor_assignments(tenant_id,project_id,user_id,aor_node_id) VALUES($1,$2,$3,$4)",[f.tenant,f.project,f.subject,area]);
  const account=new SqlMyAccountReader();
  assert.deepEqual((await account.assignment(db,auth.tenantId,project,auth.userId)).areas,['Synthetic Area']); checks++;
  const beforeStamp=await staffing.snapshot(db,auth.tenantId,project);
  await db.query('UPDATE project_memberships SET access_disabled_at=NOW(),access_disabled_by=$3 WHERE project_id=$1 AND user_id=$2',[f.project,f.subject,f.actor]);
  caps=await resolveProjectCapabilities(db,auth,project);
  assert.deepEqual(caps,{operationalRole:null,canAdminister:false,centralIT:false,accessDisabled:true}); checks++;
  await assert.rejects(getProjectRole(db,auth.tenantId,project,auth.userId,1),{type:'ForbiddenError'}); checks++;
  await assert.rejects(requireSurveyReviewAuthority(db,{tenantId:auth.tenantId,projectId:project,aorNodeId:null},{actorId:auth.userId,actorRole:'SURVEY_MANAGER'}),{type:'ForbiddenError'}); checks++;
  assert.notEqual(await staffing.snapshot(db,auth.tenantId,project),beforeStamp,'staffing snapshot must include project access stamp'); checks++;
  await assert.rejects(protectedRepo.readAuthority(db,auth,project),{type:'ForbiddenError'}); checks++;
  assert.equal(await workforce.context(db,workforceActor),null); checks++;
  assert.deepEqual(await account.assignment(db,auth.tenantId,project,auth.userId),{areas:[],crew:[]},'disabled project assignments are not current account duties'); checks++;
  assert.equal(await staffing.member(db,auth.tenantId,project,auth.userId),null,'disabled member cannot receive staffing assignment'); checks++;
  const readiness=await new TenancyRepository().getProjectActivationReadiness(db,auth.tenantId,project);
  assert.equal(readiness.surveyManagerCount,0,'disabled Manager is not an activation witness'); checks++;
  await db.query("UPDATE project_memberships SET role='PARTY_CHIEF' WHERE project_id=$1 AND user_id=$2",[f.project,f.subject]);
  assert.equal(await new TicketRepository().isActiveProjectMemberWithRole(db,auth.tenantId,project,auth.userId,['PARTY_CHIEF']),false); checks++;
  assert.equal(await staffing.readStaffing(db,auth.tenantId,project,auth.userId,{search:'',limit:25,offset:0}),null); checks++;
  const candidates=await new SurveyTeamsPgRepository().personnel(db,auth.tenantId,project,{search:'Subject',limit:25,offset:0});
  assert.equal(candidates.total,0,'disabled member cannot be a team assignment candidate'); checks++;
  await db.query("UPDATE project_memberships SET role='SURVEY_SUPERINTENDENT' WHERE project_id=$1 AND user_id=$2",[f.project,f.subject]);
  await db.query("UPDATE project_memberships SET role='SURVEY_MANAGER' WHERE project_id=$1 AND user_id=$2",[f.project,f.actor]);
  const actorAuthority=await protectedRepo.readAuthority(db,{...auth,userId:f.actor as UUID},project);
  const people=await protectedRepo.readPage(db,{tenantId:auth.tenantId,projectId:project},actorAuthority,{mode:'personnel',query:{search:'Subject',limit:25,offset:0}});
  assert.equal(people.mode,'personnel'); if(people.mode==='personnel'){assert.equal(people.personnel.data[0]!.active,false);} checks++;
  const areaRepo=new SuperintendentAreasPgRepository();
  const disabledArea=await areaRepo.readPage(db,{...auth,userId:f.actor as UUID},project,{mode:'superintendent-areas',superintendentId:auth.userId,query:{search:'',limit:25,offset:0}});
  assert.equal(disabledArea.person.active,false);
  if(disabledArea.mode==='superintendent-areas'){assert.equal(disabledArea.assignments.data[0]!.canUnlink,false);} checks++;
  await db.query("UPDATE project_memberships SET role='SURVEY_MANAGER' WHERE project_id=$1 AND user_id=$2",[f.project,f.subject]);
  await assert.rejects(areaRepo.readPage(db,auth,project,{mode:'superintendent-areas',superintendentId:auth.userId,query:{search:'',limit:25,offset:0}}),{type:'ForbiddenError'}); checks++;
  await db.query("UPDATE project_memberships SET role='PROJECT_ADMIN' WHERE project_id=$1 AND user_id=$2",[f.project,f.actor]);
  await db.query("UPDATE project_memberships SET role='SURVEY_MANAGER' WHERE project_id=$1 AND user_id=$2",[f.project,f.subject]);
  await db.query("INSERT INTO tenant_memberships(tenant_id,user_id,role) VALUES($1,$2,'TENANT_ADMIN')",[f.tenant,f.subject]);
  caps=await resolveProjectCapabilities(db,auth,project);
  assert.deepEqual(caps,{operationalRole:null,canAdminister:true,centralIT:true,accessDisabled:true}); checks++;
  await assert.rejects(resolveProjectCapabilities(db,auth,f.foreignProject as UUID),{type:'NotFoundError'}); checks++;
  await db.query('UPDATE project_admin_grants SET revoked_at=NOW(),revoked_by=$4 WHERE tenant_id=$1 AND project_id=$2 AND user_id=$3',[f.tenant,f.project,f.actor,f.subject]);
  const actorAuth={...auth,userId:f.actor as UUID};
  caps=await resolveProjectCapabilities(db,actorAuth,project);
  assert.equal(caps.operationalRole,null); assert.equal(caps.canAdminister,false); checks++;
  await assert.rejects(getProjectRole(db,actorAuth.tenantId,project,actorAuth.userId,1),{type:'ForbiddenError'}); checks++;
  const discovery=await handleGetProjects(new NextRequest('http://localhost/api/projects'),{requireAuth:()=>auth,assertActiveSession,db});
  assert.equal(discovery.status,200); assert.deepEqual((await discovery.json()).projects,[],'disabled project is absent from operational discovery'); checks++;
  await db.query('UPDATE project_memberships SET access_disabled_at=NULL,access_disabled_by=NULL WHERE project_id=$1 AND user_id=$2',[f.project,f.subject]);
  await db.query('DELETE FROM tenant_memberships WHERE tenant_id=$1 AND user_id=$2',[f.tenant,f.subject]);
  await db.query("INSERT INTO acting_grants(tenant_id,project_id,user_id,role,trigger,granted_by,granted_reason,created_at) VALUES($1,$2,$3,'SURVEY_MANAGER','VACANCY','fixture','Synthetic vacancy',NOW()-interval '49 hours')",[f.tenant,f.project,f.actor]);
  const notifications=new NotificationRepository();
  let vacancies=await notifications.listVacancyEscalationCandidates(db,new Date());
  assert.equal(vacancies.length,1);
  assert.deepEqual(vacancies[0]!.recipients.map(x=>x.userId),[f.subject],'independent active admin receives escalation; revoked legacy admin does not'); checks++;
  await db.query("INSERT INTO tenant_memberships(tenant_id,user_id,role) VALUES($1,$2,'TENANT_ADMIN')",[f.tenant,f.subject]);
  vacancies=await notifications.listVacancyEscalationCandidates(db,new Date());
  assert.deepEqual(vacancies[0]!.recipients.map(x=>x.userId),[f.subject],'same Central IT/project admin is notified once'); checks++;
  console.log('Project capabilities PostgreSQL checks passed: '+checks);
}).catch(error=>{console.error(error);process.exitCode=1;});

