import {playwrightModuleURL} from '../playwright-runtime.mjs';
// Actual live Team Management entry and identity/navigation; no prototype harness.
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {randomUUID} from 'node:crypto';
assert.equal(process.env.SWR_RECONCILIATION,'1');
assert(process.env.SWR_PLAYWRIGHT_MODULE,'SWR_PLAYWRIGHT_MODULE is required before any fixture mutation');
const {chromium}=await import(playwrightModuleURL);
const f=JSON.parse(await readFile('.local-reconciliation-fixture.json','utf8'));assert.match(f.schema,/^reconcile_http_[a-f0-9]{32}$/);assert.equal(f.origin,'http://127.0.0.1:3320');
const origin='https://127.0.0.1:3321',browser=await chromium.launch({channel:'msedge',headless:true}),checks=[],captures=[],errors=[];
const check=(value,label)=>{assert(value,label);checks.push(label);};
async function login(who,width=1440){const context=await browser.newContext({viewport:{width,height:1000},ignoreHTTPSErrors:true,reducedMotion:'reduce'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin+'/login?returnTo='+encodeURIComponent('/projects/'+f.project));await page.getByLabel('Tenant ID',{exact:true}).fill(f.tenant);await page.getByLabel('Email',{exact:true}).fill(f.people[who]+'@reconciliation.invalid');await page.getByLabel('Password',{exact:true}).fill(f.password);
 const response=page.waitForResponse(r=>r.url()===origin+'/api/auth/login'&&r.request().method()==='POST');await page.getByRole('button',{name:'Sign In',exact:true}).press('Enter');check((await response).status()===200,who+' actual credential login');await page.waitForURL(url=>!url.pathname.startsWith('/login'));return {context,page};}
async function capture(page,name){await page.waitForLoadState('networkidle');check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),name+' has contained document width');const p='.local/reconciliation-captures/'+name+'.png';await page.screenshot({path:p});captures.push(p);}
try{
 for(const who of ['requester','viewer','superintendent','chief','instrument','tenantOnly']){const {context,page}=await login(who,who==='viewer'?390:1440);await page.goto(origin+'/projects/'+f.project);check(await page.locator('main').count()>0,who+' current authenticated project navigation');await capture(page,'role-'+who);await context.close();}
 const {context,page}=await login('manager');await page.goto(origin+'/projects/'+f.project+'/survey/teams');
 const launcher=page.getByRole('button',{name:'Open Visual Editor',exact:true});await launcher.waitFor();await launcher.press('Enter');await page.locator('.org-chart').waitFor();
 check(await page.locator('[data-person="'+f.people.instrument+'"]').count()===1,'Live entry shows current fixture Instrument Man');check(await page.getByText('Jordan Morgan',{exact:true}).count()===0,'Live chart contains no synthetic demo default');
 await capture(page,'live-chart-light-desktop');
 await page.locator('[data-person="'+f.people.instrument+'"] .org-card-actions button').click();
 await page.getByRole('dialog').last().getByRole('button',{name:/Acceptance otherChief/}).click();await page.getByRole('heading',{name:'Review Visual Crew Reassignment',exact:true}).waitFor();
 await page.getByRole('button',{name:'Cancel proposed move',exact:true}).click();check(await page.getByRole('heading',{name:'Review Visual Crew Reassignment',exact:true}).count()===0,'Live visual cancellation discards proposal');
 const teams=origin+'/api/projects/'+f.project+'/survey/teams',moves=origin+'/api/projects/'+f.project+'/survey/reorganization';
 const team=(await (await context.request.get(teams+'?teamId='+f.team)).json()).team;
 const teamSave=await context.request.post(teams,{headers:{'Idempotency-Key':randomUUID()},data:{teamId:f.team,expectedVersion:team.rowVersion,name:team.name,areaId:team.areaId,areaIds:team.areas.map(a=>a.id),leadUserId:team.lead.userId,memberIds:[...new Set([...team.members.map(m=>m.userId),f.people.otherChief,f.people.otherInstrument])]}});check(teamSave.status()===200,'Owned destination Chief is explicitly enrolled in named team');
 await page.getByRole('button',{name:'Reload hierarchy',exact:true}).click();await page.locator('[data-person="'+f.people.instrument+'"] .org-card-actions button').waitFor();
 await page.locator('[data-person="'+f.people.instrument+'"] .org-card-actions button').click();await page.getByRole('dialog').last().getByRole('button',{name:/Acceptance otherChief/}).click();
 await page.getByRole('heading',{name:'Review Visual Crew Reassignment',exact:true}).waitFor();const review=page.locator('dialog.administration-dialog').filter({has:page.getByRole('heading',{name:'Review Visual Crew Reassignment',exact:true})});await review.getByLabel(/^Destination Named Team/).selectOption(f.team);await review.getByRole('button',{name:'Preview Manpower Move',exact:true}).click();await review.getByLabel(/^Reason \(10/).fill('Owned visual review and exact retry witness');await review.getByRole('checkbox').check();
 const attempts=[];let lost=false;await page.route(moves,async route=>{if(route.request().method()!=='POST')return route.continue();attempts.push({body:route.request().postData(),key:route.request().headers()['idempotency-key']});if(!lost){lost=true;const actual=await route.fetch();assert.equal(actual.status(),200,await actual.text());return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'Synthetic lost reply after actual commit'}})});}return route.continue();});
 await review.getByRole('button',{name:'Confirm Manpower Move',exact:true}).click();await review.getByRole('button',{name:'Retry Unchanged Move',exact:true}).waitFor();check(await page.getByRole('button',{name:'Close organization chart',exact:true}).isDisabled(),'Uncertain actual commit holds outer chart');await review.getByRole('button',{name:'Retry Unchanged Move',exact:true}).click();await page.getByRole('heading',{name:'Review Visual Crew Reassignment',exact:true}).waitFor({state:'hidden'});await page.locator('[data-person="'+f.people.instrument+'"]').waitFor();check(attempts.length===2&&JSON.stringify(attempts[0])===JSON.stringify(attempts[1]),'Actual visual commit retries exact reviewed payload and key');await page.unroute(moves);
 const graph=await (await context.request.get(origin+'/api/projects/'+f.project+'/survey/organization')).json();check(graph.staffing.find(s=>s.partyChiefId===f.people.otherChief).instrumentMen.some(m=>m.userId===f.people.instrument),'Live graph reflects committed crew reassignment');
 await page.locator('[data-person="'+f.people.otherInstrument+'"] .org-card-actions button').click();await page.getByRole('dialog').last().getByRole('button',{name:/^Acceptance chief /}).click();await page.getByRole('heading',{name:'Review Visual Crew Reassignment',exact:true}).waitFor();await review.getByLabel(/^Destination Named Team/).selectOption(f.team);await review.getByRole('button',{name:'Preview Manpower Move',exact:true}).click();await review.getByLabel(/^Reason \(10/).fill('Owned stale review must refuse current staffing change');await review.getByRole('checkbox').check();
 const changed=(await (await context.request.get(teams+'?teamId='+f.team)).json()).team;const changedSave=await context.request.post(teams,{headers:{'Idempotency-Key':randomUUID()},data:{teamId:f.team,expectedVersion:changed.rowVersion,name:changed.name+' current',areaId:changed.areaId,areaIds:changed.areas.map(a=>a.id),leadUserId:changed.lead.userId,memberIds:changed.members.map(m=>m.userId)}});check(changedSave.status()===200,'Separate governed team save invalidates reviewed staffing snapshot');await review.getByRole('button',{name:'Confirm Manpower Move',exact:true}).click();await review.getByText('Staffing or work changed.',{exact:false}).waitFor();check(await review.getByRole('button',{name:'Confirm Manpower Move',exact:true}).isDisabled(),'Stale visual review blocks further writes');await review.getByRole('button',{name:'Reload Current Movement Choices',exact:true}).click();await page.getByRole('heading',{name:'Review Visual Crew Reassignment',exact:true}).waitFor({state:'hidden'});await page.locator('.org-chart').waitFor();
 await page.getByRole('button',{name:'Close organization chart',exact:true}).press('Enter');check(await launcher.evaluate(e=>e===document.activeElement),'Live entry returns keyboard focus');
 // Color/theme persisted through existing account API; no product design change.
 const appearance=await context.request.put(origin+'/api/account/appearance',{headers:{'Idempotency-Key':randomUUID()},data:{scope:'PERSONAL',mode:'DARK'}});check(appearance.status()===200,'Manager selects Dark through current appearance API; got '+appearance.status());await page.reload();await page.setViewportSize({width:390,height:1000});await launcher.click();await page.locator('.org-chart').waitFor();await page.getByRole('button',{name:'Dark Theme',exact:true}).click();await capture(page,'live-chart-dark-mobile');await page.getByRole('button',{name:'Close organization chart',exact:true}).click();
 await page.goto(origin+'/projects/'+f.archivedProject+'/survey/teams');const readOnly=page.getByRole('button',{name:/Open Survey Organization Chart \(Read-Only\)/});await readOnly.waitFor();await readOnly.click();await page.locator('.org-chart').waitFor();check(await page.locator('.org-card-actions').count()===0,'Archived live chart provides no move controls');await capture(page,'archived-chart-dark-mobile');await context.close();
 const styling=await login('manager');for(const mode of ['LIGHT','DARK']){const response=await styling.context.request.put(origin+'/api/account/appearance',{headers:{'Idempotency-Key':randomUUID()},data:{scope:'PERSONAL',mode}});assert.equal(response.status(),200);for(const width of [1440,390])for(const [label,path]of [['home','/home'],['operations','/survey/operations'],['review','/survey/review']]){await styling.page.setViewportSize({width,height:1000});await styling.page.goto(origin+'/projects/'+f.project+path);await styling.page.locator('main').waitFor();await capture(styling.page,'alignment-'+label+'-'+mode.toLowerCase()+'-'+width);}}await styling.context.close();
 check(errors.length===0,'No browser page errors');
 await writeFile('audits/alpha1-reconciliation/browser-acceptance.json',JSON.stringify({checks,captureNames:captures.map(p=>p.split('/').at(-1)),fixtureKind:'fresh owned synthetic',entry:'actual /projects/[projectId]/survey/teams',limits:['Edge desktop/mobile viewports; other engines and physical touch devices unverified.']},null,2)+'\n');
 console.log('Live browser acceptance: '+checks.length+' named checks');
}finally{await browser.close();}
