import {moveWorkforceMember} from '../../src/modules/tenancy/application/survey-workforce';
import {reorganizeSurvey} from '../../src/modules/tenancy/application/reorganize-survey';
import {SurveyReorganizationPgRepository} from '../../src/modules/tenancy/infrastructure/survey-reorganization.repository';
import {buildVisibilityClause} from '../../src/lib/ticket-visibility-clause';
import {requireSurveyReviewAuthority} from '../../src/lib/survey-review-authority';
import {approveTicket} from '../../src/modules/ticket/application/approve-ticket';
import {rejectTicket} from '../../src/modules/ticket/application/reject-ticket';
import {proposeRejection,readRejectionProposal} from '../../src/modules/ticket/application/rejection-proposal';
import {requesterCancel} from '../../src/modules/ticket/application/requester-cancel';
import {returnTicketForCorrection} from '../../src/modules/ticket/application/return-ticket-for-correction';
import {assertAssignmentScope} from '../../src/modules/ticket/application/assignment-scope';
import {delegateWork,delegationTeams} from '../../src/modules/ticket/application/delegate-work';
import {assignTicket} from '../../src/modules/ticket/application/assign-ticket';
import {assignmentChoices} from '../../src/modules/ticket/application/assignment-choices';
import {TicketRepository} from '../../src/modules/ticket/infrastructure/ticket.repository';
import {createSurveyArea} from '../../src/modules/tenancy/application/create-survey-area';
import {SurveyAreasPgRepository} from '../../src/modules/tenancy/infrastructure/survey-areas.repository';
import {notifySurveySubmission} from '../../src/modules/ticket/application/survey-submission-notifications';
import {SurveyWorkforcePgRepository} from '../../src/modules/tenancy/infrastructure/survey-workforce.repository';
import {readSurveyInbox} from '../../src/modules/notification/application/survey-inbox';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {Pool} from 'pg';
import {SurveyTeamsPgRepository} from '../../src/modules/tenancy/infrastructure/survey-teams.repository';
import {saveSurveyTeam,deactivateSurveyTeam,readSurveyTeams,type TeamActor} from '../../src/modules/tenancy/application/survey-teams';
import type {UUID} from '../../src/shared/types';

async function main(){
 const url=new URL(process.env.DATABASE_URL??'');
 assert.equal(process.env.SWR_SURVEY_WORKFLOW_TEST,'1');
 assert.equal(url.hostname,'127.0.0.1');assert.equal(url.port,'15495');assert.equal(url.pathname,'/swr_survey_workflow');
 const pool=new Pool({connectionString:url.href});const db=await pool.connect();
 try{
  await db.query('BEGIN');
  const ids=Array.from({length:10},()=>randomUUID() as UUID);
  const superintendent=randomUUID() as UUID, instrument=randomUUID() as UUID;
  const [tenant,project,company,manager,chief,otherChief,level,areaA,areaB,requester]=ids as [UUID,UUID,UUID,UUID,UUID,UUID,UUID,UUID,UUID,UUID];
  await db.query("INSERT INTO tenants(id,name) VALUES($1,'Owned survey test')",[tenant]);
  await db.query("INSERT INTO companies(id,tenant_id,name,type) VALUES($1,$2,'GC','GC')",[company,tenant]);
  await db.query("INSERT INTO projects(id,tenant_id,name,status,crew_build) VALUES($1,$2,'Owned project','ACTIVE','FULL')",[project,tenant]);
  for(const [user,role] of [[manager,'SURVEY_MANAGER'],[chief,'PARTY_CHIEF'],[otherChief,'PARTY_CHIEF'],[requester,'REQUESTER'],[superintendent,'SURVEY_SUPERINTENDENT'],[instrument,'INSTRUMENT_MAN']]){
   await db.query("INSERT INTO users(id,tenant_id,company_id,email,name,password_hash) VALUES($1,$2,$3,$4,$5,'not-a-login')",[user,tenant,company,`${user}@example.test`,role]);
   await db.query('INSERT INTO project_memberships(project_id,user_id,role) VALUES($1,$2,$3)',[project,user,role]);
  }
  await db.query("INSERT INTO aor_levels(id,tenant_id,project_id,depth,label) VALUES($1,$2,$3,0,'Area')",[level,tenant,project]);
  for(const [area,name] of [[areaA,'Area A'],[areaB,'Area B']])await db.query('INSERT INTO aor_nodes(id,tenant_id,project_id,level_id,name,code) VALUES($1,$2,$3,$4,$5,$5)',[area,tenant,project,level,name]);
  const repo=new SurveyTeamsPgRepository();const actor:TeamActor={tenantId:tenant,projectId:project,actorId:manager,actorRole:'SURVEY_MANAGER',sessionVersion:1};
  const areasRepo=new SurveyAreasPgRepository();
  const newArea=await createSurveyArea(areasRepo,db,actor,{name:' Area C ',code:' area-c '});
  assert.equal(newArea.name,'Area C');
  assert.equal((await repo.areas(db,tenant,project,{search:'Area C',limit:10,offset:0})).data[0]?.id,newArea.id,'Created Area immediately appears in team choices');
  assert.equal((await db.query('SELECT level_id,code FROM aor_nodes WHERE id=$1',[newArea.id])).rows[0].level_id,level,'Uses existing requester Area hierarchy');
  await assert.rejects(createSurveyArea(areasRepo,db,actor,{name:'area c',code:'OTHER'}),/already uses/);
  await assert.rejects(createSurveyArea(areasRepo,db,actor,{name:'Different name',code:'AREA-C'}),/already uses/);
  await assert.rejects(createSurveyArea(areasRepo,db,{...actor,actorId:superintendent,actorRole:'SURVEY_SUPERINTENDENT'},{name:'Forbidden',code:'NO'}),/Only the Survey Manager/);
  await assert.rejects(createSurveyArea(areasRepo,db,{...actor,sessionVersion:99},{name:'Stale',code:'STALE'}),/assignment or session has changed/);
  await assert.rejects(createSurveyArea(areasRepo,db,{...actor,projectId:randomUUID() as UUID},{name:'Foreign',code:'FOREIGN'}),/Project not found/);
  const input={teamId:null,expectedVersion:null,name:'Team 1',areaId:areaA,areaIds:[areaA,areaB],leadUserId:superintendent,memberIds:[chief,superintendent,instrument]};
  const saved=await saveSurveyTeam(repo,db,actor,input);
  assert.deepEqual((await repo.team(db,tenant,project,saved.teamId))!.areas!.map(a=>a.name),['Area A','Area B']);
  assert.equal((await repo.list(db,tenant,project,{search:'Area B',limit:10,offset:0})).total,1);
  const destination=await saveSurveyTeam(repo,db,actor,{...input,name:'Team 2',leadUserId:otherChief,memberIds:[otherChief]});
  assert.equal((await repo.list(db,tenant,project,{search:'Area B',limit:10,offset:0})).total,2,'Teams may overlap Areas');
  assert.equal((await repo.personnel(db,tenant,project,{search:'',limit:10,offset:0})).data.some(p=>p.userId===requester),false);
  await saveSurveyTeam(repo,db,actor,{...input,teamId:saved.teamId,expectedVersion:1,areaIds:[areaA]});
  assert.equal((await db.query('SELECT deactivated_at IS NOT NULL AS removed FROM survey_team_areas WHERE team_id=$1 AND area_id=$2',[saved.teamId,areaB])).rows[0].removed,true);
  await saveSurveyTeam(repo,db,actor,{...input,teamId:saved.teamId,expectedVersion:2});
  assert.equal((await repo.team(db,tenant,project,saved.teamId))!.areas!.length,2);
  const workforce=new SurveyWorkforcePgRepository();
  const ss={...actor,actorId:superintendent,actorRole:'SURVEY_SUPERINTENDENT' as const};
  assert.equal(await workforce.sameTeam(db,ss,[superintendent,chief]),true);
  assert.equal(await workforce.sameTeam(db,ss,[chief,otherChief]),false,'Cross-team reassignment is forbidden even within one project');
  const ssPeople=await workforce.personnel(db,ss,{search:'',limit:10,offset:0});
  assert.deepEqual(ssPeople.data.map(p=>p.userId).sort(),[chief,instrument].sort(),'Named team establishes assigned personnel without separate reporting grants');
  assert.equal((await workforce.person(db,ss,instrument))!.partyChiefId,null);
  await db.query('SAVEPOINT unassigned_transfer');
  {
    const transfers=new SurveyReorganizationPgRepository(),selection={kind:'INSTRUMENT_MAN' as const,instrumentManId:instrument,partyChiefId:otherChief,destinationTeamId:destination.teamId};
    const preview=await transfers.preview(db,actor,selection);
    assert.deepEqual(preview.blockers,[],'Team member without a Chief can be transferred');
    await reorganizeSurvey(transfers,db,actor,{...selection,snapshot:preview.snapshot,reason:'Assign available surveyor to crew',confirmed:true});
    assert.equal(await transfers.rosterChief(db,tenant,project,instrument),otherChief);
    await db.query('ROLLBACK TO SAVEPOINT unassigned_transfer');
    await db.query('UPDATE survey_team_members SET deactivated_at=now() WHERE project_id=$1 AND user_id=$2',[project,instrument]);
    const available=await transfers.preview(db,actor,selection);
    assert.deepEqual(available.blockers,[],'Project surveyor without a team can join the destination team');
    assert(available.summary.some(line=>line.includes('unassigned personnel pool')));
    await reorganizeSurvey(transfers,db,actor,{...selection,snapshot:available.snapshot,reason:'Place unassigned surveyor on team',confirmed:true});
    assert.equal(await transfers.rosterChief(db,tenant,project,instrument),otherChief);
    assert.equal((await db.query('SELECT count(*)::int n FROM survey_team_members WHERE project_id=$1 AND user_id=$2 AND deactivated_at IS NULL',[project,instrument])).rows[0].n,1);
  }
  await db.query('ROLLBACK TO SAVEPOINT unassigned_transfer');
  await db.query('SAVEPOINT initial_assignment');
  await moveWorkforceMember(workforce,db,ss,{instrumentManId:instrument,partyChiefId:chief,expectedSnapshot:ssPeople.snapshotToken});
  assert.equal((await workforce.person(db,ss,instrument))!.partyChiefId,chief,'Superintendent can assign an unassigned team Instrument Man');
  assert.equal((await readSurveyInbox(db,actor,0)).messages.length,1);
  const pc={...actor,actorId:chief,actorRole:'PARTY_CHIEF' as const};
  assert.deepEqual((await workforce.personnel(db,pc,{search:'',limit:10,offset:0})).data.map(p=>p.userId),[instrument]);
  const transfers=new SurveyReorganizationPgRepository();
  const move={kind:'INSTRUMENT_MAN' as const,instrumentManId:instrument,partyChiefId:otherChief,destinationTeamId:destination.teamId};
  await assert.rejects(transfers.authorize(db,ss),/Only the Survey Manager/);
  const transferPreview=await transfers.preview(db,actor,move);
  assert.deepEqual(transferPreview.blockers,[],'Manager can transfer out of a Superintendent-led team');
  await reorganizeSurvey(transfers,db,actor,{...move,snapshot:transferPreview.snapshot,reason:'Move to the destination crew',confirmed:true});
  assert.equal((await db.query('SELECT party_chief_id FROM crew_rosters WHERE project_id=$1 AND instrument_man_id=$2',[project,instrument])).rows[0].party_chief_id,otherChief);
  assert.equal((await repo.team(db,tenant,project,saved.teamId))!.members.some(m=>m.userId===instrument),false,'Source roster removes transferred Instrument Man');
  assert.equal((await repo.team(db,tenant,project,saved.teamId))!.areas!.length,2,'Transfer preserves all source team Areas');
  assert.equal((await db.query('SELECT count(*)::int n FROM survey_team_members WHERE project_id=$1 AND user_id=$2 AND deactivated_at IS NULL',[project,instrument])).rows[0].n,1,'Transferred person has one current team');
  assert.equal((await workforce.personnel(db,pc,{search:'',limit:10,offset:0})).data.some(p=>p.userId===instrument),false,'Former Chief no longer manages transferred Instrument Man');
  await assert.rejects(reorganizeSurvey(transfers,db,actor,{...move,snapshot:transferPreview.snapshot,reason:'Repeat the old reviewed move',confirmed:true}),/changed/);
  await db.query('ROLLBACK TO SAVEPOINT initial_assignment');
  await db.query('SAVEPOINT notification_rollback');
  await workforce.record(db,ss,{action:'reorganize-roster',instrumentManName:'Alex',partyChiefName:'Chief A'});
  const inbox=await readSurveyInbox(db,actor,0);
  assert.equal(inbox.messages.length,1);assert.match(inbox.messages[0]!.message,/assigned Alex to Chief A/);
  assert.equal((await readSurveyInbox(db,ss,0)).messages.length,0,'Only addressed recipients see the update');
  assert.equal((await readSurveyInbox(db,{...actor,sessionVersion:99},0)).messages.length,0,'Stale sessions cannot read messages');
  await db.query('ROLLBACK TO SAVEPOINT notification_rollback');
  assert.equal((await readSurveyInbox(db,actor,0)).messages.length,0,'Roster transaction rollback removes its notification');
  const ticket=randomUUID() as UUID;
  await db.query("INSERT INTO tickets(id,tenant_id,project_id,company_id,requester_id,workflow_variant,status,craft,description,aor_node_id,ticket_type,requested_date) VALUES($1,$2,$3,$4,$5,'STANDARD_APPROVAL','SUBMITTED','Survey','Owned submission',$6,'LAYOUT',CURRENT_DATE)",[ticket,tenant,project,company,requester,areaB]);
  await notifySurveySubmission(db,tenant,ticket,requester);
  await notifySurveySubmission(db,tenant,ticket,requester);
  async function visibleTo(userId:UUID,role:'SURVEY_SUPERINTENDENT'|'PARTY_CHIEF'|'INSTRUMENT_MAN') {
    const clause=buildVisibilityClause({actorId:userId,actorRole:role,projectId:project,companyId:company},4);
    return (await db.query(`SELECT t.id FROM tickets t WHERE t.tenant_id=$1 AND t.project_id=$2 AND t.id=$3 ${clause.sql}`,[tenant,project,ticket,...clause.params])).rows.length===1;
  }
  assert.equal(await visibleTo(superintendent,'SURVEY_SUPERINTENDENT'),true,'Team lead opens covered request without separate Area grant');
  assert.equal(await visibleTo(chief,'PARTY_CHIEF'),true,'Team Chief opens covered request before crew assignment');
  assert.equal(await visibleTo(instrument,'INSTRUMENT_MAN'),true,'Team Instrument Man opens covered request notification');
  await db.query('UPDATE survey_team_members SET deactivated_at=NOW() WHERE team_id=$1 AND user_id=$2',[saved.teamId,instrument]);
  assert.equal(await visibleTo(instrument,'INSTRUMENT_MAN'),false,'Coverage is rechecked after team membership removal');
  await db.query('UPDATE survey_team_members SET deactivated_at=NULL WHERE team_id=$1 AND user_id=$2',[saved.teamId,instrument]);
  await db.query('UPDATE tickets SET aor_node_id=$2 WHERE id=$1',[ticket,newArea.id]);
  assert.equal(await visibleTo(chief,'PARTY_CHIEF'),false,'Uncovered Area is not exposed');
  await db.query('UPDATE tickets SET aor_node_id=$2,status=\'DRAFT\' WHERE id=$1',[ticket,areaB]);
  assert.equal(await visibleTo(chief,'PARTY_CHIEF'),false,'Requester draft remains private despite team coverage');
  await db.query('UPDATE tickets SET status=\'SUBMITTED\' WHERE id=$1',[ticket]);
  const notices=await db.query('SELECT recipient_id FROM survey_notifications WHERE project_id=$1',[project]);
  assert.deepEqual(notices.rows.map(p=>p.recipient_id).sort(),[manager,superintendent,chief,otherChief,instrument].sort(),'Manager and every covering team member notified exactly once');
  assert.equal((await db.query('SELECT count(*)::int AS n FROM notification_outbox WHERE ticket_id=$1',[ticket])).rows[0].n,5);
  const chiefInboxActor={...actor,actorId:chief,actorRole:'PARTY_CHIEF' as const};
  assert((await readSurveyInbox(db,chiefInboxActor,0)).messages.some(message=>message.ticketId===ticket),'Covered request notification has a current authorized target');
  await db.query('SAVEPOINT notification_target');
  await db.query('UPDATE survey_team_members SET deactivated_at=now() WHERE tenant_id=$1 AND project_id=$2 AND user_id=$3',[tenant,project,chief]);
  assert((await readSurveyInbox(db,chiefInboxActor,0)).messages.every(message=>message.ticketId===null),'Lost team coverage removes the request link from retained notices');
  await db.query('ROLLBACK TO SAVEPOINT notification_target');
  await db.query('UPDATE project_memberships SET access_disabled_at=NOW(),access_disabled_by=$3 WHERE project_id=$1 AND user_id=$2',[project,otherChief,manager]);
  await db.query('UPDATE tickets SET return_cycle=1 WHERE id=$1',[ticket]);
  await notifySurveySubmission(db,tenant,ticket,requester);
  assert.equal((await db.query("SELECT count(*)::int AS n FROM survey_notifications WHERE project_id=$1 AND event_key LIKE '%:submitted:1'",[project])).rows[0].n,4,'Resubmission excludes disabled members');
  const led=await readSurveyTeams(repo,db,ss,{search:'',limit:10,offset:0});
  assert('data' in led);assert.deepEqual(led.data.map(team=>team.id),[saved.teamId],'Superintendent lists only teams they lead');
  const ownEdit={...input,teamId:saved.teamId,expectedVersion:3,name:'Superintendent updated team'};
  await assert.rejects(saveSurveyTeam(repo,db,ss,{...ownEdit,memberIds:[...input.memberIds,otherChief]}),/outside your team/);
  await assert.rejects(saveSurveyTeam(repo,db,ss,{...ownEdit,areaIds:[areaA]}),/Area coverage/);
  await saveSurveyTeam(repo,db,ss,ownEdit);
  assert.equal((await repo.team(db,tenant,project,saved.teamId))!.name,ownEdit.name);
  assert.equal((await db.query("SELECT count(*)::int AS n FROM survey_notifications WHERE tenant_id=$1 AND recipient_id=$2 AND message LIKE '%Superintendent updated team%'",[tenant,manager])).rows[0].n,1,'Team edit and Manager notice commit together');
  await assert.rejects(saveSurveyTeam(repo,db,{...ss,sessionVersion:99},{...ownEdit,expectedVersion:4}),/session has changed/);
  const reviewScope={tenantId:tenant,projectId:project,aorNodeId:areaB};
  assert.equal((await requireSurveyReviewAuthority(db,reviewScope,{actorId:chief,actorRole:'PARTY_CHIEF'})).kind,'TEAM_COVERAGE');
  assert.equal((await requireSurveyReviewAuthority(db,reviewScope,{actorId:superintendent,actorRole:'SURVEY_SUPERINTENDENT'})).kind,'TEAM_COVERAGE');
  await assert.rejects(requireSurveyReviewAuthority(db,{...reviewScope,aorNodeId:newArea.id},{actorId:chief,actorRole:'PARTY_CHIEF'}),/does not cover/);
  await assert.rejects(requireSurveyReviewAuthority(db,reviewScope,{actorId:instrument,actorRole:'INSTRUMENT_MAN'}),/Survey review requires/);
  await assert.rejects(requireSurveyReviewAuthority(db,reviewScope,{actorId:otherChief,actorRole:'PARTY_CHIEF'}),/does not cover/);
  const tickets=new TicketRepository();
  const ownCrew={partyChiefId:chief,instrumentManId:instrument,previousChiefId:null,previousInstrumentId:null};
  await assertAssignmentScope(db,reviewScope,{actorId:superintendent,actorRole:'SURVEY_SUPERINTENDENT'},ownCrew);
  await assert.rejects(assertAssignmentScope(db,reviewScope,{actorId:superintendent,actorRole:'SURVEY_SUPERINTENDENT'},{...ownCrew,partyChiefId:otherChief}),/Only the Survey Manager/);
  await assert.rejects(assertAssignmentScope(db,reviewScope,{actorId:superintendent,actorRole:'SURVEY_SUPERINTENDENT'},{...ownCrew,previousChiefId:otherChief}),/Only the Survey Manager/);
  await assertAssignmentScope(db,reviewScope,{actorId:manager,actorRole:'SURVEY_MANAGER'},{...ownCrew,partyChiefId:otherChief});
  await assert.rejects(assertAssignmentScope(db,reviewScope,{actorId:chief,actorRole:'PARTY_CHIEF'},{...ownCrew,previousChiefId:chief}),/assigned to you/);
  await db.query('SAVEPOINT assignment_crew');
  await db.query('INSERT INTO crew_rosters(tenant_id,project_id,party_chief_id,instrument_man_id) VALUES($1,$2,$3,$4)',[tenant,project,chief,instrument]);
  await assertAssignmentScope(db,reviewScope,{actorId:chief,actorRole:'PARTY_CHIEF'},{...ownCrew,previousChiefId:chief});
  await assert.rejects(assertAssignmentScope(db,reviewScope,{actorId:otherChief,actorRole:'PARTY_CHIEF'},{...ownCrew,partyChiefId:otherChief,previousChiefId:otherChief}),/assigned to you/);
  await db.query('ROLLBACK TO SAVEPOINT assignment_crew');
  assert.equal((await approveTicket(tickets,db,{tenantId:tenant,ticketId:ticket,actorId:chief,actorRole:'PARTY_CHIEF'})).status,'APPROVED','Responsible Chief approves submitted request');
  assert.equal((await db.query("SELECT payload->'reviewAuthority'->>'kind' AS kind FROM ticket_events WHERE ticket_id=$1 AND event_type='ticket.approved'",[ticket])).rows[0].kind,'TEAM_COVERAGE','Approval retains team authority evidence');
  await db.query('SAVEPOINT delegation_case');
  const delegateActor={tenantId:tenant,ticketId:ticket,actorId:manager,actorRole:'SURVEY_MANAGER' as const};
  assert((await delegationTeams(db,tenant,ticket)).some(team=>team.id===saved.teamId));
  await assert.rejects(delegateWork(tickets,db,{...delegateActor,actorId:superintendent,actorRole:'SURVEY_SUPERINTENDENT'},saved.teamId),/Only the Survey Manager/);
  await assert.rejects(delegateWork(tickets,db,delegateActor,randomUUID() as UUID),/Choose an active team/);
  const delegated=await delegateWork(tickets,db,delegateActor,saved.teamId);
  assert.deepEqual((await assignmentChoices(db,{...delegateActor,actorId:superintendent,actorRole:'SURVEY_SUPERINTENDENT'})).map(person=>person.id).sort(),[chief,instrument].sort(),'Delegated Superintendent choices contain only own eligible crew');
  assert((await assignmentChoices(db,delegateActor)).every(person=>person.role==='PARTY_CHIEF'||person.role==='INSTRUMENT_MAN'),'Manager assignment choices exclude other departments');
  assert.equal(delegated.status,'AWAITING_CREW');
  assert.equal((await db.query('SELECT status FROM tickets WHERE id=$1',[ticket])).rows[0].status,'APPROVED','Delegation does not start field work');
  assert.deepEqual((await db.query('SELECT recipient_id FROM survey_notifications WHERE event_key=$1',[`delegation:${delegated.delegationId}`])).rows.map(row=>row.recipient_id).sort(),[superintendent,chief,instrument].sort());
  await delegateWork(tickets,db,delegateActor,saved.teamId);
  assert.equal((await db.query('SELECT count(*)::int n FROM survey_work_delegations WHERE ticket_id=$1 AND ended_at IS NULL',[ticket])).rows[0].n,1);
  assert.equal((await db.query('SELECT end_reason FROM survey_work_delegations WHERE id=$1',[delegated.delegationId])).rows[0].end_reason,'REDELEGATED','Prior delegation history retained');
  assert.equal((await assignTicket(tickets,db,{...delegateActor,actorId:superintendent,actorRole:'SURVEY_SUPERINTENDENT',assignedPartyChiefId:chief,assignedInstrumentManId:instrument,surveyLeadId:superintendent})).status,'ASSIGNED','Delegated leader selects own team crew');
  assert.deepEqual((await db.query("SELECT recipient_id FROM survey_notifications WHERE ticket_id=$1 AND title='Work assigned to you'",[ticket])).rows.map(row=>row.recipient_id).sort(),[chief,instrument].sort(),'Only the assigned Chief and Instrument Man receive crew handoff notices');
  assert.equal((await db.query('SELECT count(*)::int n FROM survey_work_delegations WHERE ticket_id=$1 AND ended_at IS NULL',[ticket])).rows[0].n,0,'Crew selection closes awaiting-crew delegation');
  await db.query('ROLLBACK TO SAVEPOINT delegation_case');
  const rejected=randomUUID() as UUID;
  await db.query("INSERT INTO tickets(id,tenant_id,project_id,company_id,requester_id,workflow_variant,status,craft,description,aor_node_id,ticket_type,requested_date) VALUES($1,$2,$3,$4,$5,'STANDARD_APPROVAL','SUBMITTED','Survey','Rejection test',$6,'LAYOUT',CURRENT_DATE)",[rejected,tenant,project,company,requester,areaB]);
  const proposer={tenantId:tenant,ticketId:rejected,actorId:chief,actorRole:'PARTY_CHIEF' as const};
  const proposal=await proposeRejection(db,proposer,'Outside survey scope');
  assert.equal((await db.query('SELECT status FROM tickets WHERE id=$1',[rejected])).rows[0].status,'SUBMITTED','Proposal is not a final rejection');
  assert.deepEqual((await db.query('SELECT recipient_id FROM survey_notifications WHERE event_key=$1',[`rejection-proposal:${proposal.id}`])).rows.map(row=>row.recipient_id).sort(),[manager,superintendent].sort(),'Only Manager and covering leadership receive proposal notice');
  await assert.rejects(proposeRejection(db,proposer,'Repeated proposal'),/already awaits/);
  await assert.rejects(approveTicket(tickets,db,proposer),/awaits a Superintendent/);
  await db.query('SAVEPOINT decline_proposal');
  await db.query('UPDATE project_memberships SET access_disabled_at=now(),access_disabled_by=$3 WHERE project_id=$1 AND user_id=$2',[project,chief,manager]);
  await approveTicket(tickets,db,{...proposer,actorId:superintendent,actorRole:'SURVEY_SUPERINTENDENT'});
  assert.equal((await db.query('SELECT count(*)::int n FROM survey_notifications WHERE event_key=$1',[`rejection-outcome:${proposal.id}`])).rows[0].n,0,'Removed Chief receives no new outcome notice');
  await db.query('ROLLBACK TO SAVEPOINT decline_proposal');
  assert.equal((await approveTicket(tickets,db,{...proposer,actorId:superintendent,actorRole:'SURVEY_SUPERINTENDENT'})).status,'APPROVED','Leadership may decline the proposal and approve instead');
  assert.equal((await db.query('SELECT outcome FROM survey_rejection_proposals WHERE id=$1',[proposal.id])).rows[0].outcome,'DECLINED');
  assert.deepEqual((await db.query('SELECT recipient_id,message FROM survey_notifications WHERE event_key=$1',[`rejection-outcome:${proposal.id}`])).rows.map(row=>[row.recipient_id,row.message.includes('declined')]),[[chief,true]],'Declined proposal outcome reaches only its Chief');
  await db.query('ROLLBACK TO SAVEPOINT decline_proposal');
  await db.query('SAVEPOINT superseded_proposal');
  await requesterCancel(tickets,db,{...proposer,actorId:requester,actorRole:'REQUESTER'});
  assert.equal(await readRejectionProposal(db,tenant,rejected),null,'Requester cancellation clears pending decision');
  assert.equal((await db.query('SELECT outcome FROM survey_rejection_proposals WHERE id=$1',[proposal.id])).rows[0].outcome,'SUPERSEDED');
  assert.equal((await db.query('SELECT message FROM survey_notifications WHERE event_key=$1',[`rejection-outcome:${proposal.id}`])).rows[0].message.includes('no longer needs a decision'),true,'Cancellation explains superseded proposal');
  await db.query('ROLLBACK TO SAVEPOINT superseded_proposal');
  await returnTicketForCorrection(tickets,db,{...proposer,actorId:superintendent,actorRole:'SURVEY_SUPERINTENDENT',reason:'Please clarify the location',origin:'INITIAL_REVIEW'});
  assert.equal(await readRejectionProposal(db,tenant,rejected),null,'Returning for correction clears pending decision');
  assert.equal((await db.query('SELECT outcome FROM survey_rejection_proposals WHERE id=$1',[proposal.id])).rows[0].outcome,'SUPERSEDED');
  await db.query('ROLLBACK TO SAVEPOINT superseded_proposal');
  await db.query('UPDATE projects SET status=\'ARCHIVED\' WHERE tenant_id=$1 AND id=$2',[tenant,project]);
  await assert.rejects(proposeRejection(db,proposer,'Closed project'),/not active/);
  await db.query('ROLLBACK TO SAVEPOINT superseded_proposal');
  assert.equal((await rejectTicket(tickets,db,{tenantId:tenant,ticketId:rejected,actorId:superintendent,actorRole:'SURVEY_SUPERINTENDENT',rejectionReason:'Outside survey scope'})).status,'REJECTED','Responsible Superintendent confirms rejection');
  assert.equal(await readRejectionProposal(db,tenant,rejected),null);
  assert.equal((await db.query('SELECT outcome FROM survey_rejection_proposals WHERE id=$1',[proposal.id])).rows[0].outcome,'CONFIRMED','Proposal outcome retained');
  assert.deepEqual((await db.query('SELECT recipient_id,message FROM survey_notifications WHERE event_key=$1',[`rejection-outcome:${proposal.id}`])).rows.map(row=>[row.recipient_id,row.message.includes('accepted')]),[[chief,true]],'Confirmed proposal outcome reaches only its Chief');
  await deactivateSurveyTeam(repo,db,actor,saved.teamId,4);
  assert.equal((await db.query('SELECT count(*)::int AS n FROM survey_team_areas WHERE team_id=$1 AND deactivated_at IS NULL',[saved.teamId])).rows[0].n,0);
  assert.equal((await db.query('SELECT count(*)::int AS n FROM survey_team_areas WHERE team_id=$1',[saved.teamId])).rows[0].n,2,'Coverage history retained');
  await db.query('SET CONSTRAINTS ALL IMMEDIATE');
  console.log('Survey team multi-Area persistence, overlap, search, personnel isolation, removal/reactivation and history checks passed.');
 }finally{await db.query('ROLLBACK');db.release();await pool.end();}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
