import type {AuthContext} from '@/lib/auth';
import type {DbClient,Page,UUID} from '@/shared/types';
import type {ProjectStatus,CrewBuild} from '@/modules/tenancy/domain/types';
import type {ProjectRole} from '@/modules/identity/domain/types';
export type CoverageIntent='TEMPORARY'|'PERMANENT';
export type ProtectedScope={tenantId:UUID;projectId:UUID};
export type ResolutionAuthority=ProtectedScope&{branch:'CENTRAL_IT'|'PROJECT_IT'|'SURVEY_MANAGER';actorId:UUID;actorMembershipId:UUID;actorAdminGrantId?:UUID;actorCompanyId:UUID;actorCompanyType:string;actorSessionVersion:number;expiresAt?:Date;project:{status:ProjectStatus;crewBuild:CrewBuild}};
export type ResolveReviewerInput={userId:UUID;grantId:UUID;replacementUserId:UUID;expectedSnapshot:string;confirmResolution:true}&({coverageMode:'reuse'}|{coverageMode:'assignAdditional';confirmAdditionalCoverage:true;coverageIntent:CoverageIntent});
export type ResolveReviewerResult={resolved:true;grantId:UUID;resolutionEventId:UUID;resolvedAt:string;replacementUserId:UUID;replacementGrantId:UUID;replacementAssignmentId:UUID;createdReviewGrant:boolean;createdIndividualAssignment:boolean};
export type ProtectedPageQuery={search:string;limit:10|25|50|100;offset:number};
export type ProtectedReadQuery={mode:'personnel';query:ProtectedPageQuery}|{mode:'obligations';userId:UUID;query:ProtectedPageQuery}|{mode:'candidates';userId:UUID;grantId:UUID;query:ProtectedPageQuery};
export type ProtectedPerson={userId:UUID;name:string;email:string;role:ProjectRole;active:boolean;responsibilityCount:number;actingCount:number};
export type ReviewerObligation={grantId:UUID;responsibility:'SURVEY_REVIEWER'|'FIELD_COORDINATOR';areaId:UUID|null;areaName:string|null;canResolve:boolean;unsupportedReason:string|null;addedCoverageIntent:CoverageIntent|null;addedIndividualAssignment:{id:UUID;coverageIntent:CoverageIntent}|null};
export type ReviewerCandidate={userId:UUID;name:string;email:string;replacementGrantId:UUID|null;replacementAssignmentId:UUID|null;canReuse:boolean;missingReviewGrant:boolean;missingIndividualAssignment:boolean};
export type ProtectedReadResult={mode:'personnel';project:ResolutionAuthority['project'];personnel:Page<ProtectedPerson>}|{mode:'obligations';project:ResolutionAuthority['project'];person:ProtectedPerson;obligations:Page<ReviewerObligation>;actingCount:number;departmentMembershipCount:number;snapshotToken:string}|{mode:'candidates';candidates:Page<ReviewerCandidate>;snapshotToken:string};
export type ResolutionPerson={id:UUID;companyId:UUID;companyType:string;role:ProjectRole|null;membershipId:UUID|null;sessionVersion:number;deactivatedAt:string|null;accessDisabledAt?:string|null};
export type ResponsibilityGrantEvidence={id:UUID;userId:UUID;areaId:UUID|null;responsibility:string;grantedBy:UUID;grantedAt:string;revokedAt:string|null};
export type IndividualAssignmentEvidence={id:UUID;userId:UUID;areaId:UUID;createdAt:string;deactivatedAt:string|null};
export type ResolutionArea={id:UUID;name:string;levelId:UUID;depth:number;parentId:UUID|null;retiredAt:string|null};
export type ResolutionContext={authority:ResolutionAuthority;subject:ResolutionPerson;replacement:ResolutionPerson;grant:ResponsibilityGrantEvidence;area:ResolutionArea|null;replacementGrant:ResponsibilityGrantEvidence|null;replacementAssignment:IndividualAssignmentEvidence|null};
export interface ProtectedObligationsRepository{
 lockResolutionContext(db:DbClient,auth:AuthContext,projectId:UUID,input:ResolveReviewerInput):Promise<ResolutionContext>;
 snapshot(db:DbClient,scope:ProtectedScope,userId:UUID):Promise<string>;
 createIndividualCoverage(db:DbClient,scope:ProtectedScope,userId:UUID,areaId:UUID,id:UUID,at:string):Promise<IndividualAssignmentEvidence>;
 createReviewCoverage(db:DbClient,scope:ProtectedScope,userId:UUID,areaId:UUID,actorId:UUID,id:UUID,at:string):Promise<ResponsibilityGrantEvidence>;
 revokeSelectedGrant(db:DbClient,scope:ProtectedScope,input:ResolveReviewerInput,actorId:UUID,at:string):Promise<boolean>;
 recordResolution(db:DbClient,context:ResolutionContext,input:ResolveReviewerInput,result:ResolveReviewerResult,coverage:{grant:ResponsibilityGrantEvidence;assignment:IndividualAssignmentEvidence},at:string):Promise<void>;
 readAuthority(db:DbClient,auth:AuthContext,projectId:UUID):Promise<ResolutionAuthority>;
 readPage(db:DbClient,scope:ProtectedScope,authority:ResolutionAuthority,query:ProtectedReadQuery):Promise<ProtectedReadResult>;
}
