"use client";
import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {apiRequest} from '@/lib/apiClient';
import {ApiClientError,getErrorMessage} from '@/lib/errors';
import {CommandOwner,FrozenCommand} from '@/lib/frozen-command';
import {useUnsavedProgress} from '@/lib/use-unsaved-progress';
import {Button,ErrorBanner,Input,SuccessBanner} from '@/components/ui';
import {Field} from '@/components/forms';
import {AdministrationDialog} from './administration-dialog';
import type {RegisteredCompany} from './company-registration';
type Directory={company:RegisteredCompany|null;companies:RegisteredCompany[];canManage:boolean};
type Body={companyId:string;expectedCompanyId:string|null;confirmed:true};
export function HomeOrganization({owner,disabled,onDone,continuation}:{owner:CommandOwner;disabled?:boolean;onDone?:()=>void;continuation?:{token:string;onReturn:(company?:RegisteredCompany)=>void}}){
 const token=continuation?.token??'home-organization';useSyncExternalStore(owner.subscribe,owner.snapshot,owner.snapshot);
 const gate=useRef(new FrozenCommand<Body>()).current;
 const [open,setOpen]=useState(!!continuation),[step,setStep]=useState(0),[data,setData]=useState<Directory>(),[search,setSearch]=useState(''),[company,setCompany]=useState<RegisteredCompany>(),[result,setResult]=useState<RegisteredCompany>();
 const [error,setError]=useState<string>(),[loading,setLoading]=useState(false),[consent,setConsent]=useState(false),[revision,setRevision]=useState(0),[,render]=useState(0);
 const blocked=!!disabled||owner.blocked(token),locked=blocked||gate.locked;useUnsavedProgress(gate.locked);
 useEffect(()=>{let active=true;setLoading(true);const timer=setTimeout(()=>void apiRequest<Directory>(`/api/tenant/home-organization?search=${encodeURIComponent(search)}`).then(value=>{if(active){setData(value);setError(undefined);}}).catch(cause=>{if(active)setError(getErrorMessage(cause,'Unable to load the home organization.'));}).finally(()=>{if(active)setLoading(false);}),200);return()=>{active=false;clearTimeout(timer);};},[search,revision]);
 function close(){if(blocked||!gate.reload())return;if(continuation){continuation.onReturn(result);return;}owner.release(token);setOpen(false);setResult(undefined);setStep(0);setConsent(false);setSearch('');setRevision(n=>n+1);}
 async function save(){if(!company||!data||!consent||blocked||!owner.claim(token))return;const frozen=gate.begin({companyId:company.id,expectedCompanyId:data.company?.id??null,confirmed:true},crypto.randomUUID());if(!frozen)return;render(n=>n+1);setError(undefined);
  try{const response=await apiRequest<{company:RegisteredCompany}>('/api/tenant/home-organization',{method:'PATCH',body:frozen.body,headers:{'Idempotency-Key':frozen.key}});gate.success();setResult(response.company);setData({...data,company:response.company});onDone?.();}catch(cause){gate.fail(cause instanceof ApiClientError?cause.status:undefined);setError(getErrorMessage(cause,'The outcome is uncertain. Retry the same designation.'));}finally{render(n=>n+1);}
 }
 return <>{!continuation&&<div className="stack">{error&&<ErrorBanner message={error}/>}<p>{loading?'Loading home organization…':data?.company?<>Tenant Company: <strong>{data.company.name}</strong></>:'No home organization has been designated.'}</p>{data?.canManage&&<Button variant="secondary" disabled={blocked||owner.snapshot()!==null||loading} onClick={()=>{if(owner.claim(token)){setOpen(true);setStep(0);setCompany(data.company??undefined);setResult(undefined);setConsent(false);}}}>{data.company?'Change Home Organization':'Set Home Organization'}</Button>}</div>}
 {open&&<AdministrationDialog title={result?'Home Organization Designated':'Designate Home Organization'} help="Tenant Company identifies the tenant’s home organization. Its General Contractor or Owner Representative type stays the same. Designation does not move employees, change memberships or grant access." step={{current:result?3:step+1,total:3,label:result?'Complete':step?'Review':'Choose Company'}} onClose={close} closeDisabled={blocked||gate.pending||!!gate.command&&!gate.stale}
 footer={result?<Button onClick={close}>{continuation?'Use Tenant Company and Return':'Close'}</Button>:<><Button variant="secondary" disabled={blocked||gate.pending||!!gate.command&&!gate.stale} onClick={close}>Cancel</Button><div className="row">{step===1&&<Button variant="secondary" disabled={locked} onClick={()=>{setStep(0);setConsent(false);}}>Back</Button>}{step===0?<Button disabled={locked||loading||!data?.canManage||!company} onClick={()=>setStep(1)}>Review Designation</Button>:<Button disabled={blocked||!consent||gate.pending||gate.stale} onClick={()=>void save()}>{gate.pending?'Saving…':gate.command?'Retry Same Designation':'Designate Home Organization'}</Button>}</div></>}>
 {error&&<ErrorBanner message={error}/>} {gate.stale&&<><p role="alert">The home organization changed. Reload and review the current designation.</p><Button variant="secondary" onClick={()=>{if(gate.reload()){setCompany(undefined);setStep(0);setConsent(false);setRevision(n=>n+1);}}}>Reload Designation</Button></>}
 {result?<SuccessBanner message={`${result.name} is now the tenant’s home organization.`}/>:step===0?<><Field label="Search Internal Companies"><Input maxLength={100} value={search} disabled={locked} onChange={e=>{setSearch(e.target.value);setCompany(undefined);}}/></Field><Field label="Home Organization"><select className="select" value={company?.id??''} disabled={locked||loading||!data?.canManage} onChange={e=>setCompany(data?.companies.find(c=>c.id===e.target.value))}><option value="">Choose a company</option>{company&&!data?.companies.some(c=>c.id===company.id)&&<option value={company.id}>{company.name}</option>}{data?.companies.map(c=><option key={c.id} value={c.id}>{c.name} · {c.type==='GC'?'General Contractor':'Owner Representative'}</option>)}</select></Field>{!loading&&!data?.companies.length&&<p>Register a General Contractor or Owner Representative in Companies first, then return to designate it.</p>}<p className="muted">Up to 100 matching internal companies. Narrow the search to find another.</p></>:<><dl className="administration-dialog-summary"><div><dt>Current Home Organization</dt><dd>{data?.company?.name??'Not designated'}</dd></div><div><dt>New Home Organization</dt><dd>{company?.name}</dd></div></dl><p>This tenant-wide choice appears in internal employee invitations. Existing employees, invitations and permissions are preserved.</p><label className="checkbox-row"><input type="checkbox" checked={consent} disabled={locked} onChange={e=>setConsent(e.target.checked)}/><span>I confirm this company is the tenant’s home organization.</span></label></>}
 </AdministrationDialog>}</>;
}
