'use client';
import {useAdministrationNotice} from './administration-workspace';
import {useRef,useState,useSyncExternalStore} from 'react';
import {apiRequest} from '@/lib/apiClient';
import {ApiClientError,getErrorMessage} from '@/lib/errors';
import {CommandOwner,FrozenCommand} from '@/lib/frozen-command';
import {Button,Card,ErrorBanner,Input,SuccessBanner} from '@/components/ui';
import {AdministrationRecords,AdministrationSection} from './administration-records';
import {roleLabel} from '@/lib/display-labels';
type Member={userId:string;name:string;email:string;role:string;sessionVersion:number;accessDisabledAt:string|null;accountDisabledAt:string|null};
type Intent={userId:string;sessionVersion:number;disabledAt:string;reason:string;confirmed:true};
export function MemberAccessRecovery({projectId,owner,readOnly=true}:{projectId:string;owner:CommandOwner;readOnly?:boolean}){
 const token='member-access-recovery';useSyncExternalStore(owner.subscribe,owner.snapshot,owner.snapshot);
 const gate=useRef(new FrozenCommand<Intent>());
 const [members,setMembers]=useState<Member[]>([]),[selected,setSelected]=useState<Member>(),[reason,setReason]=useState(''),[consent,setConsent]=useState(false),[loading,setLoading]=useState(false),[offset,setOffset]=useState(0),[more,setMore]=useState(false),[error,setError]=useState<string>(),[success,setSuccess]=useState<string>();
 const [closed,setClosed]=useState(false),[readFailed,setReadFailed]=useState(false);const reading=useRef(false);
 const [,render]=useState(0),blocked=owner.blocked(token),locked=blocked||gate.current.locked||loading;
 async function load(page=offset){if(reading.current||blocked||gate.current.pending||gate.current.command&&!gate.current.stale)return;reading.current=true;setLoading(true);setError(undefined);
  try{const [r,context]=await Promise.all([apiRequest<{members:Member[];total:number}>(`/api/projects/${projectId}/members?includeDisabled=true&limit=100&offset=${page}`),apiRequest<{project:{status:string}}>(`/api/projects/${projectId}/template`)]);if(!gate.current.reload())return;setMembers(r.members.filter(m=>m.accessDisabledAt));setOffset(page);setMore(page+100<r.total);setClosed(context.project.status==='ARCHIVED');setSelected(undefined);setReason('');setConsent(false);setReadFailed(false);owner.release(token);}catch(e){setReadFailed(gate.current.stale);setError(getErrorMessage(e,'Unable to read current removed project members. Keep this decision held and retry Reload Removed Members.'));}finally{reading.current=false;setLoading(false);}
 }
 async function restore(){if(readOnly||closed||loading||!selected?.accessDisabledAt||!consent||!owner.claim(token))return;const attempt=gate.current.begin({userId:selected.userId,sessionVersion:selected.sessionVersion,disabledAt:selected.accessDisabledAt,reason:reason.trim(),confirmed:true},crypto.randomUUID());if(!attempt)return;render(n=>n+1);setError(undefined);
  try{const {userId,...body}=attempt.body;await apiRequest(`/api/projects/${projectId}/members/${userId}/restore`,{method:'POST',body,headers:{'Idempotency-Key':attempt.key}});gate.current.success();owner.release(token);setMembers(rows=>rows.filter(m=>m.userId!==userId));setSelected(undefined);setConsent(false);setSuccess('Project access restored. The member must sign in again. Previously removed admin grants and crew assignments remain separate decisions.');}
  catch(e){gate.current.fail(e instanceof ApiClientError?e.status:undefined);if(!gate.current.locked)owner.release(token);setError(getErrorMessage(e,'Outcome uncertain. Retry the unchanged access restoration.'));}finally{render(n=>n+1);}
 }
 useAdministrationNotice(token,{source:'Member Access Restoration',href:`/projects/${projectId}/admin/access-recovery`,tone:error?'error':success?'success':'status',message:gate.current.pending?'Saving the reviewed decision…':gate.current.stale?'State changed. Return to this action, deliberately reload and review again.':gate.current.command?'Outcome uncertain. Return to this action and retry the unchanged decision.':error??(success)??''});
 return <Card><AdministrationSection title="Restore Removed Members" level={2} locked={locked} description="Restore retained project membership with a recorded reason. Tenant-disabled accounts require Tenant Admin assistance. Earlier removal history, revoked admin grants and staffing decisions are preserved."><div className="stack">
 {(readOnly||closed)&&<p role="status">Project access restoration is read-only while this project is archived or its lifecycle cannot be verified. You can still inspect removed members.</p>}
 {gate.current.stale&&<p role="alert">{readFailed?'Current removed-member information could not be loaded.':'Access changed.'} Your reviewed restoration remains held. Reload Removed Members must successfully read current members and project context before a new selection and confirmation.</p>}
 {error&&<ErrorBanner message={error}/>} {success&&<SuccessBanner message={success}/>} <Button variant="secondary" disabled={blocked||loading||gate.current.pending||!!gate.current.command&&!gate.current.stale} onClick={()=>void load(0)}>{loading?'Loading…':gate.current.stale?'Reload Removed Members':'View Removed Members'}</Button>
 <p>Each Member Page loads up to 100 project members. The table below shows removed members from that page. Its filtering, selection and export apply to that page; use the Member Page buttons to inspect other project members.</p>
 <AdministrationRecords scrollable label="removed members on this project member page" rows={members} id={m=>m.userId} disabled={locked||loading} columns={[{key:'name',label:'Name',text:m=>m.name},{key:'email',label:'Email',text:m=>m.email},{key:'role',label:'Retained Role',text:m=>roleLabel(m.role)},{key:'access',label:'Tenant Account',text:m=>m.accountDisabledAt?'Disabled — contact Tenant Admin':'Active'}]} actions={m=><Button variant="secondary" disabled={readOnly||closed||locked||loading||!!m.accountDisabledAt} onClick={()=>{setSelected(m);setReason('');setConsent(false);setSuccess(undefined);}}>Review Access Restoration</Button>}/>
 <div className="row"><Button variant="secondary" disabled={locked||loading||!offset} onClick={()=>void load(Math.max(0,offset-100))}>Previous Member Page</Button><Button variant="secondary" disabled={locked||loading||!more} onClick={()=>void load(offset+100)}>Next Member Page</Button></div>
 {selected&&<section className="administration-command-review stack" aria-label="Confirm Member Access Restoration"><h3 className="panel-title">Restore Project Access for {selected.name}</h3><dl><dt>Retained Role</dt><dd>{roleLabel(selected.role)}</dd><dt>Removed (Your Local Time)</dt><dd>{selected.accessDisabledAt?new Date(selected.accessDisabledAt).toLocaleString():'Not recorded'}</dd></dl><label className="field"><span className="field-label">Restoration reason (10–1000 characters)</span><Input maxLength={1000} value={reason} disabled={locked} onChange={e=>{setReason(e.target.value);setConsent(false);}}/></label><label className="checkbox-row"><input type="checkbox" checked={consent} disabled={locked} onChange={e=>setConsent(e.target.checked)}/><span>I confirm restoring this project membership and requiring sign-in renewal.</span></label><div className="row"><Button disabled={readOnly||closed||blocked||loading||!consent||reason.trim().length<10||gate.current.pending||gate.current.stale} onClick={()=>void restore()}>{gate.current.pending?'Restoring…':gate.current.command&&!gate.current.stale?'Retry Unchanged Restoration':'Restore Project Access'}</Button><Button variant="secondary" disabled={locked} onClick={()=>setSelected(undefined)}>Cancel</Button></div></section>}
 </div></AdministrationSection></Card>;
}
