'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/lib/apiClient';
import {ApiClientError,getErrorMessage} from '@/lib/errors';
import {useUnsavedProgress} from '@/lib/use-unsaved-progress';
import {FrozenCommand} from '@/lib/frozen-command';
import {AdministrationRecords,AdministrationSection} from './administration-records';
import {Button,ErrorBanner,Input,SuccessBanner} from '@/components/ui';
import type {RecommissionCommand,RecommissionPreview,RecommissionRecord} from '@/modules/tenancy/application/recommission-project';
import type {UUID} from '@/shared/types';
import {AdministrationDialog} from './administration-dialog';
export function ProjectRecommissioning({projectId,onClose,onChanged,onLockChange}:{projectId:string;onClose:()=>void;onChanged:()=>void;onLockChange:(locked:boolean)=>void}){
 const [preview,setPreview]=useState<RecommissionPreview>(),[admin,setAdmin]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[members,setMembers]=useState<string[]>([]),[companies,setCompanies]=useState<string[]>([]),[work,setWork]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<string>(),[success,setSuccess]=useState<string>(),[completed,setCompleted]=useState<{periodId:string;snapshot:string;reason:string}>(),[revision,setRevision]=useState(0);
 const gate=useRef(new FrozenCommand<RecommissionCommand>()).current,url=`/api/projects/${projectId}/recommission`,heading=useRef<HTMLHeadingElement>(null);
 async function load(){if(gate.pending||gate.command&&!gate.stale)return;setBusy(true);setError(undefined);try{const response=await apiRequest<{preview:RecommissionPreview}>(url);setPreview(response.preview);setMembers([]);setCompanies([]);setWork([]);setConfirmed(false);setReason('');gate.reload();onLockChange(false);}catch(e){setError(getErrorMessage(e,'Unable to load recommissioning evidence.'));}finally{setBusy(false);}}
 useEffect(()=>{heading.current?.focus();void load();},[projectId]);
 async function submit(){if(!preview||busy)return;const body:RecommissionCommand=preview.periodId?{action:'OPEN',snapshot:preview.snapshot,reason:reason.trim(),confirmed:true,retainedMembers:members,retainedCompanies:companies,continuedWork:work}:{action:'BEGIN',snapshot:preview.snapshot,replacementAdminId:admin as UUID,reason:reason.trim(),confirmed:true};const attempt=gate.begin(body,crypto.randomUUID());if(!attempt)return;setBusy(true);onLockChange(true);setError(undefined);try{const result=await apiRequest<{periodId:string}>(url,{method:'POST',body:attempt.body,headers:{'Idempotency-Key':attempt.key}});gate.success();if(attempt.body.action==='OPEN')setCompleted({periodId:result.periodId,snapshot:attempt.body.snapshot,reason:attempt.body.reason});setSuccess(body.action==='BEGIN'?'Preparation started. The replacement administrator has independent project authority. Historical records and disabled access are retained.':'Project reopened following the recorded readiness review.');onChanged();if(body.action==='BEGIN')await load();}catch(e){gate.fail(e instanceof ApiClientError?e.status:undefined);setError(getErrorMessage(e,'The outcome is uncertain. Retry the unchanged command.'));}finally{setBusy(false);onLockChange(gate.locked);setRevision(n=>n+1);}}
 useUnsavedProgress(gate.locked);
 void revision;const locked=busy||gate.locked;
 const columns=[{key:'name',label:'Record',text:(r:RecommissionRecord)=>r.name},{key:'detail',label:'Evidence',text:(r:RecommissionRecord)=>r.detail}];
 return <AdministrationDialog title="Recommission this project" onClose={onClose} closeDisabled={busy||!!gate.command&&!gate.stale}><h3 className="panel-title" ref={heading} tabIndex={-1}>Review the next operating period</h3><p>Keep this project’s identity, files and request history. Prepare the next operating period before reopening.</p>{error&&<ErrorBanner message={error}/>} {success&&<SuccessBanner message={success}/>} {busy&&<p role="status">Loading or saving recommissioning…</p>}
 {completed&&<><details><summary>Recorded reopening evidence</summary><p>Operating period: {completed.periodId}</p><p>Reviewed snapshot: {completed.snapshot}</p><p>Reason: {completed.reason}</p></details><Button variant="secondary" onClick={onClose}>Close completed review</Button></>}
 {preview&&!completed&&<><p>Current status: {preview.status==='SETUP'?'Recommissioning preparation':preview.status}</p>
 {!preview.periodId?<><AdministrationRecords label="replacement administrator candidates" rows={preview.candidates} id={r=>r.id} columns={columns} disabled={locked} actions={r=><Button variant="secondary" aria-pressed={admin===r.id} disabled={locked} onClick={()=>setAdmin(r.id)}>Choose administrator</Button>}/><p className="muted">Existing disabled access is never restored. Existing operational roles are preserved; a new member receives Requester plus independent Project Admin authority. Review retained access in preparation.</p></>:<>
 <div className="row"><Link className="app-link" href={`/projects/${projectId}/admin`}>Review access and company associations</Link><Link className="app-link" href={`/projects/${projectId}/survey/teams`}>Review Survey organization</Link><Link className="app-link" href={`/projects/${projectId}/survey/operations`}>Review unfinished work</Link></div>
 <p className="muted">Departing personnel must be offboarded through the existing guarded controls. Authorized operational users can reassign or cancel unfinished requests during preparation. Canceled work retains its history. Select every remaining member, company and unfinished request to explicitly retain them for the next period.</p>
 <AdministrationSection title="Retained project access" open locked={locked}><AdministrationRecords label="retained members" rows={preview.members} id={r=>r.id} columns={columns} selected={members} onSelection={setMembers} disabled={locked}/></AdministrationSection>
 <AdministrationSection title="Retained company associations" locked={locked}><AdministrationRecords label="retained companies" rows={preview.companies} id={r=>r.id} columns={columns} selected={companies} onSelection={setCompanies} disabled={locked}/></AdministrationSection>
 <AdministrationSection title="Survey teams and invitation review" locked={locked}><AdministrationRecords label="retained Survey teams" rows={preview.teams} id={r=>r.id} columns={columns}/><AdministrationRecords label="outstanding invitations" rows={preview.invitations} id={r=>r.id} columns={columns}/></AdministrationSection>
 <AdministrationSection title="Unfinished work to continue" open locked={locked}><AdministrationRecords label="continued requests" rows={preview.work} id={r=>r.id} columns={columns} selected={work} onSelection={setWork} disabled={locked} actions={r=><Link className="app-link" href={`/projects/${projectId}/tickets/${r.id}`}>Inspect with authorized role</Link>}/></AdministrationSection>
 {preview.blockers.length>0?<div role="alert"><h3>Readiness blockers</h3>{preview.blockers.map(b=><p key={b}>{b}</p>)}</div>:<p>Current Area and Survey Manager readiness checks pass. Reload this review after any preparation change.</p>}
 </>}
 <label className="field"><span className="field-label">Recorded reason</span><Input value={reason} maxLength={2000} disabled={locked} onChange={e=>setReason(e.target.value)}/></label><label className="row"><input type="checkbox" checked={confirmed} disabled={locked} onChange={e=>setConfirmed(e.target.checked)}/>{preview.periodId?'I reviewed retained access, company associations, Survey staffing and each unfinished request.':'I confirm the named replacement administrator and the start of preparation.'}</label>
 <div className="row"><Button disabled={busy||gate.stale||(!gate.locked&&(!confirmed||!reason.trim()||(!preview.periodId&&!admin)||!!preview.periodId&&(preview.blockers.length>0||members.length!==preview.members.length||companies.length!==preview.companies.length||work.length!==preview.work.length)))} onClick={()=>void submit()}>{gate.locked?'Retry unchanged command':preview.periodId?'Confirm readiness and reopen':'Begin preparation'}</Button><Button variant="secondary" disabled={busy||!!gate.command&&!gate.stale} onClick={()=>void load()}>Reload current evidence</Button><Button variant="secondary" disabled={locked} onClick={onClose}>Close review</Button></div>
 </>}
 </AdministrationDialog>;
}
