'use client';
import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {apiRequest} from '@/lib/apiClient';
import {ApiClientError,getErrorMessage} from '@/lib/errors';
import {CommandOwner,FrozenCommand} from '@/lib/frozen-command';
import {Button,Card,ErrorBanner,Input,SuccessBanner} from '@/components/ui';
import {AdministrationDialog} from './administration-dialog';
import {AdministrationRecords} from './administration-records';
import type {ProjectTemplateListItem as Template} from '@/modules/tenancy/application/ports';
import type {reviewProjectTemplate} from '@/modules/tenancy/application/project-templates';
type InputTemplate={name:string;crewBuild:string;aorDepth:number;aorLevelLabels:string[];disciplineGroups:string[]};
type Review=Awaited<ReturnType<typeof reviewProjectTemplate>>;
type Intent={method:'POST'|'PATCH'|'DELETE';path:string;body:InputTemplate|{expectedSnapshot:string;confirmed:true}};
const crewLabels:Record<string,string>={FULL:'Full — Superintendent, Party Chief, Instrument Man',MEDIUM:'Medium — Party Chief, Instrument Man',SLIM:'Slim — Instrument Man'};
export function ProjectTemplates({owner}:{owner:CommandOwner}){
 const token='project-template';useSyncExternalStore(owner.subscribe,owner.snapshot,owner.snapshot);
 const gate=useRef(new FrozenCommand<Intent>()),createButton=useRef<HTMLButtonElement>(null),reviewTrigger=useRef<HTMLElement|null>(null),restoreFocus=useRef(false);
 const [templates,setTemplates]=useState<Template[]>([]),[name,setName]=useState(''),[crewBuild,setCrew]=useState('FULL'),[labels,setLabels]=useState('Area'),[groups,setGroups]=useState('Survey'),[open,setOpen]=useState(false),[step,setStep]=useState(0),[consent,setConsent]=useState(false),[error,setError]=useState<string>(),[success,setSuccess]=useState<string>(),[loading,setLoading]=useState(true);
 const [selected,setSelected]=useState<Review>(),[deleting,setDeleting]=useState(false);
 const [,rerender]=useState(0),[ready,setReady]=useState(false),[readFailed,setReadFailed]=useState(false);const reading=useRef(false);const blocked=owner.blocked(token),locked=loading||blocked||gate.current.locked;
 function close(){restoreFocus.current=true;setOpen(false);setDeleting(false);setSelected(undefined);setStep(0);setConsent(false);}
 async function load(renew=false){if(reading.current||owner.blocked(token)||gate.current.pending||gate.current.command&&!gate.current.stale)return;reading.current=true;setLoading(true);setError(undefined);try{const current=await apiRequest<{templates:Template[]}>('/api/project-templates');if(renew&&!gate.current.reload())return;setTemplates(current.templates);setReady(true);setReadFailed(false);if(renew){owner.release(token);close();setName('');}}catch(e){setReadFailed(gate.current.stale);setError(getErrorMessage(e,'Unable to read current project templates.'));}finally{reading.current=false;setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const levelLabels=labels.split('\n').map(v=>v.trim()).filter(Boolean),disciplineGroups=groups.split('\n').map(v=>v.trim()).filter(Boolean);
 async function review(id:string,remove=false){if(locked||open||deleting||reading.current||!owner.claim(token))return;reviewTrigger.current=document.activeElement instanceof HTMLElement?document.activeElement:null;reading.current=true;setLoading(true);setError(undefined);setSuccess(undefined);
  try{const {review:current}=await apiRequest<{review:Review}>(`/api/project-templates/${id}`);setSelected(current);setName(current.template.name);setCrew(current.template.crewBuild);setLabels(current.template.aorLevelLabels.join('\n'));setGroups(current.template.disciplineGroups.join('\n'));setStep(0);setConsent(false);setDeleting(remove);setOpen(!remove);}
  catch(e){setError(getErrorMessage(e,'Unable to read this current shared template. Reload Templates before reviewing again.'));}
  finally{reading.current=false;setLoading(false);owner.release(token);}
 }
 async function submit(remove=false){if(loading||blocked||!ready||gate.current.pending||gate.current.stale||!consent||remove&&selected?.referencingProjects.length||!owner.claim(token))return;
  const fields:InputTemplate={name:name.trim(),crewBuild,aorDepth:levelLabels.length,aorLevelLabels:levelLabels,disciplineGroups};
  const attempt=gate.current.begin(selected?{method:remove?'DELETE':'PATCH',path:`/api/project-templates/${selected.template.id}`,body:remove?{expectedSnapshot:selected.snapshot,confirmed:true}:{...fields,expectedSnapshot:selected.snapshot,confirmed:true}}:{method:'POST',path:'/api/project-templates',body:fields},crypto.randomUUID());if(!attempt){if(!gate.current.locked)owner.release(token);return;}rerender(n=>n+1);setError(undefined);
  try{await apiRequest(attempt.body.path,{method:attempt.body.method,body:attempt.body.body,headers:{'Idempotency-Key':attempt.key}});gate.current.success();owner.release(token);setSuccess(attempt.body.method==='DELETE'?'Unused shared template deleted. Established projects are unchanged.':attempt.body.method==='PATCH'?'Shared template updated for future project establishment. Existing projects are unchanged.':`${name.trim()} is ready to use when creating a project.`);close();setName('');void load();}
  catch(e){gate.current.fail(e instanceof ApiClientError?e.status:undefined);if(!gate.current.locked)owner.release(token);setError(getErrorMessage(e,'Outcome uncertain. Retry the unchanged catalog action.'));}finally{rerender(n=>n+1);}
 }
 useEffect(()=>{if(!open&&!deleting&&!loading&&restoreFocus.current){restoreFocus.current=false;if(success)createButton.current?.focus();else if(reviewTrigger.current?.isConnected)reviewTrigger.current.focus({preventScroll:true});}},[success,loading,open,deleting]);
 const message=<>{readFailed&&<p role="alert">Current project templates could not be loaded. Your reviewed template remains held. Reload Templates must successfully read the current catalog before fresh review and consent.</p>}{error&&<ErrorBanner message={error}/>}</>;
 return <Card title="Project Templates" description="Central IT manages reusable crew builds, Area levels and discipline groups for future project establishment. Existing projects retain their saved configuration."><div className="stack">
 {!deleting&&message}{success&&<SuccessBanner message={success}/>}
 {!open?<Button ref={createButton} disabled={blocked||loading||!ready||deleting} onClick={()=>{setSelected(undefined);setName('');setCrew('FULL');setLabels('Area');setGroups('Survey');setStep(0);setConsent(false);setOpen(true);setSuccess(undefined);}}>Create Project Template</Button>:<section className="administration-wizard stack" aria-label={selected?'Edit Project Template Wizard':'Create Project Template Wizard'}>
 <ol className="administration-wizard-steps">{['Template Details','Structure','Review'].map((label,i)=><li key={label} aria-current={step===i?'step':undefined}>{label}</li>)}</ol>
 {selected&&<p>Changes apply to future project establishment. {selected.referencingProjects.length} existing {selected.referencingProjects.length===1?'project keeps':'projects keep'} their current configuration and governing template reference.</p>}
 {step===0&&<><label className="field"><span className="field-label">Template name</span><Input maxLength={160} value={name} disabled={locked} onChange={e=>{setName(e.target.value);setConsent(false);}}/></label><label className="field"><span className="field-label">Crew build</span><select aria-label="Crew build" className="select" value={crewBuild} disabled={locked} onChange={e=>{setCrew(e.target.value);setConsent(false);}}>{Object.entries(crewLabels).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label></>}
 {step===1&&<><label className="field"><span className="field-label">Area level labels, one per line (top to bottom)</span><textarea className="input" rows={4} value={labels} disabled={locked} onChange={e=>{setLabels(e.target.value);setConsent(false);}}/></label><label className="field"><span className="field-label">Discipline groups, one per line</span><textarea className="input" rows={4} value={groups} disabled={locked} onChange={e=>{setGroups(e.target.value);setConsent(false);}}/></label></>}
 {step===2&&<><h3 className="panel-title">{selected?'Review Template Changes':'Review Project Template'}</h3><dl><dt>Name</dt><dd>{name}</dd><dt>Crew Build</dt><dd>{crewLabels[crewBuild]}</dd><dt>Area Levels</dt><dd>{levelLabels.join(' → ')||'No Area levels'}</dd><dt>Discipline Groups</dt><dd>{disciplineGroups.join(', ')||'None'}</dd></dl><label className="checkbox-row"><input type="checkbox" checked={consent} disabled={locked} onChange={e=>setConsent(e.target.checked)}/><span>{selected?'I confirm these shared template changes for future project establishment.':'I confirm this shared tenant template.'}</span></label>{gate.current.stale&&<p role="alert">State changed. Reload Templates before reviewing and confirming again.</p>}</>}
 <div className="row">{step>0&&<Button variant="secondary" disabled={locked} onClick={()=>{setStep(n=>n-1);setConsent(false);}}>Back</Button>}{step<2?<Button disabled={locked||!name.trim()} onClick={()=>setStep(n=>n+1)}>Next</Button>:<Button disabled={loading||blocked||!consent||gate.current.pending||gate.current.stale} onClick={()=>void submit()}>{gate.current.pending?'Saving…':gate.current.command&&!gate.current.stale?selected?'Retry Unchanged Changes':'Retry Unchanged Template':selected?'Save Template Changes':'Create Template'}</Button>}<Button variant="secondary" disabled={loading||blocked||gate.current.pending||!!gate.current.command&&!gate.current.stale} onClick={()=>{if(gate.current.stale)void load(true);else if(gate.current.reload()){owner.release(token);close();setError(undefined);void load();}}}>{gate.current.stale?'Reload Templates':'Cancel'}</Button></div>
 </section>}
 {loading&&<p role="status">Loading project templates…</p>}{!ready&&error&&<Button variant="secondary" disabled={loading||blocked} onClick={()=>void load()}>Reload Templates</Button>}
 <AdministrationRecords scrollable label="project templates" rows={templates} id={t=>t.id} disabled={locked||open||deleting} columns={[{key:'name',label:'Template',text:t=>t.name},{key:'crew',label:'Crew Build',text:t=>crewLabels[t.crewBuild]??t.crewBuild},{key:'depth',label:'Area Depth',text:t=>String(t.aorDepth)},{key:'areas',label:'Area Levels',text:t=>String(t.aorLevelCount)},{key:'disciplines',label:'Discipline Groups',text:t=>String(t.disciplineGroupCount)},{key:'usage',label:'Projects',text:t=>String(t.usageCount)},{key:'created',label:'Created',text:t=>new Date(t.createdAt).toLocaleDateString()}]} actions={t=><><Button variant="secondary" disabled={locked||open||deleting} onClick={()=>void review(t.id)}>Edit Template</Button><Button variant="danger" disabled={locked||open||deleting||t.usageCount>0} title={t.usageCount?'Referenced templates cannot be deleted.':undefined} onClick={()=>void review(t.id,true)}>Delete Template</Button>{t.usageCount>0&&<span>Used by {t.usageCount} {t.usageCount===1?'project':'projects'}; deletion blocked.</span>}</>}/>
 {deleting&&selected&&<AdministrationDialog title="Review Template Deletion" locked={locked} onDismiss={()=>{close();setError(undefined);}}>{message}<p>This permanently deletes this unused template from the shared tenant catalog. Established projects remain unchanged.</p><dl><dt>Template</dt><dd>{selected.template.name}</dd><dt>Crew Build</dt><dd>{crewLabels[selected.template.crewBuild]}</dd><dt>Area Levels</dt><dd>{selected.template.aorLevelLabels.join(' → ')||'None'}</dd><dt>Discipline Groups</dt><dd>{selected.template.disciplineGroups.join(', ')||'None'}</dd></dl>{selected.referencingProjects.length>0?<p role="alert">Deletion is blocked by: {selected.referencingProjects.map(p=>p.name).join(', ')}. Keep this template while projects reference it.</p>:<label className="checkbox-row"><input type="checkbox" checked={consent} disabled={locked} onChange={e=>setConsent(e.target.checked)}/><span>I confirm deleting this unused tenant template.</span></label>}{gate.current.stale&&<p role="alert">State changed. Reload Templates before a new deletion review.</p>}<div className="row"><Button variant="danger" disabled={loading||blocked||!consent||selected.referencingProjects.length>0||gate.current.pending||gate.current.stale} onClick={()=>void submit(true)}>{gate.current.pending?'Deleting…':gate.current.command&&!gate.current.stale?'Retry Unchanged Deletion':'Delete Unused Template'}</Button><Button variant="secondary" disabled={loading||blocked||gate.current.pending||!!gate.current.command&&!gate.current.stale} onClick={()=>{if(gate.current.stale)void load(true);else{close();setError(undefined);}}}>{gate.current.stale?'Reload Templates':'Cancel'}</Button></div></AdministrationDialog>}
 </div></Card>;
}
