'use client';
import type {ProjectCompanyRecord,MatchingTenantCompany} from '@/modules/tenancy/infrastructure/project-companies.reader';
import {companyNameKey} from '@/modules/tenancy/domain/company-name';
import {AdministrationDialog} from './administration-dialog';
import {AdministrationArea} from './administration-workspace';
import {ProjectMemberWizard,operationalRoleLabels} from './project-member-wizard';
import {ProjectDiagnostics} from './project-diagnostics';
import {MemberRoleAssignment} from './member-role-assignment';
import {useProjectWorkspace} from './project-shell-header';
import {headingCase} from '@/lib/heading-case';
import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {apiRequest} from '@/lib/apiClient';
import {ApiClientError,getErrorMessage} from '@/lib/errors';
import {FrozenCommand,CommandOwner} from '@/lib/frozen-command';
import {Button,Card,ErrorBanner,Input,SuccessBanner} from '@/components/ui';
import {AccountOffboarding} from './account-offboarding';
import {SurveyManagerHandover} from './survey-manager-handover';
import {AdministrationSection,AdministrationRecords} from './administration-records';
import {AdministrationBatch,type AdministrationAction} from './administration-batch';
import type {UUID} from '@/shared/types';
interface Member {companyType:string;userId:string;name:string;email:string;role:string;accessDisabledAt:string|null;accountDisabledAt:string|null;canAdminister?:boolean;customRoleId:string|null;customRoleName:string|null;sessionVersion:number}
interface Companies {companies:ProjectCompanyRecord[];candidates:Array<{userId:string;name:string;email:string;companyName:string}>}
type Intent={url:string;method:'POST'|'PATCH'|'DELETE';body:Record<string,unknown>;label:string;companyRemoval?:ProjectCompanyRecord[];companyAssociation?:MatchingTenantCompany};
export function ProjectAdministration({projectId,owner,onCompaniesChanged}:{projectId:string;owner:CommandOwner;onCompaniesChanged?:()=>void}){
 const token='project-administration';const ownerToken=useSyncExternalStore(owner.subscribe,owner.snapshot,owner.snapshot);
 const base=`/api/projects/${projectId}`;
 const [members,setMembers]=useState<Member[]>([]),[admins,setAdmins]=useState<Member[]>([]),[companies,setCompanies]=useState<Companies>();
 const workspace=useProjectWorkspace(),centralIT=workspace?.capabilities.centralIT===true;
 const [roleMember,setRoleMember]=useState<Member>();
 const [selected,setSelected]=useState<Member>(),[promotion,setPromotion]=useState<Member>();
 const [name,setName]=useState(''),[type,setType]=useState('SUBCONTRACTOR'),[companyId,setCompanyId]=useState(''),[email,setEmail]=useState('');
 const [templateId,setTemplateId]=useState(''),[template,setTemplate]=useState<{templates:Array<{id:string;name:string}>;project:{status:string;templateId:string|null;crewBuild:import('@/modules/tenancy/domain/types').CrewBuild;hasBeenActivated?:boolean}}>();
 const [error,setError]=useState<string>(),[success,setSuccess]=useState<string>(),[intent,setIntent]=useState<Intent>(),[consent,setConsent]=useState(false),[revision,setRevision]=useState(0),[loading,setLoading]=useState(false);
 const childLock=useRef(false);
 const gate=useRef(new FrozenCommand<Intent>()),generation=useRef(0);
 const [companySelection,setCompanySelection]=useState<string[]>([]);
 const [companyLookup,setCompanyLookup]=useState<{key:string;rows:MatchingTenantCompany[];loading:boolean;failed:boolean}>();
 const [memberSelection,setMemberSelection]=useState<string[]>([]),[adminSelection,setAdminSelection]=useState<string[]>([]),[removalQueue,setRemovalQueue]=useState<Member[]>([]),[batch,setBatch]=useState<AdministrationAction[]>();
 async function readAll<T>(path:string,field:string):Promise<T[]>{const all:T[]=[];for(let page=0;page<1000;page++){const result=await apiRequest<Record<string,T[]>>(`${path}?includeDisabled=true&limit=100&offset=${page*100}`);const rows=result[field];if(!Array.isArray(rows))throw new Error("Invalid administrative page");all.push(...rows);if(rows.length<100)return all;}throw new Error('Too many records; narrow the administrative population.');}
 async function load(){const epoch=++generation.current;setLoading(true);setError(undefined);
  try{const results=await Promise.all([readAll<Member>(`${base}/members`,'members'),centralIT?readAll<Member>(`${base}/administrators`,'administrators'):Promise.resolve<Member[]>([]),apiRequest<Companies>(`${base}/companies`),apiRequest<NonNullable<typeof template>>(`${base}/template`),readAll<Companies['candidates'][number]>(`${base}/companies`,'candidates')]);
   if(epoch!==generation.current)return;setMembers(results[0]);setAdmins(results[1]);setCompanies({...results[2],candidates:results[4]});setTemplate(results[3]);setTemplateId(results[3].project.templateId??'');return true;
  }catch(cause){if(epoch===generation.current)setError(getErrorMessage(cause,'Unable to load project administration.'));return false;}
  finally{if(epoch===generation.current)setLoading(false);}
 }
 useEffect(()=>{void load();return()=>{generation.current++;};},[projectId,centralIT]);
 useEffect(()=>{let current=true;const key=companyNameKey(name);
  if(!key){setCompanyLookup(undefined);return;}
  setCompanyLookup({key,rows:[],loading:true,failed:false});
  const timer=setTimeout(()=>{void apiRequest<{matchingCompanies:MatchingTenantCompany[]}>(`${base}/companies?companyName=${encodeURIComponent(name)}`).then(result=>{if(current)setCompanyLookup({key,rows:result.matchingCompanies,loading:false,failed:false});}).catch(()=>{if(current)setCompanyLookup({key,rows:[],loading:false,failed:true});});},300);
  return()=>{current=false;clearTimeout(timer);};
 },[name,base,companies?.companies]);
 const matchingCompanies=companyLookup?.key===companyNameKey(name)?companyLookup.rows:[];
 const checkingCompany=!!name.trim()&&(companyLookup?.key!==companyNameKey(name)||companyLookup.loading);
 const duplicateCompany=!!name.trim()&&(companies?.companies.some(company=>companyNameKey(company.name)===companyNameKey(name))||matchingCompanies.length>0);
 const closed=template?.project.status==='ARCHIVED';
 const locked=gate.current.locked||ownerToken!==null;
 const companyDialog=!!intent&&intent.url===`${base}/companies`;
 function dismissReview(){if(gate.current.locked||owner.blocked(token))return;setIntent(undefined);setConsent(false);setError(undefined);}
 const companyRemovalBlocked=intent?.companyRemoval?.some(c=>c.members||c.invitations||c.grants)??false;
 function propose(value:Intent){if(locked||childLock.current||closed||batch)return;setIntent(value);setConsent(false);setSuccess(undefined);}
 async function submit(){if(!intent||!owner.claim(token))return;const frozen=gate.current.begin(intent,crypto.randomUUID());if(!frozen){if(!gate.current.locked)owner.release(token);return;}setRevision(n=>n+1);setError(undefined);
  try{await apiRequest(frozen.body.url,{method:frozen.body.method,body:frozen.body.body,headers:{'Idempotency-Key':frozen.key}});gate.current.success();setSuccess(frozen.body.companyRemoval?'Selected companies removed from this project. Tenant company records and history are preserved.':`${frozen.body.label} completed. Affected authority changes require sign-in renewal.`);if(frozen.body.url===`${base}/companies`){setCompanySelection([]);onCompaniesChanged?.();}setIntent(undefined);setConsent(false);void load();}
  catch(cause){gate.current.fail(cause instanceof ApiClientError?cause.status:undefined);setError(getErrorMessage(cause,'The outcome is uncertain. Retry the same action.'));}
  finally{if(!gate.current.locked)owner.release(token);setRevision(n=>n+1);}
 }
 void revision;
 const review=intent&&<section className={companyDialog?"stack":"stack administration-command-review"} aria-label="Confirm project administration">{!companyDialog&&<h3 className="panel-title">{headingCase(intent.label)}</h3>}{companyDialog&&error&&<ErrorBanner message={error}/>}{companyDialog&&!intent.companyRemoval&&<><p>{intent.label}</p><dl>{typeof intent.body.name==='string'?<><dt>Company Name</dt><dd>{intent.body.name}</dd><dt>Company Type</dt><dd>{{GC:'General Contractor',SUBCONTRACTOR:'Subcontractor',OWNER_REP:'Owner Representative'}[intent.body.type as 'GC'|'SUBCONTRACTOR'|'OWNER_REP']}</dd></>:<>{intent.companyAssociation&&<><dt>Company Name</dt><dd>{intent.companyAssociation.name}</dd><dt>Company Type</dt><dd>{{GC:'General Contractor',SUBCONTRACTOR:'Subcontractor',OWNER_REP:'Owner Representative'}[intent.companyAssociation.type as 'GC'|'SUBCONTRACTOR'|'OWNER_REP']}</dd></>}<dt>Company ID</dt><dd className="administration-company-id">{String(intent.body.companyId)}</dd></>}</dl></>}{intent.companyRemoval&&<><p>Remove these company associations from this project. Tenant company records, employees and request history are preserved. You can associate the same Company IDs again later.</p><ul>{intent.companyRemoval.map(c=><li key={c.id}><strong>{c.name}</strong><div className="administration-company-id">Company ID: {c.id}</div>{c.members||c.invitations||c.grants?<p>{c.members} enabled project membership(s), {c.invitations} pending invitation(s), {c.grants} active authority grant(s). Resolve these through Personnel and Subcontractor Access before removal.</p>:<span>Ready to Remove</span>}</li>)}</ul>{companyRemovalBlocked&&<p role="alert">Resolve the listed dependencies, then reload and review the selection. No companies will be removed while any selected company is blocked.</p>}</>}<label className="checkbox-row"><input type="checkbox" checked={consent} disabled={locked} onChange={e=>setConsent(e.target.checked)}/><span>I confirm this action applies to this project.</span></label><div className="row"><Button disabled={owner.blocked(token)||!consent||companyRemovalBlocked||gate.current.pending||gate.current.stale} onClick={()=>void submit()}>{gate.current.pending?'Submitting…':gate.current.command?'Retry same action':intent.companyRemoval?'Confirm Company Removal':'Confirm action'}</Button><Button variant="secondary" disabled={owner.blocked(token)||gate.current.pending||!!gate.current.command&&!gate.current.stale} onClick={()=>{if(!owner.blocked(token)&&gate.current.reload()){owner.release(token);setIntent(undefined);setConsent(false);void load();}}}>Reload administration</Button></div>{gate.current.stale&&<p role="alert">State changed. Reload before another action.</p>}</section>;
 return <div className="stack">
 {error&&!companyDialog&&<ErrorBanner message={error}/>} {success&&<SuccessBanner message={success}/>} {loading&&<p role="status">Loading project administration…</p>}
 <AdministrationArea id="admin-personnel"><Card title="Project Personnel Administration" description={centralIT?"Membership, operational roles and independent Project Admin authority are separate.":"Project membership and operational roles."}><div className="stack">
 {closed&&<p>This archived project retains history. Access removal remains available; other administration is read-only.</p>}
 <AdministrationSection title="Add a Project Member" open locked={locked} description="Associate the person's company with this project first. Select eligible accounts, then review their project role.">
 {companies&&!closed&&<ProjectMemberWizard projectId={projectId} companies={companies.companies} canGrantAdmin={centralIT} owner={owner} onCreated={()=>void load()}/>}

 </AdministrationSection>
 <AdministrationSection title="Project Members and Access" open locked={locked}>
 {removalQueue.length>0&&<p>Reviewing {selected?.name}. Each person requires their own blocker evidence, reason and confirmation. {removalQueue.length} remaining in this review.</p>}
 {roleMember&&template&&<MemberRoleAssignment key={roleMember.userId} projectId={projectId} member={roleMember} owner={owner} crewBuild={template.project.crewBuild} reload={load} onAssigned={()=>void load()} onClose={()=>setRoleMember(undefined)}/>}
 {selected&&<AccountOffboarding key={selected.userId} subjectUserId={selected.userId} subjectName={selected.name} commandOwner={owner} scope={{kind:'PROJECT_ACCESS',projectId:projectId as UUID}} onLockChange={value=>{childLock.current=value;}} onResult={()=>void load()} onCancel={()=>{setSelected(undefined);setRemovalQueue([]);setMemberSelection([]);}}/>}
 {selected&&<Button variant="secondary" disabled={locked} onClick={()=>{const remaining=removalQueue.filter(m=>m.userId!==selected.userId);setRemovalQueue(remaining);setSelected(remaining[0]);}}> {removalQueue.length>1?'Review next selected person':'Close access review'}</Button>}
 <AdministrationRecords scrollable label="project members" rows={members} id={m=>m.userId} columns={[{key:'name',label:'Name',text:m=>m.name},{key:'email',label:'Email',text:m=>m.email},{key:'role',label:'Operational role',text:m=>m.customRoleName??operationalRoleLabels[m.role]??m.role},{key:'access',label:'Access',className:'administration-state-column',text:m=>m.accountDisabledAt?'Tenant disabled':m.accessDisabledAt?'Project disabled':'Enabled',render:m=><span className="badge badge-neutral">{m.accountDisabledAt?'Tenant Disabled':m.accessDisabledAt?'Project Disabled':'Enabled'}</span>}]} selected={memberSelection} onSelection={setMemberSelection} disabled={locked} selectionActions={<Button variant="secondary" disabled={!memberSelection.length||locked||!!batch} onClick={()=>{const queue=members.filter(m=>memberSelection.includes(m.userId));setPromotion(undefined);setRemovalQueue(queue);setSelected(queue[0]);}}>Review selected access removals</Button>} actions={m=><>{centralIT&&['GC','OWNER_REP'].includes(m.companyType)&&!m.accessDisabledAt&&!m.accountDisabledAt&&!closed&&!admins.find(a=>a.userId===m.userId)?.canAdminister&&<Button variant="secondary" disabled={locked||!!batch} onClick={()=>propose({url:`${base}/administrators`,method:'POST',body:{userId:m.userId,enabled:true,confirmed:true},label:`Grant independent Project Admin for ${m.name}; preserve ${operationalRoleLabels[m.role]??m.role}`})}>Grant Project Admin</Button>}{['REQUESTER','VIEWER','SURVEY_MANAGER','SURVEY_SUPERINTENDENT','PARTY_CHIEF','INSTRUMENT_MAN'].includes(m.role)&&m.userId!==workspace?.actorId&&!m.accessDisabledAt&&!m.accountDisabledAt&&!closed&&<Button variant="secondary" disabled={locked||!!batch} onClick={()=>{setSelected(undefined);setPromotion(undefined);setRoleMember(m);}}>Assign Role</Button>}<Button variant="secondary" disabled={locked||!!batch} onClick={()=>{setPromotion(undefined);setRemovalQueue([]);setSelected(m);}}>Preview access removal</Button>{m.role==='SURVEY_SUPERINTENDENT'&&!m.accessDisabledAt&&!m.accountDisabledAt&&<Button variant="secondary" disabled={locked||closed||!!batch} onClick={()=>{setSelected(undefined);setRemovalQueue([]);setPromotion(m);}}>Appoint as Survey Manager</Button>}</>}/>
 {promotion&&<SurveyManagerHandover key={promotion.userId} projectId={projectId} incoming={promotion} owner={owner} onLockChange={value=>{childLock.current=value;}} onResult={()=>void load()}/>}
 </AdministrationSection>
 </div></Card></AdministrationArea>
 {centralIT&&<AdministrationArea id="admin-personnel"><Card title="Project Admin Assignments" description="Only Tenant Admin creates or grants Project Admin. Current administrator assignments are listed here; project personnel remain on the member roster."><div className="stack">
 {centralIT&&companies&&!closed&&<ProjectMemberWizard projectId={projectId} companies={companies.companies} canGrantAdmin owner={owner} onCreated={()=>void load()} initialAdmin/>}
 <AdministrationSection title="Independent Project Admin Assignments" locked={locked} description="Granting administration preserves the person's operational role. Central IT can recover a project administration vacancy.">
 <AdministrationRecords scrollable label="project administrators" rows={admins.filter(m=>m.canAdminister)} id={m=>m.userId} columns={[{key:'name',label:'Name',text:m=>m.name},{key:'email',label:'Email',text:m=>m.email},{key:'role',label:'Operational role',text:m=>m.customRoleName??operationalRoleLabels[m.role]??m.role},{key:'grant',label:'Project Admin',className:'administration-state-column',text:m=>m.canAdminister?'Active grant':'No grant',render:m=><span className="badge badge-neutral">{m.canAdminister?'Active Grant':'No Grant'}</span>}]} selected={adminSelection} onSelection={setAdminSelection} disabled={locked} eligible={m=>closed||!m.accessDisabledAt&&!m.accountDisabledAt} actions={centralIT?m=><Button variant="secondary" disabled={locked||closed||!!batch||!!m.accessDisabledAt||!!m.accountDisabledAt} onClick={()=>propose({url:`${base}/administrators`,method:'POST',body:{userId:m.userId,enabled:!m.canAdminister,confirmed:true},label:`${m.canAdminister?'Revoke':'Grant'} Project Admin for ${m.name}`})}>{m.canAdminister?'Revoke Admin':'Grant Admin'}</Button>:undefined}/>
 {centralIT&&<div className="row">{[false].map(enabled=><Button key={String(enabled)} variant="secondary" disabled={!adminSelection.length||locked||closed||!!batch||!!intent} onClick={()=>setBatch(admins.filter(m=>adminSelection.includes(m.userId)&&!m.accessDisabledAt&&!m.accountDisabledAt&&!!m.canAdminister!==enabled).map(m=>({url:`${base}/administrators`,method:'POST',body:{userId:m.userId,enabled,confirmed:true},label:`${enabled?'Grant':'Revoke'} Project Admin for ${m.name} (${m.email})`})))}>{enabled?'Review selected Admin grants':'Review selected Admin revocations'}</Button>)}</div>}
 </AdministrationSection> </div></Card></AdministrationArea>}
 <AdministrationArea id="admin-companies"><Card title="Project Companies" description="Associating a company here grants no access to another project."><div className="stack">
 <AdministrationRecords scrollable label="project companies" rows={companies?.companies??[]} id={c=>c.id} columns={[{key:'name',label:'Company',text:c=>c.name,render:c=><strong>{c.name}</strong>},{key:'type',label:'Company type',text:c=>(({GC:'General contractor',SUBCONTRACTOR:'Subcontractor',OWNER_REP:'Owner representative'} as Record<string,string>)[c.type]??c.type)},{key:'id',label:'Reference',text:c=>c.id,render:c=><details><summary>Company ID</summary><span className="administration-company-id">{c.id}</span></details>}]} selected={companySelection} onSelection={setCompanySelection} disabled={locked||loading||!!intent||!!batch} selectionActions={<Button variant="danger" aria-haspopup="dialog" disabled={!companySelection.length||locked||loading||closed||!!intent||!!batch} onClick={()=>{const selected=companies?.companies.filter(c=>companySelection.includes(c.id))??[];if(selected.length)propose({url:`${base}/companies`,method:'DELETE',body:{companies:selected.map(c=>({id:c.id,associatedAt:c.associatedAt})),confirmed:true},label:'Review Company Removal',companyRemoval:selected});}}>Remove Selected</Button>}/>
 {!closed&&<AdministrationSection title="Register or Associate a Company" open locked={locked}>
 <label className="field"><span className="field-label">New company name</span><Input aria-invalid={duplicateCompany||undefined} aria-describedby={duplicateCompany?'company-name-conflict':undefined} value={name} maxLength={200} disabled={locked||closed} onChange={e=>setName(e.target.value)}/></label>
 {checkingCompany&&<p role="status">Checking for an existing tenant company…</p>}
  {duplicateCompany&&<p id="company-name-conflict" role="status">A tenant company with this name already exists. Removing a company from a project keeps its tenant record and history. Use the existing record below to add it to this project.</p>}
  {companyLookup?.key===companyNameKey(name)&&companyLookup.failed&&<p role="status">Company lookup is unavailable. Registration will still check for duplicates when confirmed; you can also use an existing Company ID below.</p>}
  {matchingCompanies.length>0&&<section className="stack" aria-label="Existing Tenant Companies"><h4 className="panel-title">Existing Tenant Companies</h4>{matchingCompanies.map(company=><div className="stack" key={company.id}><strong>{company.name}</strong><span>{{GC:'General Contractor',SUBCONTRACTOR:'Subcontractor',OWNER_REP:'Owner Representative'}[company.type as 'GC'|'SUBCONTRACTOR'|'OWNER_REP']}</span><span className="administration-company-id">Company ID: {company.id}</span>{company.associated?<p role="status">Already on this project.</p>:<Button variant="secondary" aria-haspopup="dialog" disabled={locked||loading||closed} onClick={()=>propose({url:`${base}/companies`,method:'POST',body:{companyId:company.id,confirmed:true},label:`Add ${company.name} to this project using its existing tenant record. Company details and history are preserved.`,companyAssociation:company})}>Review Add to Project</Button>}</div>)}</section>}
 <label className="field"><span className="field-label">Company type</span><select className="select" value={type} disabled={locked||closed} onChange={e=>setType(e.target.value)}>{['GC','SUBCONTRACTOR','OWNER_REP'].map(t=><option key={t} value={t}>{{GC:"General Contractor",SUBCONTRACTOR:"Subcontractor",OWNER_REP:"Owner Representative"}[t]}</option>)}</select></label>
 <Button aria-haspopup="dialog" disabled={!name.trim()||duplicateCompany||checkingCompany||loading||!companies||locked||closed} onClick={()=>propose({url:`${base}/companies`,method:'POST',body:{name:name.trim(),type,confirmed:true},label:`Register ${name.trim()} for this project`})}>Review company registration</Button>
 <label className="field"><span className="field-label">Existing company ID</span><Input value={companyId} disabled={locked||closed} onChange={e=>setCompanyId(e.target.value)}/></label><Button aria-haspopup="dialog" disabled={!companyId||locked||closed} onClick={()=>propose({url:`${base}/companies`,method:'POST',body:{companyId,confirmed:true},label:'Associate existing company with this project'})}>Review company association</Button>
 </AdministrationSection>} </div></Card></AdministrationArea>
 <AdministrationArea id="admin-settings" className="administration-settings-grid">{template?.project.status==='SETUP'&&!template.project.hasBeenActivated&&<Card title="Project Setup"><div className="stack">
 <label className="field"><span className="field-label">Applicable template (Setup only)</span><select className="select" value={templateId} disabled={locked||template?.project.status!=='SETUP'} onChange={e=>setTemplateId(e.target.value)}><option value="">Choose a template</option>{template?.templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><Button disabled={!templateId||locked||template?.project.status!=='SETUP'} onClick={()=>propose({url:`${base}/template`,method:'PATCH',body:{templateId,confirmed:true},label:'Select project template; existing setup is retained'})}>Review template selection</Button>
 </div></Card>}
 {template&&!closed&&<Card title="Project Access Settings"><div className="stack">
 <label className="field"><span className="field-label">Priority whitelist email</span><Input type="email" value={email} disabled={locked||closed} onChange={e=>setEmail(e.target.value)}/></label><div className="row">{(['POST','DELETE'] as const).map(method=><Button key={method} variant="secondary" disabled={!email||locked||closed} onClick={()=>propose({url:`${base}/whitelist`,method,body:{email},label:`${method==='POST'?'Add':'Remove'} ${email} ${method==='POST'?'to':'from'} priority whitelist`})}>{method==='POST'?'Review whitelist addition':'Review whitelist removal'}</Button>)}</div>
 <Button variant="danger" disabled={locked||template?.project.status!=='ACTIVE'} onClick={()=>propose({url:`${base}/archive`,method:'POST',body:{},label:'Archive this project; historical work is retained'})}>Review project archive</Button>
 </div></Card>}
 </AdministrationArea><AdministrationArea id="admin-diagnostics"><ProjectDiagnostics projectId={projectId} owner={owner}/></AdministrationArea>
 {batch&&<AdministrationBatch actions={batch} owner={owner} onDone={()=>void load()} onCancel={()=>{setBatch(undefined);setMemberSelection([]);setAdminSelection([]);void load();}}/>}
 {intent&&(companyDialog?<AdministrationDialog title={intent.companyRemoval?"Review Company Removal":intent.body.name?"Review Company Registration":"Review Company Association"} locked={locked} onDismiss={dismissReview}>{review}</AdministrationDialog>:review)}
 </div>;
}
