'use client';
import Link from 'next/link';
import {useState,useSyncExternalStore} from 'react';
import {apiRequest} from '@/lib/apiClient';
import {getErrorMessage} from '@/lib/errors';
import type {CommandOwner} from '@/lib/frozen-command';
import {Button,Card,ErrorBanner} from '@/components/ui';
import {AdministrationRecords} from './administration-records';
import {HeadingHelp} from './heading-help';
type ErrorRecord={id:string;route:string;method:string;status:number;durationMs:number;correlationId:string;errorCode:string|null;ticketId:string|null;priorStatus:string|null;observedAt:string;actorName:string};
type Report={diagnostics:{status:string;disabledMemberships:number;staleSubmitted:number;delayed:number;pendingCentralReviews:number};health:{requestCount:number;errorCount:number;currentAvgMs:number|null;currentSamples:number;baselineAvgMs:number|null;baselineSamples:number;p95Ms:number|null};delivery:{queuedCount:number;deliveredCount:number;averageDeliveryMs:number|null};errors:ErrorRecord[];generatedAt:string};
const time=(value:number|null)=>value===null?'No observations':`${(value/1000).toFixed(3)} s`;
function HealthDonut({label,total,attention,attentionLabel}:{label:string;total:number;attention:number;attentionLabel:string}){
 const fraction=total?attention/total:0,radius=42,circumference=2*Math.PI*radius;
 return <figure className="diagnostic-proportion"><svg viewBox="0 0 112 112" role="img" aria-label={`${label}: ${attention} ${attentionLabel} of ${total}`}><circle cx="56" cy="56" r={radius} fill="none" stroke="var(--line)" strokeWidth="12"/><circle cx="56" cy="56" r={radius} fill="none" stroke="var(--warning-ink, var(--action))" strokeWidth="12" strokeDasharray={`${fraction*circumference} ${circumference}`} transform="rotate(-90 56 56)"/><text x="56" y="61" textAnchor="middle" fill="currentColor">{total?`${Math.round(fraction*100)}%`:'—'}</text></svg><figcaption><strong>{label}</strong><span>{total?`${attention} ${attentionLabel} / ${total} observations`:'No observations in the last 24 hours'}</span></figcaption></figure>;
}
export function ProjectDiagnostics({projectId,owner}:{projectId:string;owner:CommandOwner}){
 const locked=useSyncExternalStore(owner.subscribe,owner.snapshot,owner.snapshot)!==null;
 const [report,setReport]=useState<Report>(),[loading,setLoading]=useState(false),[error,setError]=useState<string>(),[selected,setSelected]=useState<ErrorRecord>();
 async function load(){setLoading(true);setError(undefined);try{setReport(await apiRequest<Report>(`/api/projects/${projectId}/diagnostics`));setSelected(undefined);}catch(e){setError(getErrorMessage(e,'Unable to load project diagnostics. Current Project Admin or Tenant Admin access is required.'));}finally{setLoading(false);}}
 return <Card title="Project Diagnostics" description="Measured project request health and notification dispatch. Recorded observations begin with this version; they exclude unauthorized foreign-project attempts, invalid/revoked sessions, collection routes without verified project scope and failed telemetry writes. Request bodies, cookies, passwords and file contents are never recorded."><div className="stack">
 {error&&<ErrorBanner message={error}/>}<Button variant="secondary" disabled={locked||loading} onClick={()=>void load()}>{loading?'Loading…':report?'Refresh Diagnostics':'Load Project Diagnostics'}</Button>
 {report&&<><p className="muted">Last refreshed {new Date(report.generatedAt).toLocaleString()} · observed requests from the last 24 hours</p>
 <div className="diagnostic-proportions"><HealthDonut label="Request Errors" total={report.health.requestCount} attention={report.health.errorCount} attentionLabel="errors"/><HealthDonut label="Submission Notifications" total={report.delivery.queuedCount} attention={report.delivery.queuedCount-report.delivery.deliveredCount} attentionLabel="awaiting delivery"/></div>
 <HeadingHelp label="Response Timing" heading={<h3 className="panel-title">Response Timing</h3>} help="Server endpoint processing only, excluding browser/network time and telemetry persistence. Compare the last hour with the preceding 23 hours. These are measured samples, not a fixed service-level promise."/>
 <dl className="diagnostic-measures"><div><dt>Average · Last Hour</dt><dd>{time(report.health.currentAvgMs)} <small>({report.health.currentSamples} observations)</small></dd></div><div><dt>Average · Previous 23 Hours</dt><dd>{time(report.health.baselineAvgMs)} <small>({report.health.baselineSamples} observations)</small></dd></div><div><dt>95% of Responses Within</dt><dd>{time(report.health.p95Ms)}</dd></div><div><dt>Notification Dispatch After Queueing</dt><dd>{time(report.delivery.averageDeliveryMs)}</dd></div></dl>
 {report.health.currentSamples>=10&&report.health.baselineSamples>=10&&report.health.baselineAvgMs!==null&&report.health.currentAvgMs!==null&&report.health.currentAvgMs>report.health.baselineAvgMs*2&&<p role="status">Average response time is more than twice the previous observed period. Review recent errors and notification delivery, then escalate persistent delays through the Help Desk.</p>}
 <p>Notification time measures recorded queueing to dispatch or local capture. It does not prove when a survey team member read the request.</p>
 <HeadingHelp label="Work Requiring Attention" heading={<h3 className="panel-title">Work Requiring Attention</h3>} help="Pending review over 24 hours means a submitted request has not progressed for more than a day. Delayed requests, removed access and open tenant reviews are separate counts; they are not an overall health score."/>
 <dl className="diagnostic-measures"><div><dt>Pending Review Over 24 Hours</dt><dd>{report.diagnostics.staleSubmitted}</dd></div><div><dt>Delayed Requests</dt><dd>{report.diagnostics.delayed}</dd></div><div><dt>Removed Project Memberships</dt><dd>{report.diagnostics.disabledMemberships}</dd></div><div><dt>Pending Tenant Reviews</dt><dd>{report.diagnostics.pendingCentralReviews}</dd></div></dl>
 <AdministrationRecords scrollable label="recent project errors" rows={report.errors} id={r=>r.id} disabled={locked} columns={[{key:'time',label:'When',text:r=>new Date(r.observedAt).toLocaleString()},{key:'person',label:'Who',text:r=>r.actorName},{key:'result',label:'HTTP Result',text:r=>String(r.status)},{key:'action',label:'Where',text:r=>`${r.method} ${r.route}`},{key:'context',label:'Request State Before Action',text:r=>r.priorStatus?.replaceAll('_',' ')??'Not a request workflow action'}]} actions={r=><Button variant="secondary" disabled={locked} onClick={()=>setSelected(r)}>Investigate</Button>}/>
 <p>Showing up to 100 recent errors. Client/permission errors (400, 403), conflicts (409), and server errors have different causes; a request error does not automatically mean the system is unhealthy.</p>
 {selected&&<section className="administration-command-review stack" aria-label="Investigate Project Error"><h3 className="panel-title">Investigate HTTP {selected.status}</h3><dl><dt>Person</dt><dd>{selected.actorName}</dd><dt>Action</dt><dd>{selected.method} {selected.route}</dd><dt>Result</dt><dd>{selected.errorCode??'No structured error code'}</dd><dt>Time to Response</dt><dd>{time(selected.durationMs)}</dd><dt>Request State Before Action</dt><dd>{selected.priorStatus?.replaceAll('_',' ')??'No request state recorded'}</dd><dt>Investigation Reference</dt><dd className="administration-company-id">{selected.correlationId}</dd></dl><p>Include this reference, time, action and expected behavior when requesting assistance. Existing request history records prior workflow actions; diagnostic observations do not capture form contents or a person’s screen.</p><Link className="button button-secondary" href={`/projects/${projectId}/admin/help-desk`}>Open Help Desk to Escalate</Link><Button variant="secondary" onClick={()=>setSelected(undefined)}>Close Investigation</Button></section>}
 </>}
 </div></Card>;
}
