'use client';
import type {CommandOwner} from '@/lib/frozen-command';
import type {CustomRole,CustomRoleDirectory} from '@/modules/tenancy/domain/custom-role';
import {MEMBER_INVITATION_ROLES} from '@/modules/tenancy/domain/member-invitation';
import {OPERATIONAL_ROLE_PROFILES} from '@/modules/tenancy/domain/operational-role-profiles';
import {roleLabel} from '@/lib/display-labels';
import {CustomRoleCreation} from './custom-role-creation';
import {Card} from './card';
import {AdministrationSection} from './administration-records';
const roles=[
 ...MEMBER_INVITATION_ROLES.map(role=>[roleLabel(role),OPERATIONAL_ROLE_PROFILES[role].visibility,OPERATIONAL_ROLE_PROFILES[role].responsibilities]),
 ['Area Viewer','Authorized Areas.','View work within the assigned Areas.'],
 ['Department Manager / Department Lead','Assigned department; Department Lead also requires authorized Areas.','Department title administration is limited to current department authority.'],
 ['Subcontracts Coordinator','Subcontractor requests in this project.','View subcontractor work; this role does not grant Project Admin.'],
];
export function RolesPermissions({directory,owner,disabled,onCreated,onReload}:{directory?:CustomRoleDirectory;owner:CommandOwner;disabled?:boolean;onCreated:(role:CustomRole)=>void;onReload:()=>void}){return <Card title="Roles & Permissions" help="A reference to current fixed roles and separate grants. Every action also checks current account access, project scope, workflow state and required responsibility grants."><div className="stack"><p>Built-in permission profiles are read-only. Custom roles inherit one existing profile.</p><AdministrationSection title="Administrative Authority" open><dl className="administration-dialog-summary"><div><dt>Tenant IT / Central IT</dt><dd>Tenant administration and every project’s administration. Operational work requires its own project role. Manages tenant templates and the home organization.</dd></div><div><dt>Billing Viewer</dt><dd>A separate tenant role. Billing membership does not grant project administration or request analytics.</dd></div><div><dt>Project Admin</dt><dd>Independent grant to administer one project. Preserves the person’s operational role; does not automatically grant survey review or field execution.</dd></div></dl></AdministrationSection><AdministrationSection title="Operational Roles" open><div className="administration-table-scroll" tabIndex={0} role="region" aria-label="Operational roles and permissions"><table className="administration-table roles-permissions-table"><thead><tr><th scope="col">Role</th><th scope="col">Visibility</th><th scope="col">Current Responsibilities</th></tr></thead><tbody>{roles.map(([role,visibility,responsibilities])=><tr key={role}><th scope="row">{role}</th><td>{visibility}</td><td>{responsibilities}</td></tr>)}</tbody></table></div></AdministrationSection><AdministrationSection title="Separate Responsibility Grants"><p>Survey Reviewer grants authorize Area review. Company authority grants expand an eligible subcontractor Requester’s company visibility. Staffing links and protected obligations remain separately reviewed.</p><p>Disabled tenant accounts or project access prevent use of their roles and grants.</p></AdministrationSection><AdministrationSection title="Custom Roles" open help="Tenant-wide names for existing operational profiles. Only Tenant IT creates definitions. Project Admins can use saved roles for internal member invitations and enrollment. Definitions preserve their inherited profile."><CustomRoleCreation directory={directory} owner={owner} disabled={disabled} onCreated={onCreated} onReload={onReload}/></AdministrationSection></div></Card>;}
