import {Card} from './card';
import {AdministrationSection} from './administration-records';
const roles=[
 ['Requester','Own requests; subcontractor company visibility requires a separate company grant.','Create and submit own requests, respond to corrections and cancel eligible requests.'],
 ['Survey Manager','Project requests within current visibility rules.','Survey review, assignment, priority and need-by changes; manage survey staffing.'],
 ['Survey Superintendent','Authorized Areas; linked crew views also require current staffing links.','Area survey review requires a live Survey Reviewer grant; assignment and handover follow current coverage rules.'],
 ['Party Chief','Requests assigned to this Party Chief.','Allocate field work and perform permitted field review and coordination actions.'],
 ['Instrument Man','Directly assigned work or work for the currently linked Party Chief.','Start, delay and complete directly assigned field work.'],
 ['CAD Technician / CAD Lead','Project requests within current visibility rules.','View project requests. CAD role membership does not grant Project Admin or survey review.'],
 ['Viewer','Project requests within current visibility rules.','View project work. The Viewer role does not grant project administration.'],
 ['Area Viewer','Authorized Areas.','View work within the assigned Areas.'],
 ['Department Manager / Department Lead','Assigned department; Department Lead also requires authorized Areas.','Department title administration is limited to current department authority.'],
 ['Subcontracts Coordinator','Subcontractor requests in this project.','View subcontractor work; this role does not grant Project Admin.'],
];
export function RolesPermissions(){return <Card title="Roles & Permissions" help="A reference to current fixed roles and separate grants. Every action also checks current account access, project scope, workflow state and required responsibility grants."><div className="stack"><p>Current roles and permissions are read-only.</p><AdministrationSection title="Administrative Authority" open><dl className="administration-dialog-summary"><div><dt>Tenant IT / Central IT</dt><dd>Tenant administration and every project’s administration. Operational work requires its own project role. Manages tenant templates and the home organization.</dd></div><div><dt>Billing Viewer</dt><dd>A separate tenant role. Billing membership does not grant project administration or request analytics.</dd></div><div><dt>Project Admin</dt><dd>Independent grant to administer one project. Preserves the person’s operational role; does not automatically grant survey review or field execution.</dd></div></dl></AdministrationSection><AdministrationSection title="Operational Roles" open><div className="administration-table-scroll" tabIndex={0} role="region" aria-label="Operational roles and permissions"><table className="administration-table roles-permissions-table"><thead><tr><th scope="col">Role</th><th scope="col">Visibility</th><th scope="col">Current Responsibilities</th></tr></thead><tbody>{roles.map(([role,visibility,responsibilities])=><tr key={role}><th scope="row">{role}</th><td>{visibility}</td><td>{responsibilities}</td></tr>)}</tbody></table></div></AdministrationSection><AdministrationSection title="Separate Responsibility Grants"><p>Survey Reviewer grants authorize Area review. Company authority grants expand an eligible subcontractor Requester’s company visibility. Staffing links and protected obligations remain separately reviewed.</p><p>Disabled tenant accounts or project access prevent use of their roles and grants.</p></AdministrationSection></div></Card>;}
