'use client';
import {HeadingHelp} from '@/components/ui/heading-help';
import {RecordCollection} from '@/components/ui/record-collection';
import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {apiRequest} from '@/lib/apiClient';
import {ApiClientError,getErrorMessage} from '@/lib/errors';
import {CommandOwner,FrozenCommand} from '@/lib/frozen-command';
import {Button,ErrorBanner,Input,SuccessBanner} from '@/components/ui';
import type {ManagerPreview,ManagerAppointment} from '@/modules/tenancy/application/appoint-survey-manager';
interface Member {companyType:string;userId:string;name:string;role:string;accessDisabledAt:string|null;accountDisabledAt:string|null}
export function SurveyManagerHandover({projectId,incoming,owner,onLockChange,onResult}:{projectId:string;incoming:Member;owner:CommandOwner;onLockChange:(locked:boolean)=>void;onResult:()=>void}){
 const token='survey-manager-handover',ownerToken=useSyncExternalStore(owner.subscribe,owner.snapshot,owner.snapshot),gate=useRef(new FrozenCommand<ManagerAppointment>()).current;
 const [people,setPeople]=useState<Member[]>([]),[outgoing,setOutgoing]=useState(''),[coverage,setCoverage]=useState(''),[preview,setPreview]=useState<ManagerPreview>(),[reason,setReason]=useState(''),[consent,setConsent]=useState(false),[error,setError]=useState<string>(),[success,setSuccess]=useState(false),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0),[readFailed,setReadFailed]=useState(false),[closed,setClosed]=useState(false);
 const generation=useRef(0),heading=useRef<HTMLHeadingElement>(null),url=`/api/projects/${projectId}/survey/manager-handover`,blocked=ownerToken!==null&&ownerToken!==token;
 async function readChoices(){const all:Member[]=[];for(let offset=0;;offset+=100){const page=await apiRequest<{members:Member[];total:number}>(`/api/projects/${projectId}/members?limit=100&offset=${offset}`);all.push(...page.members);if(offset+100>=page.total)break;}return all.filter(p=>p.companyType!=='SUBCONTRACTOR'&&!p.accessDisabledAt&&!p.accountDisabledAt&&p.userId!==incoming.userId&&['SURVEY_MANAGER','SURVEY_SUPERINTENDENT'].includes(p.role));}
 useEffect(()=>{let current=true;heading.current?.focus();setLoading(true);void readChoices().then(all=>{if(current)setPeople(all);}).catch(e=>{if(current)setError(getErrorMessage(e,'Unable to load manager handover choices.'));}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;generation.current++;};},[projectId,incoming.userId]);
 async function reload(){if(loading||owner.blocked(token)||gate.pending||gate.command&&!gate.stale||!owner.claim(token))return;const epoch=++generation.current;setLoading(true);onLockChange(true);setError(undefined);
  try{const [all,context]=await Promise.all([readChoices(),apiRequest<{project:{status:string;crewBuild:string}}>(`/api/projects/${projectId}/template`)]);if(epoch!==generation.current)return;if(!gate.reload())return;setPeople(all);setClosed(context.project.status==='ARCHIVED'||context.project.crewBuild!=='FULL');setOutgoing('');setCoverage('');setPreview(undefined);setReason('');setConsent(false);setReadFailed(false);}
  catch(e){if(epoch===generation.current){setReadFailed(true);setError(getErrorMessage(e,'Unable to reload current manager handover choices.'));}}
  finally{if(epoch===generation.current){if(!gate.locked)owner.release(token);onLockChange(gate.locked);setLoading(false);setRevision(n=>n+1);}}
 }
 async function load(){if(loading||closed||blocked||gate.locked)return;const epoch=++generation.current;setLoading(true);setError(undefined);setPreview(undefined);setConsent(false);setSuccess(false);try{const value=await apiRequest<{preview:ManagerPreview}>(`${url}?outgoingUserId=${outgoing}&incomingUserId=${incoming.userId}&coverageUserId=${coverage}`);if(epoch===generation.current)setPreview(value.preview);}catch(e){if(epoch===generation.current){if(e instanceof ApiClientError&&e.status===409){gate.fail(409);owner.claim(token);onLockChange(true);}setError(getErrorMessage(e,'Unable to preview manager handover.'));}}finally{if(epoch===generation.current)setLoading(false);}}
 async function submit(){if(loading||closed||!preview||!consent||!reason.trim()||preview.blockers.length>0||!owner.claim(token))return;const command=gate.begin({outgoingUserId:preview.outgoing.userId,incomingUserId:preview.incoming.userId,coverageUserId:preview.coverage.userId,snapshot:preview.snapshot,reason:reason.trim(),confirmed:true},crypto.randomUUID());if(!command){if(!gate.locked)owner.release(token);return;}onLockChange(true);setRevision(n=>n+1);setError(undefined);try{await apiRequest(url,{method:'POST',body:command.body,headers:{'Idempotency-Key':command.key}});gate.success();setSuccess(true);onResult();}catch(e){gate.fail(e instanceof ApiClientError?e.status:undefined);setError(getErrorMessage(e,'The outcome is uncertain. Retry the same handover.'));}finally{if(!gate.locked)owner.release(token);onLockChange(gate.locked);setRevision(n=>n+1);}}
 void revision;
 return <section className="stack" aria-label="Survey Manager handover"><HeadingHelp label={"Appoint As Survey Manager"} heading={<h3 className="panel-title" tabIndex={-1} ref={heading}>Appoint {incoming.name} As Survey Manager</h3>} help={<span>Select who will take over this Superintendent’s Area coverage and reporting crews. Historical requests and assignments are retained. The outgoing manager’s access must be disabled separately after the appointment.</span>}/>
 {error&&<ErrorBanner message={error}/>} {loading&&<p role="status">Loading handover evidence…</p>}
 {closed&&<p>This project no longer permits Manager handover. Historical requests and assignments remain unchanged.</p>}
 {!success&&!closed&&<><label className="field"><span className="field-label">Outgoing Survey Manager</span><select className="select" value={outgoing} disabled={blocked||loading||gate.locked} onChange={e=>{setOutgoing(e.target.value);setPreview(undefined);setConsent(false);}}><option value="">Choose the outgoing manager</option>{people.filter(p=>p.role==='SURVEY_MANAGER').map(p=><option key={p.userId} value={p.userId}>{p.name}</option>)}</select></label>
 <label className="field"><span className="field-label">Superintendent taking over coverage</span><select className="select" value={coverage} disabled={blocked||loading||gate.locked} onChange={e=>{setCoverage(e.target.value);setPreview(undefined);setConsent(false);}}><option value="">Choose the coverage Superintendent</option>{people.filter(p=>p.role==='SURVEY_SUPERINTENDENT').map(p=><option key={p.userId} value={p.userId}>{p.name}</option>)}</select></label>
 <Button variant="secondary" disabled={!outgoing||!coverage||blocked||loading||gate.locked} onClick={()=>void load()}>Preview manager handover</Button>
 {preview&&<><p>{preview.incoming.name} will become Survey Manager. {preview.coverage.name} will receive {preview.areaIds.length} Area assignment(s) and {preview.reportingLinkIds.length} reporting crew(s) from them. Both people must sign in again.</p>{preview.blockers.length>0&&<RecordCollection label="manager handover blockers" records={<>{preview.blockers.map(b=><li key={b}>{b}</li>)}</>}/>}
 <label className="field"><span className="field-label">Reason for manager handover</span><Input value={reason} maxLength={1000} disabled={blocked||loading||gate.locked} onChange={e=>{setReason(e.target.value);setConsent(false);}}/></label><label className="checkbox-row"><input type="checkbox" checked={consent} disabled={blocked||loading||gate.locked} onChange={e=>setConsent(e.target.checked)}/><span>I confirm the displayed promotion and coverage transfer for this project.</span></label>
 <Button disabled={blocked||loading||gate.pending||gate.stale||!consent||!reason.trim()||preview.blockers.length>0} onClick={()=>void submit()}>{gate.pending?'Submitting…':gate.command&&!gate.stale?'Retry same handover':'Confirm manager appointment'}</Button></>}
 {gate.stale&&<p role="alert">{readFailed?'Current handover choices could not be loaded.':'The handover evidence changed.'} Your reviewed handover remains held. Reload handover must successfully read current members and project context before choosing and previewing again.</p>}
 {gate.command&&!gate.stale&&!gate.pending&&<p role="status">The response is uncertain. The original selection, reason and retry key are retained.</p>}
 <Button variant="secondary" disabled={blocked||loading||gate.pending||!!gate.command&&!gate.stale} onClick={()=>void reload()}>Reload handover</Button></>}
 {success&&<SuccessBanner message={`${incoming.name} appointed as Survey Manager. Coverage transferred; the outgoing manager’s access remains until separately disabled.`}/>}</section>;
}
