'use client';
import {useEffect,useRef,useState} from 'react';
import {apiClient,apiRequest} from '@/lib/apiClient';
import {ApiClientError,getErrorMessage} from '@/lib/errors';
import {FrozenCommand} from '@/lib/frozen-command';
import {Button,Input,ErrorBanner,SuccessBanner} from '@/components/ui';
import {AdministrationSection} from './administration-records';
import type {TeamArea} from '@/modules/tenancy/application/survey-teams';
import type {WorkforcePerson} from '@/modules/tenancy/application/survey-workforce';
import type {ReorganizationSelection,ReorganizationPreview} from '@/modules/tenancy/application/reorganize-survey';
import type {UUID} from '@/shared/types';
export function SurveyReorganization({projectId,archived,onLockChange,isBlocked}:{projectId:string;archived:boolean;onLockChange?:(locked:boolean)=>void;isBlocked?:()=>boolean}){
 const [people,setPeople]=useState<WorkforcePerson[]>([]),[areas,setAreas]=useState<TeamArea[]>([]),[build,setBuild]=useState('FULL'),[kind,setKind]=useState<'CREW'|'INSTRUMENT_MAN'>('CREW'),[chief,setChief]=useState(''),[instrument,setInstrument]=useState(''),[area,setArea]=useState(''),[superintendent,setSuperintendent]=useState('');
 const [preview,setPreview]=useState<Omit<ReorganizationPreview,'state'>>(),[reason,setReason]=useState(''),[consent,setConsent]=useState(false),[error,setError]=useState<string>(),[success,setSuccess]=useState<string>(),[loading,setLoading]=useState(false),[,render]=useState(0);
 const gate=useRef(new FrozenCommand<ReorganizationSelection&{snapshot:string;reason:string;confirmed:true}>()).current;
 const base=`/api/projects/${projectId}/survey/reorganization`;
 useEffect(()=>{let active=true;async function load(){try{const context=await apiClient.workforceContext(projectId);const personnel:WorkforcePerson[]=[],locations:TeamArea[]=[];for(let offset=0;;offset+=100){const page=await apiClient.workforce(projectId,{search:'',limit:100,offset});personnel.push(...page.data);if(offset+100>=page.total)break;}for(let offset=0;;offset+=100){const page=await apiClient.listTeamAreas(projectId,{search:'',limit:100,offset});locations.push(...page.data);if(offset+100>=page.total)break;}if(active){setPeople(personnel);setAreas(locations);setBuild(context.project.crewBuild);}}catch(cause){if(active)setError(getErrorMessage(cause,'Unable to load manpower choices.'));}}void load();return()=>{active=false;};},[projectId]);
 const locked=gate.locked||loading;
 function selection():ReorganizationSelection{return kind==='CREW'?{kind,partyChiefId:chief as UUID,areaId:area as UUID,superintendentId:build==='FULL'?superintendent as UUID:null}:{kind,instrumentManId:instrument as UUID,partyChiefId:chief as UUID};}
 async function inspect(){if(isBlocked?.())return;setLoading(true);setError(undefined);setSuccess(undefined);try{const query=new URLSearchParams(Object.entries(selection()).map(([k,v])=>[k,String(v)]));onLockChange?.(true);setPreview((await apiRequest<{preview:Omit<ReorganizationPreview,'state'>}>(`${base}?${query}`)).preview);setConsent(false);}catch(cause){onLockChange?.(false);setError(getErrorMessage(cause,'Unable to preview this move.'));}finally{setLoading(false);}}
 async function save(){if(isBlocked?.())return;if(!preview||!consent)return;const frozen=gate.begin({...preview.selection,snapshot:preview.snapshot,reason,confirmed:true},crypto.randomUUID());if(!frozen)return;render(v=>v+1);setError(undefined);try{await apiRequest(base,{method:'POST',body:frozen.body,headers:{'Idempotency-Key':frozen.key}});gate.success();onLockChange?.(false);setSuccess('Manpower move saved atomically. Requests and historical assignments were retained. Reload Team Management to see current staffing.');setPreview(undefined);setConsent(false);}catch(cause){gate.fail(cause instanceof ApiClientError?cause.status:undefined);setError(getErrorMessage(cause,'Outcome uncertain. Retry the unchanged move.'));}finally{render(v=>v+1);}}
 return <AdministrationSection title="Coordinate manpower movement" locked={locked}>
 <p>Move an intact crew or one Instrument Man. Reporting, Area and matching named-team changes commit together. Existing request assignments do not move automatically.</p>{archived&&<p>Archived project: manpower is read-only.</p>}{error&&<ErrorBanner message={error}/>} {success&&<SuccessBanner message={success}/>}
 <label className="field"><span className="field-label">Movement</span><select className="select" value={kind} disabled={locked||archived||!!preview} onChange={e=>setKind(e.target.value as typeof kind)}><option value="CREW">Party Chief / intact crew</option><option value="INSTRUMENT_MAN">Instrument Man between crews</option></select></label>
 {kind==='INSTRUMENT_MAN'&&<label className="field"><span className="field-label">Instrument Man</span><select className="select" value={instrument} disabled={locked||archived||!!preview} onChange={e=>setInstrument(e.target.value)}><option value="">Choose a person</option>{people.filter(p=>p.role==='INSTRUMENT_MAN').map(p=><option key={p.userId} value={p.userId}>{p.name} · {p.email}</option>)}</select></label>}
 <label className="field"><span className="field-label">{kind==='CREW'?'Party Chief / crew':'Destination Party Chief'}</span><select className="select" value={chief} disabled={locked||archived||!!preview} onChange={e=>setChief(e.target.value)}><option value="">Choose a Chief</option>{people.filter(p=>p.role==='PARTY_CHIEF').map(p=><option key={p.userId} value={p.userId}>{p.name} · {p.email}</option>)}</select></label>
 {kind==='CREW'&&<><label className="field"><span className="field-label">Destination Area</span><select className="select" value={area} disabled={locked||archived||!!preview} onChange={e=>setArea(e.target.value)}><option value="">Choose an Area</option>{areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{build==='FULL'&&<label className="field"><span className="field-label">Responsible Superintendent</span><select className="select" value={superintendent} disabled={locked||archived||!!preview} onChange={e=>setSuperintendent(e.target.value)}><option value="">Choose a Superintendent with existing Area coverage</option>{people.filter(p=>p.role==='SURVEY_SUPERINTENDENT').map(p=><option key={p.userId} value={p.userId}>{p.name} · {p.email}</option>)}</select></label>}</>}
 {!preview&&<Button disabled={locked||archived||!chief||(kind==='CREW'?(!area||build==='FULL'&&!superintendent):!instrument)} onClick={()=>void inspect()}>Preview manpower move</Button>}
 {preview&&<><ul>{preview.summary.map(line=><li key={line}>{line}</li>)}</ul>{preview.blockers.length>0&&<ErrorBanner message={preview.blockers.join('; ')}/>}<label className="field"><span className="field-label">Reason (10–1000 characters)</span><Input value={reason} maxLength={1000} disabled={locked} onChange={e=>setReason(e.target.value)}/></label><label className="checkbox-row"><input type="checkbox" checked={consent} disabled={locked} onChange={e=>setConsent(e.target.checked)}/><span>I confirm the displayed move and preservation of existing request assignments.</span></label><Button disabled={archived||loading||gate.pending||gate.stale||!consent||reason.trim().length<10||preview.blockers.length>0} onClick={()=>void save()}>{gate.pending?'Moving personnel…':gate.command?'Retry unchanged move':'Confirm manpower move'}</Button></>}
 {gate.stale&&<p role="alert">Staffing or work changed. Reload this preview before confirming again.</p>}
 <Button variant="secondary" disabled={loading||gate.pending||!!gate.command&&!gate.stale} onClick={()=>{if(gate.reload()){onLockChange?.(false);setPreview(undefined);setConsent(false);setError(undefined);render(v=>v+1);}}}>Reload / change selection</Button>
 </AdministrationSection>;
}
